### ISSUE TITLE
README for Prims Algorithm

### ISSUE THREAD

**Issue by marwahmanbir** [jainaman224/Algo_Ds_Notes#1000]
Add a README.md file to explain Prims Algorithm. The file should contain the following:
- Explanation
- Algorithm
- Pseudocode
- Example
- Time Complexity

Also add images/GIFs to explain if possible.

**Comment by Chaitanyasuma** [comment]
Can I work on this?

**Comment by marwahmanbir** [comment]
@Chaitanyasuma go for it.
