### ISSUE TITLE
README for Queen's Algorithm

### ISSUE THREAD

**Issue by marwahmanbir** [jainaman224/Algo_Ds_Notes#1001]
Add a README.md file to explain Queen's Algorithm. The file should contain the following:
- Explanation
- Algorithm
- Pseudocode
- Example
- Time Complexity

Also add images/GIFs to explain if possible.

**Comment by vsharma20v** [comment]
@marwahmanbir   can I take this issue ?

**Comment by jainaman224** [comment]
@vsharma20v Go ahead.
