### ISSUE TITLE
Bucket Sort in JavaScript

### ISSUE THREAD

**Issue by marwahmanbir** [jainaman224/Algo_Ds_Notes#1003]
Add your implementation for Bucket Sort Algorithm in JavaScript.

**Comment by ShivangiSingh17** [comment]
@marwahmanbir  I would like to work on this issue. Shall I begin?

**Comment by Anshuvats** [comment]
@marwahmanbir, can I work on this issue?

**Comment by jainaman224** [comment]
@ShivangiSingh17 Go ahead.

**Comment by jainaman224** [comment]
@Anshuvats Please pick up another issue.

**Comment by Anshuvats** [comment]
@jainaman224 okay

**Comment by Anshuvats** [comment]
@jainaman224 @marwahmanbir , I want to work on this issue.

**Comment by ShivangiSingh17** [comment]
@marwahmanbir I am already working on it and making the suggested changes, will send a PR soon.

**Comment by pavansai1** [comment]
I would like to pick up this as a part of GSScC'20
