### ISSUE TITLE
A* Algorithm in C++

### ISSUE THREAD

**Issue by marwahmanbir** [jainaman224/Algo_Ds_Notes#1005]
Add your implementation for A* Search Algorithm in C++.

**Comment by py93** [comment]
@marwahmanbir Hi, could you please assign this issue to me if it's available?

**Comment by marwahmanbir** [comment]
@py93 Go for it.

**Comment by shahkv95** [comment]
Because I am working in the same field and also I have command on python and C++, I would like to ask if I could take up this task?

**Comment by jainaman224** [comment]
@shahkv95 Go ahead.

**Comment by shahkv95** [comment]
@jainaman224  PR sent for A* Algorithm in C++ 
#1393

**Comment by suyashgautam** [comment]
I want to work on this issue for GSSOC2020

**Comment by pavansai1** [comment]
I would like to pick up this as a part of GSScC'20

**Comment by BhanujaAggarwal** [comment]
I would like to work on this issue in C++

**Comment by BhanujaAggarwal** [comment]
I would like to work on this issue in C++ @raghav-dalmia
