### ISSUE TITLE
A* Algorithm in Python

### ISSUE THREAD

**Issue by marwahmanbir** [jainaman224/Algo_Ds_Notes#1006]
Add your implementation for A* Search Algorithm in Python.

**Comment by mark-nakachon** [comment]
I am taking up this issue

**Comment by marwahmanbir** [comment]
@mark-nakachon I see that you have multiple issues already. Please take new issues only once you resolve the previously taken ones so that other people also get the chance to contribute.

**Comment by mark-nakachon** [comment]
I am ready with my pr

**Comment by marwahmanbir** [comment]
@mark-nakachon no need to mention here. We'll review it. :)
Also, you'll be assigned issues further on completion of all previously opened issues by you.

**Comment by Arunkumar0258** [comment]
Can I work on this if it's still available?

**Comment by jainaman224** [comment]
@Arunkumar0258 Go ahead.

**Comment by mark-nakachon** [comment]
No I am too close with my PR I will submit it in 2 days

**Comment by mark-nakachon** [comment]
I suggest @Arunkumar0258 to work on other issues

**Comment by marwahmanbir** [comment]
@mark-nakachon, you were not assigned this issue, so why did you start working on this? You won't get marked for your work if you do it this way, you know that right?

**Comment by shahkv95** [comment]
Heyy guys, would you allow me to work on this problem. I am familiar with it as I am working in the same field.

**Comment by shahkv95** [comment]
I would also like to add to the fact that this is really a very intelligent algorithm in itself. Now-a-days, it has found various applications in finding the shortest path irrespective of obstacles like maps and various arcade games. @jainaman224

**Comment by jainaman224** [comment]
@shahkv95 Go ahead.

**Comment by suyashgautam** [comment]
I want to work on this issue for GsSoc2020

**Comment by BhanujaAggarwal** [comment]
I would like to work on this issue in Python

**Comment by BhanujaAggarwal** [comment]
I would like to work on this issue in Python @raghav-dalmia
