### ISSUE TITLE
Cohen Sutherland

### ISSUE THREAD

**Issue by tusharsabhani** [jainaman224/Algo_Ds_Notes#1030]
Implementation of cohen sutherland algo

**Comment by tusharsabhani** [comment]
I would like to implement this in C

**Comment by piyush26c** [comment]
I would like to implement this in c++

**Comment by marwahmanbir** [comment]
@piyush26c go for it :+1:

**Comment by piyush26c** [comment]
I had an implementation, but a bit confused about how to pull request for this like should I add the issue number and issue name in the description of a pull request? what else I have to add?

**Comment by jainaman224** [comment]
You will be have PR template. Just fill that with issue number and basic information required.
