### ISSUE TITLE
Adding Prime Factorization in C.

### ISSUE THREAD

**Issue by jnikita356** [jainaman224/Algo_Ds_Notes#1041]
You have this algorithm in C++, python and java. I want to do it in C.

**Comment by archi14** [comment]
@jnikita356 I would like to do this.

**Comment by jainaman224** [comment]
@archi14 Please take another issue.

**Comment by archi14** [comment]
@jainaman224 oaky

**Comment by shreyasrivastava936** [comment]
Hi! I would like to work on this issue. please assign this task to me.
