### ISSUE TITLE
Adding FCFS (First Come First Served) Scheduling Algorithm in C++, Python, Java, Golang

### ISSUE THREAD

**Issue by MastersAbh** [jainaman224/Algo_Ds_Notes#1046]
Please assign it to me.

**Comment by somya-kapoor** [comment]
@jainaman224 Sir ,FCFS is already implemented in c++(https://github.com/jainaman224/Algo_Ds_Notes/blob/master/Scheduling_Algorithm/C%2B%2B/Non_Preemptive/First_Come_First_Served.cpp) .

**Comment by MastersAbh** [comment]
@jainaman224 , Yes, I found out that it is already implemented in C++, whereas I have implemented it in C++, Java, Python and Go.
Also, may I request you to accept this C++ code too, because the last one is copied from GFG. you can see it here https://www.geeksforgeeks.org/program-fcfs-scheduling-set-1/
