### ISSUE TITLE
Adding README.md file for Haversine formula with example in Java

### ISSUE THREAD

**Issue by ShivangiSingh17** [jainaman224/Algo_Ds_Notes#1056]
Haversine formula is used to find the distance between two points on a sphere. I would like to create a readme file containing example in Java for the same.

I would like to work on this issue.

**Comment by ShivangiSingh17** [comment]
@jainaman224 can you review this PR and suggest changes if any.

**Comment by jainaman224** [comment]
I think your PR is closed. Please reopen it for review.

**Comment by aadhar54** [comment]
I would like to work on this issue. Please assign it to me for GSSOC 2020

**Comment by shreyasrivastava936** [comment]
Hi! I would like to work on this issue. please assign this task to me.
