### ISSUE TITLE
Insertion sort using PHP

### ISSUE THREAD

**Issue by ShivangiSingh17** [jainaman224/Algo_Ds_Notes#1057]
Adding the code for insertion sort using PHP. Right now the code for insertion sort using C, C++, Java, javascript, python and ruby is there so adding this will add more to it.

**Comment by ShivangiSingh17** [comment]
@Aman Jain, @Piyush Aggarwal, I would like to work on this issue. Shall I proceed?

**Comment by jainaman224** [comment]
Please complete some of the already assigned issues first.
We have max 3 issues policy.

**Comment by ShivangiSingh17** [comment]
@jainaman224 can you please review all the PR's made.
