### ISSUE TITLE
Cycle detection problem in Linked list in C,C++

### ISSUE THREAD

**Issue by Vaibhavraj10** [jainaman224/Algo_Ds_Notes#1078]

**Comment by Vaibhavraj10** [comment]
@jainaman224 Can I work on this issue?

**Comment by jainaman224** [comment]
I think you are talking about Floyd's cycle detection algorithm.

**Comment by jainaman224** [comment]
Go ahead with C.

**Comment by Vaibhavraj10** [comment]
> I think you are talking about Floyd's cycle detection algorithm.

Yes!
