### ISSUE TITLE
Bubble_Sort Algorithm in Kotlin

### ISSUE THREAD

**Issue by shubhammantri1** [jainaman224/Algo_Ds_Notes#1087]
I want to write an algorithm for Bubble sort in kotlin.

**Comment by shubhammantri1** [comment]
Please @jainaman224 assign it to me and reviewed it.

**Comment by shubhammantri1** [comment]
Please review my algorithm. @jainaman224
And I also want to write more algorithms in Kotlin. So, For that shall i create a new PR.

**Comment by jainaman224** [comment]
Yes please create new PR and issues.
