### ISSUE TITLE
Breadth First Search algorithm in C

### ISSUE THREAD

**Issue by Vaibhavraj10** [jainaman224/Algo_Ds_Notes#1088]
It is an algorithm for traversing or searching tree or graph data structures.

**Comment by Vaibhavraj10** [comment]
@jainaman224 Please assign it to me.

**Comment by jainaman224** [comment]
Please look at existing issues before creating new one.

**Comment by Vaibhavraj10** [comment]
@jainaman224 There was no file in C language.

**Comment by jainaman224** [comment]
But there is an issue for this.
