### ISSUE TITLE
Sieve of Eratosthenes in C and README.md

### ISSUE THREAD

**Issue by Vaibhavraj10** [jainaman224/Algo_Ds_Notes#1114]
There is currently no file in C for this, in the repository. Neither any pending PR or Issue.

**Comment by Vaibhavraj10** [comment]
@jainaman224 Please assign it to me.

**Comment by rishabhgarg25699** [comment]
@Vaibhavraj10  Assigned but please send PR as soon as possible .

**Comment by Vaibhavraj10** [comment]
Yes @rishabhgarg25699 ! Sure!
