### ISSUE TITLE
Rabin Karp String Matching algorithm in C++

### ISSUE THREAD

**Issue by Anshuvats** [jainaman224/Algo_Ds_Notes#1130]

**Comment by Anshuvats** [comment]
@jainaman224 please assign to me.

**Comment by hiteshsubnani0128** [comment]
@jainaman224 Hello sir, please assign this to me I have an idea how this Algo work

**Comment by jainaman224** [comment]
@hiteshsubnani0128 Would you like to work in C?

**Comment by hiteshsubnani0128** [comment]
Yes sure even you can assign me for Python and JavaScript.

**Comment by jainaman224** [comment]
Can you create a new issue?
