### ISSUE TITLE
Rabin Karp String Matching algorithm in C, Python and JavaScript

### ISSUE THREAD

**Issue by hiteshsubnani0128** [jainaman224/Algo_Ds_Notes#1139]
Please assign me this issue

**Comment by Anshuvats** [comment]
@jainaman224, I would like to work on this issue. Shall I begin?

**Comment by jainaman224** [comment]
@Anshuvats Hitesh is working on it.

**Comment by Anshuvats** [comment]
@jainaman224  okay sir!

**Comment by pavansai1** [comment]
I would like to pick up this as a part of GSScC'20
