### ISSUE TITLE
Update files to take input at runtime

### ISSUE THREAD

**Issue by GOVINDDIXIT** [jainaman224/Algo_Ds_Notes#1160]
This is a parent issue. Contributors can select a file and do the changes to take input at runtime.

### Additional Info
While submitting a PR, Mention partial solving to this issue in your PR description. for ex: `Partly solves #123`.

**Comment by somya-kapoor** [comment]
@GOVINDDIXIT I would like to work on it.

**Comment by MastersAbh** [comment]
Hi @GOVINDDIXIT , Even I'd like to work for the same so that it is done quicker.

**Comment by jainaman224** [comment]
@MastersAbh Please create issue and start working on it.
