### ISSUE TITLE
Adding Sort an array of 0s, 1s and 2s in C++

### ISSUE THREAD

**Issue by komalsingh1** [jainaman224/Algo_Ds_Notes#1161]

**Comment by komalsingh1** [comment]
Added the code of Sort an array of 0s, 1s and 2s in C++

**Comment by jainaman224** [comment]
Please refer this issue in your PR.

**Comment by aadhar54** [comment]
I would like to work on this issue. Please assign it to me for Java .

**Comment by shreyasrivastava936** [comment]
Hi! I would like to work on this issue. please assign this task to me. I can implement the code in C++ & Java.

**Comment by HariniJeyaraman** [comment]
I would like to work on this. I am a GSSoC 2020 Participant. I can implement this in C, C++, Java and Python.  Please @jainaman224 @asha15 assign this issue to me.

**Comment by jainaman224** [comment]
@HariniJeyaraman Go ahead.
