### ISSUE TITLE
Greatest Common Divisor using python

### ISSUE THREAD

**Issue by hiteshsubnani0128** [jainaman224/Algo_Ds_Notes#1231]
please assign this issue to me

**Comment by jainaman224** [comment]
Name the algorithm you going to implement for GCD.

**Comment by hiteshsubnani0128** [comment]
Euclidean Algorithm

**Comment by yashpupneja** [comment]
Sir, Can you please assign this issue to me ?

**Comment by jainaman224** [comment]
@yashpupneja Please take another issue or choose any language in which it is not implemented.
