### ISSUE TITLE
Flood fill algorithm 

### ISSUE THREAD

**Issue by robotjellyzone** [jainaman224/Algo_Ds_Notes#1233]
This algorithm uses graphics library to fill the polygon with color.

**Comment by robotjellyzone** [comment]
Please assign it to me.

**Comment by bvishal8510** [comment]
@jainaman224 may I work on this issue? Or is anyone else working?

**Comment by robotjellyzone** [comment]
Hi, @bvishal8510 this has been **assigned to me** and I am working on it (slowly, due to my exams) , you can either take other issues which are up for grabs or make a new issue if you want.
