### ISSUE TITLE
Sum of cubes of first N natural numbers

### ISSUE THREAD

**Issue by singh-shreya6** [jainaman224/Algo_Ds_Notes#1274]
In C, C++, Java, Python and Go

**Comment by dipu989** [comment]
@jainaman224 @marwahmanbir  Can I work on this issue?

**Comment by marwahmanbir** [comment]
@singh-shreya6 Can you do this in any 3 of the above mentioned languages, so that @dipu989 could take the other two?
Also, you both can consider other languages too, like JavaScript, Kotlin etc. for this algo.

**Comment by singh-shreya6** [comment]
@marwahmanbir I have already written the code in these languages, I was waiting for the issue to get assigned. @dipu989 can you take some other language?

**Comment by dipu989** [comment]
@marwahmanbir @singh-shreya6  It's alright!
I will try to implement the solution in JavaScript.

**Comment by singh-shreya6** [comment]
@marwahmanbir  Please assign it to me.

**Comment by marwahmanbir** [comment]
@dipu989 sure, you can do it in JavaScript.

**Comment by dipu989** [comment]
@marwahmanbir  I have implemented the code using JavaScript for this issue.
Should I open a new issue and then Open a PR? 
Or can I open the PR referencing this issue only?

**Comment by marwahmanbir** [comment]
@dipu989 you can reference this issue in your PR.
