### ISSUE TITLE
Sum of G.P. in C, C++, Python, Java, Go

### ISSUE THREAD

**Issue by MastersAbh** [jainaman224/Algo_Ds_Notes#1279]

**Comment by marwahmanbir** [comment]
@MastersAbh go for it.

**Comment by marwahmanbir** [comment]
@MastersAbh I just saw that this algorithm already exists in the repo, so I'll suggest you to take another one. Closing this for now.

**Comment by somya-kapoor** [comment]
Hey, sum of gp is already an open issue (#1217)

**Comment by marwahmanbir** [comment]
@MastersAbh We can't move with this issue as @somya-kapoor is already working on it. Kindly check before opening an issue whether someone else is working on the same or not. Also, I see that you've opened multiple issues at the moment, I'd suggest you to work on max 2 issues at a time.
