### ISSUE TITLE
Updating inputs to take values at run time and adding programs for Nim game in C and Go

### ISSUE THREAD

**Issue by singh-shreya6** [jainaman224/Algo_Ds_Notes#1313]
I want to update inputs for::
Nim_Game.cpp
Nim_Game.java
Nim_Game.py

and I want to add:
Nim_Game.c
Nim_Game.go

**Comment by singh-shreya6** [comment]
@marwahmanbir Please assign it to me.

**Comment by marwahmanbir** [comment]
Hey @singh-shreya6, please open PRs after the issue is assigned, as pointed on Slack.
