### ISSUE TITLE
Number conversion folder 

### ISSUE THREAD

**Issue by somya-kapoor** [jainaman224/Algo_Ds_Notes#1319]
1) binary to decimal
2) binary to hexadecimal
3) binary to octal
4) decimal to hexadecimal 
5) decimal to octal
6) octal to binary
7) octal to decimal 
8) octal to hexadecimal
9) hexadecimal to binary
10) hexadecimal to decimal
11) hexadecimal to octal
in c , c++ , java , python and go

**Comment by MastersAbh** [comment]
Hi, #865 is already assigned to @khushal87 in C, C++, Java, Python.
You can work in Go.

**Comment by somya-kapoor** [comment]
But it's open for more than one and a half months and nothing has been done except one open pr for Decimal to binary (#881 )

**Comment by jainaman224** [comment]
Make multiple PR for this and comment on the issue that is already created.
Create multiple issues as well.
