### ISSUE TITLE
Reverse of a Number in C, C++, Java, Python, Go

### ISSUE THREAD

**Issue by singh-shreya6** [jainaman224/Algo_Ds_Notes#1330]
@rishabhgarg25699 Please assign this to me.

**Comment by bvishal8510** [comment]
@singh-shreya6 may I work on this issue

**Comment by singh-shreya6** [comment]
@bvishal8510 you can work on any other language than the ones that I am working on.

**Comment by rishabhgarg25699** [comment]
@singh-shreya6 Assigned .
