### ISSUE TITLE
Sum of digits of a number in C, C++, Java, Python and Go

### ISSUE THREAD

**Issue by singh-shreya6** [jainaman224/Algo_Ds_Notes#1331]
@rishabhgarg25699 Please assign it to me.

**Comment by bvishal8510** [comment]
@singh-shreya6 may I work on this issue

**Comment by singh-shreya6** [comment]
@bvishal8510 you can work on any other language than the ones that are mentioned here.

**Comment by rishabhgarg25699** [comment]
@singh-shreya6 Go Ahead
