### ISSUE TITLE
Updating files to take input at runtime (#1160)

### ISSUE THREAD

**Issue by prashant-mahanta** [jainaman224/Algo_Ds_Notes#1352]
**Updating the Files:**
Square_Root_Decomposition.cpp
Square_Root_Decomposition.py
Z_Algorithm.java
Z_Algorithm.py
Z_Algorithm.cpp
Longest_Repeating_Subsequence.cpp
Longest_Repeating_Subsequence.java
Longest_Repeating_Subsequence.py

**Comment by prashant-mahanta** [comment]
Please assign it to me.

**Comment by rishabhgarg25699** [comment]
@prashant-mahanta You  are assigned . Go Ahead .
