### ISSUE TITLE
Find all leap years between any two years in C, C++, Java, Python and Go

### ISSUE THREAD

**Issue by singh-shreya6** [jainaman224/Algo_Ds_Notes#1365]
@marwahmanbir @rishabhgarg25699 Please assign it to me.

**Comment by shahkv95** [comment]
I would like to take up this task if shreya is not doing it else way.
Thanx

**Comment by singh-shreya6** [comment]
@shahkv95 I am working on it.

**Comment by shahkv95** [comment]
Ohk thats great. I just said because its a few line of codes for every language, may be 2 to 5, and there were no updates since last 2 days. 
Anyways, enjoy the task.
@singh-shreya6  @marwahmanbir @jainaman224
