### ISSUE TITLE
Bitonic Sort in C, Python and Java

### ISSUE THREAD

**Issue by Bhairavi-shah** [jainaman224/Algo_Ds_Notes#1411]

**Comment by Bhairavi-shah** [comment]
Please assign this to me.

**Comment by rishabhgarg25699** [comment]
@Bhairavi-shah Assigned .

**Comment by aadhar54** [comment]
I would like to work on this issue. Please assign it to me for Java .

**Comment by shreyasrivastava936** [comment]
Hi! I would like to work on this issue. please assign this task to me. I can implement the code in all three languages C, Python and Java.
