### ISSUE TITLE
Find Bitonic Point in C, C++, Java, Go and Python

### ISSUE THREAD

**Issue by singh-shreya6** [jainaman224/Algo_Ds_Notes#1419]
@marwahmanbir @jainaman224 @rishabhgarg25699 please assign it to me.

**Comment by rishabhgarg25699** [comment]
@singh-shreya6 First do the assigned issue .

**Comment by MastersAbh** [comment]
All my assigned issues are done. Please assign this to me

**Comment by singh-shreya6** [comment]
Please assign it to me as all my issues are done

**Comment by singh-shreya6** [comment]
@rishabhgarg25699 @marwahmanbir @jainaman224
