### ISSUE TITLE
Total set bits from 1 to N in C, C++, Java, Python, Go

### ISSUE THREAD

**Issue by MastersAbh** [jainaman224/Algo_Ds_Notes#1451]
Please assign it to me @jainaman224 @rishabhgarg25699 @marwahmanbir

**Comment by jainaman224** [comment]
Please explain.

**Comment by MastersAbh** [comment]
It is a generic question, where the task is to count total number of set bits in all numbers ranging from 1 to N. The implementation is divided into 3 parts, and uses recursive solution as well as mathematical formulas and concepts.
