### ISSUE TITLE
Count total possible paths from (0,0) to (m,n) in a matrix in C, C++, Java, Go and Python

### ISSUE THREAD

**Issue by MastersAbh** [jainaman224/Algo_Ds_Notes#1452]
Please assign it to me @jainaman224 @marwahmanbir @rishabhgarg25699

**Comment by jainaman224** [comment]
Please specify algorithm.

**Comment by MastersAbh** [comment]
It is an implementation problem, where we need to find out total number of possible paths we can take in a grid from corner to corner, where only top and right move is allowed.
Has both recursive and DP solution, with DP solution preferred.
