### ISSUE TITLE
number of even and odd elements in an array

### ISSUE THREAD

**Issue by gourabk121** [jainaman224/Algo_Ds_Notes#1467]
I would like to do that

**Comment by rishabhgarg25699** [comment]
@gourabk121 Assigned Please send PR ASAP.

**Comment by gourabk121** [comment]
@rishabhgarg25699 done

**Comment by aadhar54** [comment]
I would like to work on this issue. Please assign it to me for Java .

**Comment by raksha009** [comment]
Hi! I want to work on this issue and implement it in python, java , c and c++.

**Comment by shreyasrivastava936** [comment]
Hi! I would like to work on this issue. please assign this task to me.

**Comment by aditi-2405** [comment]
Heyy.I want to work on this.Please assign it to me.

**Comment by akhileshsantoshwar** [comment]
I want to work on this issue. Please assign me this as a part of GSSoC 2020

**Comment by Anushka-Rajvanshi** [comment]
I would like to work on this issue using C++ and Java. Kindly assign this to me.

**Comment by jainaman224** [comment]
raksha009 Go ahead with Python.
aditi-2405 Go ahead with C++.
Anushka-Rajvanshi Go ahead with Java.

**Comment by afroz23** [comment]
I would like to work on this issue with c and c++.

**Comment by jainaman224** [comment]
@afroz23 Please pick up different issue.
