### ISSUE TITLE
In quick sort Readme file updation.

### ISSUE THREAD

**Issue by adigeak** [jainaman224/Algo_Ds_Notes#1479]
@jainaman224 In the quick sort example illustration we used any number as the pivot but in the code implementation we used last number as the pivot. So We should edit the Readme file and add the example with last element as the pivot.

**Comment by cherryWood55** [comment]
I would like to work on this issue.

**Comment by aadhar54** [comment]
I would like to work on this issue. Please assign it to me for GSSOC 2020

**Comment by lakshyajit165** [comment]
I would like to work on this issue.

**Comment by shreyasrivastava936** [comment]
Hi! I would like to work on this issue. please assign this task to me.

**Comment by diksha-dutt08** [comment]
I would like to work on this issue.

**Comment by jainaman224** [comment]
@lakshyajit165 Go ahead.

**Comment by lakshyajit165** [comment]
I have created a PR for this. @jainaman224 please review.
