### ISSUE TITLE
Sum_Of-Digits in kotlin

### ISSUE THREAD

**Issue by shubhammantri1** [jainaman224/Algo_Ds_Notes#1483]
@jainaman224 please assign it to me.

**Comment by raksha009** [comment]
Hi! I wanna work on it. Plz assign this issue to me.

**Comment by shubhammantri1** [comment]
Sorry, @raksha009 and @jainaman224 For messing up things. I already created PR:
Here is link
https://github.com/jainaman224/Algo_Ds_Notes/pull/1484

**Comment by Samriddhi25** [comment]
I would like to take on this issue.

**Comment by ritish099** [comment]
As a participant of GSSoC, I would like to work on this. Please assign this task to me. I can implement it in kotlin
