### ISSUE TITLE
Digit_Count in Kotlin

### ISSUE THREAD

**Issue by shubhammantri1** [jainaman224/Algo_Ds_Notes#1485]
@jainaman224 Please assign it to me.

**Comment by raksha009** [comment]
Hi! I wanna work on it. Plz assign this issue to me.

**Comment by shubhammantri1** [comment]
Sorry, @raksha009 and @jainaman224 For messing up things. I already created PR:
Here is link
https://github.com/jainaman224/Algo_Ds_Notes/pull/1486
