### ISSUE TITLE
Adding more functionalities in circular linked list for C language

### ISSUE THREAD

**Issue by rahulk16** [jainaman224/Algo_Ds_Notes#1502]
I want to add the following functionalities in the current Circular_Linked_List.c for hactoberfest:-

1. Counting nodes in a circular linked list
2. Inserting a node at the front of a circular linked list
3. Deleting the last node in a circular linked list
4. Deleting the first node in a circular linked list

Please assign me this issue for HactoberFest 2019.

**Comment by instinxt** [comment]
Is this still open i would like to contribute

**Comment by HardevKhandhar** [comment]
I would like to contribute to this issue for GSSoC'2020. Kindly assign this issue to me
