### ISSUE TITLE
Knuth Morris Pratt Algorithm (KMP) in javascript and c languages

### ISSUE THREAD

**Issue by rahulk16** [jainaman224/Algo_Ds_Notes#1503]
I want to add javascript and c implementation of KMP algorithm.
Please assign me this for HactoberFest 2019. @jainaman224

**Comment by shreyasrivastava936** [comment]
Hi! I would like to work on this issue. please assign this task to me for GSSoC'20.

**Comment by pavansai1** [comment]
I would like to pick up this as a part of GSScC'20
