### ISSUE TITLE
Adding Huffman Coding using C++

### ISSUE THREAD

**Issue by rahulk16** [jainaman224/Algo_Ds_Notes#1505]
I want to implement **Huffman Coding** with _C++ STL_. I will be using _priority_queue_, _vector_ and others if required.
Please assign me this issue for HactoberFest 2019. @jainaman224

**Comment by SubhradeepSS** [comment]
@jainaman224 I would like to work on this issue for gssoc'20

**Comment by suyashgautam** [comment]
I would like to work on this issue i have already implemented this algorithm in one of the contest
