### ISSUE TITLE
Stacks using queues

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#152]
Create stack using 2 queues.

**Comment by adishjain** [comment]
I'm working on this one. 
JAVA

**Comment by jainaman224** [comment]
Thank you. Please proceed.

**Comment by sasha2222** [comment]
I want to write c++ code for this

**Comment by jainaman224** [comment]
@sasha2222 Please proceed. Thank you.

**Comment by paliitr** [comment]
Can I work on python for this?

**Comment by paliitr** [comment]
Can I work on Python for this?

**Comment by jainaman224** [comment]
@paliitr Please proceed

**Comment by sourabhjagtap95** [comment]
Made a pull request #308 .
Stack Using 2 Queues in C

**Comment by shreyasrivastava936** [comment]
Hi! I want to work on this issue. please assign this task to me fo GSSoC'20.

**Comment by shreyasrivastava936** [comment]
I can do the same in java

**Comment by HariniJeyaraman** [comment]
Hi, I am a participant of GSSoC 2020 and want to contribute to this issue. I can implement this in C , C++, Java and Python. @jainaman224 @asha15 @shreyasrivastava936 @SakshiShreya please assign me this issue
