### ISSUE TITLE
Problems based on parantheses

### ISSUE THREAD

**Issue by astra-px** [jainaman224/Algo_Ds_Notes#1536]

**Comment by Tawishi** [comment]
I would like to work on this issue. Please provide a description.

**Comment by HariniJeyaraman** [comment]
Would checking for balanced parantheses problem fall under this category ? I can implement this code in C++ and Java.
Please provide a detailed description. Interested in working on this issue

**Comment by shreyasrivastava936** [comment]
Hi! I would like to work on this issue. please provide a description .I can implement the code in C++ and Java.

**Comment by mugdhajoshi** [comment]
I wouls like to work on this issue. Please provide the description. I will work in Python as part of GSSoC 2020

**Comment by jainaman224** [comment]
@Tawishi Go ahead with C++.

**Comment by Riyagoel2** [comment]
I would like to work on it in Java. @jainaman224

**Comment by jainaman224** [comment]
@Riyagoel2 Please pick issue with label up for grabs.

**Comment by lakshyajit165** [comment]
@jainaman224. I would like to work on this problem for its python implementation.

**Comment by Tawishi** [comment]
> @Tawishi Go ahead with C++.

Please provide a description of the required problems.

**Comment by jainaman224** [comment]
@Tawishi Please pick different issue. Due to unclear requirement.
