### ISSUE TITLE
All Fibonacci Series Algorithm  in C++ 

### ISSUE THREAD

**Issue by RedEye00** [jainaman224/Algo_Ds_Notes#1547]
I wanna contribute all the algorithm covered so far based on Fibonacci series related problems in c++ using recursive way, iterative way and dynamic programming.

**Comment by pranesh6876** [comment]
Hi, I would like to work on this issue, could please tell me more about it

**Comment by navi532** [comment]
I want to work on this issue. Tell us more about it

**Comment by biekymahato** [comment]
Hello Everyone, I want to Work on this issue and contribute in all possible ways.

**Comment by akhileshsantoshwar** [comment]
I want to work on this issue as a part of GSSoC. Please assign me this issue.

**Comment by asha15** [comment]
@RedEye00  Covering all the Fibonacci serious in one issue is not a good thing. please specify one particular algorithm

**Comment by RedEye00** [comment]
hey @asha15  I have raised issues #1696 and#1694 on specific algorithms plz see them and assign so that i can start working on it.
