### ISSUE TITLE
Sorting of linked list

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#155]
Sort link list using
- [ ] Bubble Sort
- [ ] Selection Sort
- [ ] Insertion Sort

**Comment by jennifertran** [comment]
Hey can I claim this issue? Does it matter what language I use?

**Comment by jainaman224** [comment]
Yes, you can please proceed and please specify the language you want to work in.

**Comment by jennifertran** [comment]
Ok I'll be posting my solutions in Java if that's alright with you.

**Comment by jainaman224** [comment]
@jennifertran Yes please proceed.

**Comment by vinitraj10** [comment]
i want to do this in c++

**Comment by jainaman224** [comment]
@vinitraj10 Please proceed.

**Comment by sahilrider** [comment]
i am working on C

**Comment by jainaman224** [comment]
@sahilrider Please proceed.

**Comment by paliitr** [comment]
Can I do this in python?

**Comment by jainaman224** [comment]
@paliitr Already implemented. Please checkout other issues.

**Comment by shiva1208** [comment]
I want to claim on C.

**Comment by sashafierce** [comment]
Added Insertion Sort on Linked List in C #315

**Comment by NirmalKumarJoshi** [comment]
Hello admin, I would like to work on this issue under GSSoC'19. I would like to do it in C++ language. Please assign me this issue.

**Comment by jainaman224** [comment]
@NirmalKumarJoshi Go ahead but it is already implemented for bubble and selection sort. You can implement insertion and merge sort.

**Comment by NirmalKumarJoshi** [comment]
Yeah sure @jainaman224.

**Comment by Rita-Okonkwo** [comment]
Hi @jainaman224 can I implement insertion sort algorithm using java?

**Comment by jainaman224** [comment]
@Rita-Okonkwo Go ahead.

**Comment by Rita-Okonkwo** [comment]
Thanks alot

**Comment by Rita-Okonkwo** [comment]
I'd send a PR by March 1st for GSSoC
