### ISSUE TITLE
Evaluating a postfix expression in C and C++

### ISSUE THREAD

**Issue by starwiz-7** [jainaman224/Algo_Ds_Notes#1552]
I would like to contribute by solving this issue.

**Comment by chandrikadeb7** [comment]
[prog.cpp.zip](https://github.com/jainaman224/Algo_Ds_Notes/files/4237425/prog.cpp.zip)

**Comment by HariniJeyaraman** [comment]
I would love to contribute to this issue. Please find the code in C for evaluating postfix expression.
[Postfix _Evaluation.zip](https://github.com/jainaman224/Algo_Ds_Notes/files/4241284/Postfix._Evaluation.zip)

**Comment by HardevKhandhar** [comment]
I would like to contribute to this issue for GSSoC'20

**Comment by Nandini9634** [comment]
I want to work on this issue for GSSOC 2020.

**Comment by HariniJeyaraman** [comment]
@raghav-dalmia  and @jainaman224  @asha15 please assign this issue to me.
[Postfix _Evaluation.zip](https://github.com/jainaman224/Algo_Ds_Notes/files/4271392/Postfix._Evaluation.zip)

**Comment by asha15** [comment]
@starwiz-7  are you GSSOC participant ?

**Comment by jainaman224** [comment]
@estarwiz-7 Go ahead with C++.

**Comment by chandrikadeb7** [comment]
Can I work on this issue in C language?

**Comment by jainaman224** [comment]
@chandrikadeb7 You already have 2 issues.

**Comment by nitashadhingra** [comment]
can i work in C? @jainaman224
