### ISSUE TITLE
Longest_Increasing_Subsequence code in Java

### ISSUE THREAD

**Issue by eKta37** [jainaman224/Algo_Ds_Notes#1554]
@adishjain @ayushin78 @nj4710 
As a GSSoC participant, I would like to work  on this, please assign this task  to me.

**Comment by shreyasrivastava936** [comment]
Hi, I would like to work on this issue, Please assign this task to me

**Comment by BhavishayGulati** [comment]
Hi,  I am a Gssoc20 participant and I would like to solve this issue.

**Comment by jainaman224** [comment]
@BhavishayGulati Go ahead.

**Comment by ravireddy07** [comment]
i would continue this issue by implementing in Python and C. @jainaman224

**Comment by jainaman224** [comment]
@ravireddy07 You already have 2 issues.

**Comment by 15aarushiGhadiya** [comment]
@somya-kapoor @jainaman224  i want to implement it in c . please assign this issue to me.
