### ISSUE TITLE
Add gradient descent implementation and description

### ISSUE THREAD

**Issue by nikochiko** [jainaman224/Algo_Ds_Notes#1558]
Add description for gradient descent: batch gradient descent and stochastic gradient descent.
Optionally, also add details about mini-batch GD.

**Comment by raghav-dalmia** [comment]
you can start implementing it.

**Comment by jainaman224** [comment]
Please specify the language.

**Comment by nikochiko** [comment]
I'm not working on this project anymore. Can assign someone else
