### ISSUE TITLE
Implementation of all C++ Standard Template Library (STL)

### ISSUE THREAD

**Issue by biekymahato** [jainaman224/Algo_Ds_Notes#1562]
The Standard Template Library (STL) is a set of C++ template classes to provide common programming data structures and functions such as lists, stacks, arrays, etc. It is a library of container classes, algorithms, and iterators. It is a generalized library and so, its components are parameterized. Working knowledge of template classes is a prerequisite for working with STL.

**This help for newbie Student to get all material and source related to Standard template library and help them for Competitive programming and Programming Skills.**

Example : 
        [STL(c++).txt](https://github.com/jainaman224/Algo_Ds_Notes/files/4244927/STL.c%2B%2B.txt)

**Comment by DawoodBhai420** [comment]
I want to work on this issue as a part of GSSoC'20.

**Comment by suyashgautam** [comment]
I want to work on this issue as a part of GSSoC'20

**Comment by lakshyajit165** [comment]
I would like to contribute to this issue.

**Comment by rudrakshi99** [comment]
I want to work on this issue as a part of GSSoC'20.

**Comment by jainaman224** [comment]
@DawoodBhai420 go ahead.

**Comment by biekymahato** [comment]
Hello @jainaman224 
    I want to work on it. As I created this issue because I have  knowledge about it,

**Comment by asha15** [comment]
@jainaman224  @biekymahato was created this issue, so i think it's better to assign this to him

**Comment by asha15** [comment]
@biekymahato  start to work on the issue. All the best

**Comment by mansikagrawal** [comment]
Please assign me this issue for set,map, multimap and multiset.

**Comment by mansikagrawal** [comment]
I would also like to add the deque, priority queue.

**Comment by biekymahato** [comment]
@mansikagrawal  I'm covering all this topic.
