### ISSUE TITLE
Creation of Armstrong number implementation in ruby

### ISSUE THREAD

**Issue by darkdebo** [jainaman224/Algo_Ds_Notes#1564]
There is no implementation of Armstrong number in ruby. So  I want to create a ruby implementation of this problem.

**Comment by darkdebo** [comment]
@jainaman224 can i add the ruby documentation section in armstrong number.

**Comment by jainaman224** [comment]
@darkdebo I am unable to understand.

**Comment by darkdebo** [comment]
Like c code link and online compilation given in documentation

**Comment by jainaman224** [comment]
Would be great. Thanks.

**Comment by darkdebo** [comment]
Thanks....

**Comment by darkdebo** [comment]
@jainaman224 can you please check my pr regarding this implementation, it's have been 2nd day and no review by mentors after there requested changes which I made. so I can't make another pull request.

**Comment by jainaman224** [comment]
@darkdebo Wait for your chance.

**Comment by darkdebo** [comment]
Okkk
