### ISSUE TITLE
Circular-Doubly-Linked-List

### ISSUE THREAD

**Issue by HardevKhandhar** [jainaman224/Algo_Ds_Notes#1565]
I would like to create a dynamic menu driven program for Circular Doubly Linked List in C++ for GSSoC'2020. Please assign this task to me.

**Comment by shreyasrivastava936** [comment]
Hi! I want to work on this program for C++ and Java . please assign this task to me fo GSSoC'20.

**Comment by asha15** [comment]
@HardevKhandhar Go for it

**Comment by Sejal30** [comment]
I want work on this issue in  C  and Java. Please asssign me.

**Comment by Kuljeet-123** [comment]
@HardevKhandhar  I am a GSSOC'20 participant ..can you please assign me this .

**Comment by HardevKhandhar** [comment]
> @HardevKhandhar I am a GSSOC'20 participant ..can you please assign me this .

Dear @Kuljeet-123 
I am also a GSSoC'2020 participant & not a mentor. @asha15 Ma'am is the mentor.
For your kind information, this task was assigned to me & a Pull Request has also been initiated.

Thank you

**Comment by mugdhajoshi** [comment]
I want to work on this in Python. Please assign me this as part of GSSoC 2020

**Comment by HardevKhandhar** [comment]
Dear Sir @jainaman224 

Please refer to this link: https://github.com/jainaman224/Algo_Ds_Notes/issues/1565#issuecomment-591566904

@asha15 Ma'am had already assigned this to me a few days ago.

With reference to same, a pull request has also been initiated.
You may review the Pull Request initiated by me on March 1

Thank you

**Comment by jainaman224** [comment]
@HardevKhandhar  I think I have assigned you as well. And don't ask for review in issues. We will review everyone's PR.

**Comment by HardevKhandhar** [comment]
Ok Noted. Thanks a lot.
