### ISSUE TITLE
Writing prime number algorithm  in JS

### ISSUE THREAD

**Issue by abhu-A-J** [jainaman224/Algo_Ds_Notes#1567]
@raghav-dalmia I am a participant in GSSoC, and I would like to work on the implementation of a prime number in JS.

**Comment by Samriddhi25** [comment]
I would like to take on this issue.

**Comment by asha15** [comment]
@abhu-A-J  Go for it

**Comment by Sejal30** [comment]
I want to work on this  issue as a part of GSSoC's 2020. Please assign me.

**Comment by abhu-A-J** [comment]
@asha15 @raghav-dalmia  this issue is addressed [here](https://github.com/jainaman224/Algo_Ds_Notes/pull/1723). Kindly revert back for changes. Thanks.
