### ISSUE TITLE
Updating the Quick Sort implementation .

### ISSUE THREAD

**Issue by abhu-A-J** [jainaman224/Algo_Ds_Notes#1568]
@raghav-dalmia I am a participant in GSSoC, and I would like to work on the implementation of a quick sort algorithm in JS. The current approach uses ES5 syntax and would like to update to ES6  and use a recursive definition as well for its implementation using a functional programming approach.

**Comment by raghav-dalmia** [comment]
Sure!!

**Comment by abhu-A-J** [comment]
@raghav-dalmia  @asha15 I have addressed this [here](https://github.com/jainaman224/Algo_Ds_Notes/pull/1719). Kindly revert back if changes are required.
