### ISSUE TITLE
Anagram program using one hash table instead of two hash table since it will improve memory complexity

### ISSUE THREAD

**Issue by shwetagurnani** [jainaman224/Algo_Ds_Notes#1569]

**Comment by shreyasrivastava936** [comment]
Hi! I want to work on this issue. please assign this task to me fo GSSoC'20.

**Comment by shreyasrivastava936** [comment]
I can implement it in java

**Comment by Manish-cloud** [comment]
I want to work on this issue using python programming language for GSSoC'20.

**Comment by jainaman224** [comment]
@shwetagurnani Go ahead with C++.
@Manish-cloud Go ahead with Python.

**Comment by shwetagurnani** [comment]
@jainaman224 please review my PR.I had my mid semester exams going on so was unable to contribute.
