### ISSUE TITLE
Dynamic stack using array

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#157]
Implement dynamic stack that is resizeable, So, there is no overflow.

**Comment by ayushin78** [comment]
working on this!

**Comment by paliitr** [comment]
Can I work on C++/Python for this?

**Comment by jainaman224** [comment]
@paliitr Please proceed.

**Comment by AyushRai09** [comment]
Can I implement this in C?

**Comment by KanchanThareja** [comment]
I want to work on this in C++.

**Comment by jainaman224** [comment]
@KanchanThareja Go ahead if it is already not implemented.

**Comment by Ishneet09** [comment]
Hi
Can I work on this in C++ ?

**Comment by jainaman224** [comment]
@Ishneet09 It is already implemented in C++. You can take up another issue.
