### ISSUE TITLE
Egg_Drop program implementation in C#

### ISSUE THREAD

**Issue by chandrikadeb7** [jainaman224/Algo_Ds_Notes#1570]
Please assign this issue to me. I want to work on the implementation of egg dropping puzzle code in **C#** language.

**Comment by shreyasrivastava936** [comment]
I would like to do the same in Java for GSSoC'20

**Comment by asha15** [comment]
@chandrikadeb7  Go for it

**Comment by chandrikadeb7** [comment]
> @chandrikadeb7 Go for it

Pull request done.
