### ISSUE TITLE
Add README.md file for Fibonacci_Number

### ISSUE THREAD

**Issue by HardevKhandhar** [jainaman224/Algo_Ds_Notes#1571]
I would like to contribute to GSSoC'2020 by making & adding a README.md file for given program

**Comment by pps121** [comment]
- ### **Fibonacci Number:**
In mathematics, the Fibonacci numbers are the numbers follow a particular sequence, called the Fibonacci sequence where every number after the initial two is the sum of its two preceding numbers:

0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, ...

- ### **Sequence properties:** 
We can define the fibonacci number using following recurrence relation:
F(n−2)=F(n)−F(n-1) or  F(n+2)=F(n)−F(n+1)

The first 21 Fibonacci numbers Fn are:

F0 | F1 | F2 | F3 | F4 | F5 | F6 | F7 | F8 | F9 | F10 | F11 | F12 | F13 | F14 | F15 | F16 | F17 | F18 | F19 | F20
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | 1 | 1 | 2 | 3 | 5 | 8 | 13 | 21 | 34 | 55 | 89 | 144 | 233 | 377 | 610 | 987 | 1597 | 2584 | 4181 | 6765

The sequence can also be extended to negative index n using the re-arranged recurrence relation

F−8 | F−7 | F−6 | F−5 | F−4 | F−3 | F−2 | F−1 | F0 | F1 | F2 | F3 | F4 | F5 | F6 | F7 | F8
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
−21 | 13 | −8 | 5 | −3 | 2 | −1 | 1 | 0 | 1 | 1 | 2 | 3 | 5 | 8 | 13 | 21

- ### **References:**  [Wikipedia](https://en.wikipedia.org/wiki/Fibonacci_number)

**Comment by asha15** [comment]
@HardevKhandhar The file should contain the following:
  
-  Explanation
-  Algorithm
-   Pseudocode
-   Example
-   Time Complexity

Also add images/GIFs to explain if possible. All the best
