### ISSUE TITLE
I would like to contribute to GSSoC'2020 by Writing Armstrong_Number code in Go

### ISSUE THREAD

**Issue by eaglewarrior** [jainaman224/Algo_Ds_Notes#1572]

**Comment by Samriddhi25** [comment]
I would like to take on this issue.

**Comment by asha15** [comment]
@eaglewarrior Start to work on it

**Comment by eaglewarrior** [comment]
@asha15  can you please assign me this issue

**Comment by eaglewarrior** [comment]
Hey @asha15 I have opened a PR #1712 please review and merge.Thanks

**Comment by jainaman224** [comment]
It is already present.
