### ISSUE TITLE
I would like to contribute to GSSoC'2020 by writing the Transformation of  all 1-D_Array programs in GO

### ISSUE THREAD

**Issue by eaglewarrior** [jainaman224/Algo_Ds_Notes#1573]

**Comment by raghav-dalmia** [comment]
@eaglewarrior Can you be more specific and list down those transformations?

**Comment by eaglewarrior** [comment]
@raghav-dalmia  I can write code on both left and right rotation Please assign me this issue

**Comment by raghav-dalmia** [comment]
@eaglewarrior array rotation is already there. You can contribute code for any other transformation.

**Comment by eaglewarrior** [comment]
@raghav-dalmia  I wanted to implement that in GO

**Comment by raghav-dalmia** [comment]
Okay, go with it.
