### ISSUE TITLE
I would like to work on linked lists, queue and stack data structures

### ISSUE THREAD

**Issue by nikkkhil067** [jainaman224/Algo_Ds_Notes#1575]

**Comment by biekymahato** [comment]
I want to work on this issue as a part of GSSoC'20.

**Comment by Nandini9634** [comment]
I would like to work on this issue.

**Comment by SohelRaja** [comment]
I want to contribute for this issue as a part of **GSSoc'20** using **Python** and **C++** Programming Language. **Please Assign me for this task**.

**Comment by jainaman224** [comment]
This is already implemented. Create separate issue with language if there is any implementation left.
