### ISSUE TITLE
Top View, Left View, Right View, Bottom View of Binary Tree in C, Java, Python language

### ISSUE THREAD

**Issue by AkanshaKamboj** [jainaman224/Algo_Ds_Notes#1577]
I would like to contribute on this

**Comment by shreyasrivastava936** [comment]
I would like to do the same in Java for GSSoC'20

**Comment by AkanshaKamboj** [comment]
The same has been contributed in c++, java, Python language. I will add the codes in C and will try to add it in any other language.

**Comment by raghav-dalmia** [comment]
@AkanshaKamboj sure go ahead with top, right, bottom view. The left view is already implemented in C.

**Comment by raghav-dalmia** [comment]
@shreyasrivastava936 you can implement top view in JAVA.

**Comment by Kuljeet-123** [comment]
@raghav-dalmia I would love to implement this in Python...can you please assign me this.

**Comment by santushtisharma10** [comment]
I would like to contribute in C ,please assign me this
