### ISSUE TITLE
Linked List MergeSort in C, C++, Java, Python

### ISSUE THREAD

**Issue by AkanshaKamboj** [jainaman224/Algo_Ds_Notes#1578]
I would like to contribute on this issue.

**Comment by AkanshaKamboj** [comment]
For GSSoC20

**Comment by asha15** [comment]
@AkanshaKamboj  Go ahead

**Comment by pratu098** [comment]
I want to implement this project in java. Please assign me this as a part of gssoc'20

**Comment by Kuljeet-123** [comment]
I would like to do it in C/C++..Please assign me this.
