### ISSUE TITLE
Implementing switch case statement for Linked List operations

### ISSUE THREAD

**Issue by lakshyajit165** [jainaman224/Algo_Ds_Notes#1579]
I went through the linked list code, and found that all the functions are called one after the other. It would be better to add a switch case statement to implement the functions as per user demand/order. I would like to implement the code for this.

**Comment by jainaman224** [comment]
We are not currently working with programs that takes user input. I am trying to create a framework for testing. We might be able to do so in future. For now, let's close this issue.
