### ISSUE TITLE
Mst algorithms

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#158]
Implement
- [ ] Kruskal Algorithm
- [ ] Prims Algorithm

**Comment by richa-coder** [comment]
Which language?

**Comment by jainaman224** [comment]
@richa-coder any language in which they are not implemented yet.

**Comment by jainaman224** [comment]
@richa-coder they are implemented only in cpp by the time.

**Comment by MahipaulTak** [comment]
can i work on it in python

**Comment by ayushin78** [comment]
@MahipaulTak Yes! you may proceed in any language in which the algorithms are still unimplemented.

**Comment by LauraLaureus** [comment]
@jainaman224 I have already programmed  Kruskal in Java for a university task. Do you want me to put a copy in your folder?

**Comment by jainaman224** [comment]
@LauraLaureus you can put that here include output and take example as input instead getting it from user. Thanks

**Comment by patniharshit** [comment]
I would like to contribute prims in C.

**Comment by jainaman224** [comment]
Please check, it should not be implemented yet

**Comment by patniharshit** [comment]
yes it is not implemented, I have sent a pull request.

**Comment by sez98** [comment]
i have created a pull request of the .java file for this algorithm

**Comment by sez98** [comment]
i would like to complete the prim's algo for MST in java?

**Comment by sez98** [comment]
I have completed the Kruskal_MST in Java format using disjoint sets... Please assist the pull request

**Comment by singh-shreya6** [comment]
I want to add Prims Algorithm in Java.

**Comment by zenithexpo** [comment]
Can I implement Kruskal_algorithm in C and Python?

**Comment by jainaman224** [comment]
@singh-shreya6 Go ahead.

**Comment by jainaman224** [comment]
@zenithexpo Go ahead.
