### ISSUE TITLE
Adding python implementation of karatsuba multiplication along with readme

### ISSUE THREAD

**Issue by lakshyajit165** [jainaman224/Algo_Ds_Notes#1581]
Karatsuba multiplication is a technique to multiply large numbers efficiently(it does simple multiplication too, ofcourse). I think we could implement it in python and add an explanation along with it(may be in the form of a readme file), so that it would be helpful for everyone.

**Comment by jainaman224** [comment]
Go ahead.

**Comment by lakshyajit165** [comment]
I have created a pull request for this. Please review.

**Comment by lakshyajit165** [comment]
@asha15, @jainaman224. Please review my PR so that I can raise other issues.
