### ISSUE TITLE
Wish to add to Machine Learning/Linear Regression

### ISSUE THREAD

**Issue by BALaka-18** [jainaman224/Algo_Ds_Notes#1582]
Linear Regression is a simple algorithm which, if not understood from the basics, turns out to be difficult. I want to contribute to this file by implementing the algorithm from scratch and visualize the best fit curve on a toy dataset based on the scratch algorithm, using matplotlib.
Also, wish to add a README file.

**Comment by raghav-dalmia** [comment]
@BALaka-18 we already have Linear regression implemented in python. You can choose any other language for the same. I am closing this issue, you can reopen it if you would like to.
