### ISSUE TITLE
Minesweeper algorithm implementation in C++

### ISSUE THREAD

**Issue by chandrikadeb7** [jainaman224/Algo_Ds_Notes#1598]
I would like to make a PR on the implementation of minesweeper algorithm in C++ for GSSoC'20.

**Comment by Nik-09** [comment]
I would like to contribute in gssoc 2020  to the project Algo_Ds_Notes regarding this issue.

**Comment by raghav-dalmia** [comment]
@chandrikadeb7 go ahead. @Nik-09 you can contribute it in any other language.
