### ISSUE TITLE
Program to find if a No. is a power of any Given No. in Java 

### ISSUE THREAD

**Issue by chanpreet1999** [jainaman224/Algo_Ds_Notes#1599]
I would like to add a program which tells if a number is power of any other given number
**Time Complexity - O(1)**

**Comment by agnes-sharan** [comment]
Hi I'd like ti take up this issue in C++ or Python if possible, but I am also open to implementing it in Java.

**Comment by chanpreet1999** [comment]
Hi @agnes-sharan  if you don't mind I can solve this in c and c++ too. You can try in python of you like.

**Comment by agnes-sharan** [comment]
Hey @chanpreet1999 sounds good!

**Comment by chanpreet1999** [comment]
@raghav-dalmia  please acknowledge.
