### ISSUE TITLE
Graph Algorithm

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#160]
Implement
- [ ] BFS
- [ ] DFS
- [ ] Topological Sort
- [ ] Strongly Connected Components

**Comment by adishjain** [comment]
Which one?

**Comment by richa-coder** [comment]
hey,Can i do this?

**Comment by jainaman224** [comment]
@richa-coder yes surely but please ensure they are not implemented in language you are willing to write code in.

**Comment by jainaman224** [comment]
Last two are new ones. You can code in any language.
Both of first two are implemented in cpp, python.
Bfs is also implemented in java.

**Comment by MayankTripathi01** [comment]
can i do topological sort in c @jainaman224

**Comment by KanchanThareja** [comment]
I want to work on topological sort in Java.

**Comment by jainaman224** [comment]
@KanchanThareja Go ahead.
