### ISSUE TITLE
Frequency of all elements in an array Java

### ISSUE THREAD

**Issue by chanpreet1999** [jainaman224/Algo_Ds_Notes#1601]
Count the frequency of each element in the array
**Time Complexity O(n)
Auxiliary Space O(n)**

**Comment by Bhavyaa08** [comment]
I can implement this in java.
Time complexity: O(n)
Space complexity: O(n)

**Comment by ishaan2908** [comment]
This can be done easily using a HashMap in JAVA. Can I do this?

**Comment by raghav-dalmia** [comment]
@Bhavyaa08 @ishaan2908, you can choose any other language.

**Comment by ishaan2908** [comment]
@raghav-dalmia I can do this in Python too.

**Comment by chandrikadeb7** [comment]
Can I do the same in C?

**Comment by SohelRaja** [comment]
Hi! I want to work this Issue as a part of **GSSoC'20**. I would like to add code for **java , c++ and python** if  you give me permission to do. Please assign for this task @chanpreet1999 @Bhavyaa08 @ishaan2908 @raghav-dalmia @chandrikadeb7 .

**Comment by Kuljeet-123** [comment]
I would love to do it in PHP.
