### ISSUE TITLE
Add Marix Operations in Java

### ISSUE THREAD

**Issue by chanpreet1999** [jainaman224/Algo_Ds_Notes#1603]
I would like to add a folder for Matrix Operations in java, which is currently missing

**Comment by LovepreetSingh12** [comment]
I would like to work on this issue as a part of GSSOC 20.

**Comment by singh-shreya6** [comment]
@chanpreet1999 It is requested that you should open two issues at a time. Please work on the ones assigned to you and close other issues.

**Comment by chanpreet1999** [comment]
Got it!
