### ISSUE TITLE
Chocolate Distribution Problem Java

### ISSUE THREAD

**Issue by chanpreet1999** [jainaman224/Algo_Ds_Notes#1604]
I want to add the implementation of chocolate distribution problem in Java.

**Comment by Manas2520** [comment]
I would like to give Chocolate Distribution Problem a try in C++

**Comment by singh-shreya6** [comment]
Sure @chanpreet1999. Go ahead.

**Comment by singh-shreya6** [comment]
@Manas2520 It is already implemented in C++. Please select some other language or issue.

**Comment by singh-shreya6** [comment]
@chanpreet1999 I see you already have two issues assigned. So closing this one. Please raise PR of the other two and then take up new ones.

**Comment by chanpreet1999** [comment]
Okay no problems. 
Thankyou for acknowledging
