### ISSUE TITLE
Spiral Array

### ISSUE THREAD

**Issue by shreyasrivastava936** [jainaman224/Algo_Ds_Notes#1607]
Spiral Array Algorithm traverses an array in a spiral order. I would like to implement it in java. It has implementation in C only.

**Comment by amoghjalan** [comment]
I would like to implement it in C++.

**Comment by shreyasrivastava936** [comment]
@raghav-dalmia @singh-shreya6 please assign this issue to me

**Comment by Jahnavi-Jonnalagadda** [comment]
Hi There! I would like to work on this issue in Python. Could you please assign this to me.

**Comment by jainaman224** [comment]
@amoghjalan Go ahead with C++.
@Jahnavi-Jonnalagadda  Go ahead with Python.

**Comment by Riyagoel2** [comment]
I would like to work on this in Java. Please assign it to me @jainaman224

**Comment by shortCircuit81** [comment]
assign this to me i will do this is java and c++

**Comment by jainaman224** [comment]
@shortCircuit81 Please pick issue with label `up-for-grab`.
