### ISSUE TITLE
Matrix search - C

### ISSUE THREAD

**Issue by amoghjalan** [jainaman224/Algo_Ds_Notes#1608]
Currently there is no program to implement matrix search in code except BFS. I would like to work to add it's programs in C, C++ and python to implement it in O(n).

**Comment by jainaman224** [comment]
@amoghjalan Go only with C.

**Comment by Neelaksh-Singh** [comment]
i am willing to make a readme for the same

**Comment by jainaman224** [comment]
@Neelaksh-Singh Create a new issue.
