### ISSUE TITLE
Maximum Flow

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#161]
Implement
- [ ] Ford Fulkerson method

**Comment by MayankTripathi01** [comment]
hey can i do this in c++

**Comment by jainaman224** [comment]
Try to do it in c, already implemented in c++

**Comment by MayankTripathi01** [comment]
how to reference this issue

**Comment by jainaman224** [comment]
just use #161 that the issue number in comment or description of your pull request

**Comment by AyushRai09** [comment]
I would like to give a try to this problem in C
