### ISSUE TITLE
To add a new folder for Stooge sort in C++

### ISSUE THREAD

**Issue by Harikrishnan6336** [jainaman224/Algo_Ds_Notes#1611]

**Comment by Harikrishnan6336** [comment]
There is no folder for Stooge sort. I would like to create one and contribute algorithms into it

**Comment by asha15** [comment]
@Harikrishnan6336  great.Please specify the language you want to work with

**Comment by Harikrishnan6336** [comment]
I would like to work with C++

**Comment by asha15** [comment]
@Harikrishnan6336 ok. How many open tickets you have so far?

**Comment by Harikrishnan6336** [comment]
@asha15  Tickets?? Do you mean the number of issues I am already assigned?? I am assigned with two issues

**Comment by asha15** [comment]
@Harikrishnan6336  yes.You can have only two issues at a time. 
So I'll assign this issue for you after the other two issues were closed
