### ISSUE TITLE
I would like to implement the GCD code for c and c++ 

### ISSUE THREAD

**Issue by Angshuman032001** [jainaman224/Algo_Ds_Notes#1613]

**Comment by Angshuman032001** [comment]
please assign the above mentioned issue to me for the program of GSSoC 2020

**Comment by akhileshsantoshwar** [comment]
I would like to work on this. Please assign me this issue as a part of GSSoC 2020

**Comment by LovepreetSingh12** [comment]
I want to implement this in JAVA as a part of GSSoC 2020.

**Comment by Manas2520** [comment]
I want to implement this in Python 3 as a participant of GSSoC 2020.

**Comment by Angshuman032001** [comment]
I have already started working on this issue. So it would be better if you start working on some other issue.

**Comment by Angshuman032001** [comment]
just realized that this code is already present under Euclidean Algorithm
