### ISSUE TITLE
Infix to Postfix in JAVA

### ISSUE THREAD

**Issue by SaranshDawra** [jainaman224/Algo_Ds_Notes#1618]
Implement using stack. 
@raghav-dalmia @asha15 @singh-shreya6 I am a GSSoC20 participant. Please assign me with this issue.

**Comment by spacemonkey1101** [comment]
Is this issue still open?

**Comment by jainaman224** [comment]
@spacemonkey1101 Please pick issue with label `up-for-grab`.
