### ISSUE TITLE
In Dynamic Programming Implementation of Optimal Strategy for a game.

### ISSUE THREAD

**Issue by biekymahato** [jainaman224/Algo_Ds_Notes#1622]
**Very important! Dynamic programming is a basic algorithm design technique, mostly used in optimization problems. You may need it whenever there is a problem asking you to calculate the optimal value or to count a number of ways to do a particular task etc.
Dynamic Programming divided into Several parts one of it is -
----Optimal Strategy for a Game-----
it's having many sets in this repo we are going to clear all types sets and Question-related to it.**

**Example of SET 1 :
Consider a problem statement-
Problem statement:** Consider a row of n coins of values v1 . . . vn, where n is even. We play a game against an opponent by alternating turns. In each turn, a player selects either the first or last coin from the row, removes it from the row permanently, and receives the value of the coin. Determine the maximum possible amount of money we can definitely win if we move first.

**Comment by biekymahato** [comment]
As Part of Gssoc'20, I want to work on it.
it is a unique algorithm in Dynamic programming.
So Assign to me
@jainaman224 @asha15

**Comment by asha15** [comment]
@biekymahato  which language you are using to implement this ?

**Comment by biekymahato** [comment]
@asha15 I know in c++ and java also.

**Comment by asha15** [comment]
@biekymahato  ok, go for it
