### ISSUE TITLE
2D Array in java, python, C,C++

### ISSUE THREAD

**Issue by raksha009** [jainaman224/Algo_Ds_Notes#1628]
Hi! I want to add code for matrix operations as a participant of GSSOC'20. Plz assign me this issue.
@SakshiShreya @asha15 @singh-shreya6

**Comment by singh-shreya6** [comment]
@raksha009 Please specify the operations you are going to add in Java.

**Comment by raksha009** [comment]
Like addition, subtraction, multiplication and finding transpose of a matrix.
@singh-shreya6

**Comment by singh-shreya6** [comment]
@raksha009 Go ahead.

**Comment by raksha009** [comment]
Okk thanks. I have a doubt - I should create different pull requests na for each operation !? Otherwise i think, the file would look a bit messy and long.
@singh-shreya6

**Comment by singh-shreya6** [comment]
You can put it inside a folder and create one PR. Please note, you can submit PR from March 1

**Comment by diksha-dutt08** [comment]
I would love to do it on python. Please assign me this issue.

**Comment by CSElonewolf** [comment]
I would like to contribute for this issue in `C`.The operation that I would like to add are Addition,Multiplication,Subtraction,Printing the 2D Array in Spiral order,Transposing the elements,Printing the top-left-right-bottom and top-right to bottom-left digonal elements and many others opeartions like that.Please Assign me for this issue.Thank You 
@singh-shreya6

**Comment by sngmanish** [comment]
I would like to work on this issue, using python. 
I will perform addition, subtraction, multiplication and finding transpose of a matrix, Printing the top-left-right-bottom and top-right to bottom-left, etc under a single folder in different files.

**Comment by Amitsharma45** [comment]
@singh-shreya6 @jainaman224 i can implement matrix addition ,subtraction ,and transpose in python 
can i start work on this issue.

**Comment by Amitsharma45** [comment]
i want work on 2D Array in python .
please assign this issue to me.

**Comment by singh-shreya6** [comment]
@raksha009 The initial issue created was for Addition, Subtraction , Multiplication and Transpose. All those PRs have been merged already. The remaining matrix operations don't fall under this issue. Please start taking up other issues also as opened by @jainaman224. I believe the other PRs will have to be closed now.
