### ISSUE TITLE
No. of times Sorted Array is Rotated in JAVA

### ISSUE THREAD

**Issue by ishaan2908** [jainaman224/Algo_Ds_Notes#1634]
This will be done in O(Log n) Time Complexity using Binary Search.

**Comment by ravireddy07** [comment]
Hello sir, I would like to work on this..!!

**Comment by PranshuPanwar** [comment]
Hello @ishaan2908 , I would love to solve this issue .
Thank you.

**Comment by ravireddy07** [comment]
I would like to work on this issue, Please assign this to me.
@adishjain  @ayushin78 @ishaan2908  @nj4710
