### ISSUE TITLE
Add Z_algorithm in C#

### ISSUE THREAD

**Issue by Harikrishnan6336** [jainaman224/Algo_Ds_Notes#1635]
The code for Z_algorithm is not available in C#. I would like to work on it! (Under GSSoC'20)

**Comment by Harikrishnan6336** [comment]
Please assign this to me . I am interested in doing this

**Comment by asha15** [comment]
@Harikrishnan6336 GO for it

**Comment by Harikrishnan6336** [comment]
> @Harikrishnan6336 GO for it
You didn't label it as GSSoC 20 does that mean solving this issue doesn't count for gssoc ? . Sorry I am new to git .

**Comment by Harikrishnan6336** [comment]
> @Harikrishnan6336 GO for it
You didn't label it as GSSoC 20 does that mean solving this issue doesn't count for gssoc ? . Sorry I am new to git .
