### ISSUE TITLE
Add PHP and C# code for Arithmetic Progression

### ISSUE THREAD

**Issue by chandrikadeb7** [jainaman224/Algo_Ds_Notes#1637]
I would like to contribute to this issue as a part of GSSoc'20

**Comment by topcoder69** [comment]
I would like to work on it as a part of GSSoc 2020. Please assign it to me!

**Comment by jainaman224** [comment]
@topcoder69 Go ahead.

**Comment by chandrikadeb7** [comment]
@jainaman224  Hey, I commented first to assign me the issue.

**Comment by jainaman224** [comment]
@chandrikadeb7 You already have 2 issues in your plate.
