### ISSUE TITLE
Implementation of KNN Algorithm using C

### ISSUE THREAD

**Issue by arghac14** [jainaman224/Algo_Ds_Notes#1640]
Would like to add K-Nearest Neighbors Algorithm using C. Please assign me this
@raghav-dalmia @asha15 @singh-shreya6 
This can be labelled as GSSOC20

**Comment by Nik-09** [comment]
Want to contribute in GSSOC 2020 by fixing this issue of Algo_Ds_Notes...

**Comment by asha15** [comment]
@arghac14  please specify the language you want to work with

**Comment by arghac14** [comment]
@asha15 Ok so I'll implement it using C

**Comment by Aman-Codes** [comment]
I would like to do the K Nearest Neighbors Algorithm using C++ as a part of GsSOC 2020. Please assign it to me @raghav-dalmia @asha15 @singh-shreya6

**Comment by asha15** [comment]
@Aman-Codes please create a issue for it
