### ISSUE TITLE
Implementation of Jump search in C and C++.

### ISSUE THREAD

**Issue by DawoodBhai420** [jainaman224/Algo_Ds_Notes#1641]
I want to work on this issue as a part of GSSoC'20.
Please assign me to this issue.

**Comment by Nik-09** [comment]
Want to contribute  in GSSOC 2020 by fixing this issue of Algo_Ds_Notes ....
please assign me to this project

**Comment by akhileshsantoshwar** [comment]
I would like to work on this issue as a part of GSSoC. Can you please assign me this issue.

**Comment by nitashadhingra** [comment]
i would like to contribute under GSSoC'20 @SakshiShreya @singh-shreya6 @MastersAbh
