### ISSUE TITLE
code to check if number is palindrome or not in C and C++

### ISSUE THREAD

**Issue by DawoodBhai420** [jainaman224/Algo_Ds_Notes#1646]
I want to work on this issue as a part of GSSoC'20.
Please assign me to this issue.

**Comment by mehmehul** [comment]
Would like to work on the issue in C and C++

**Comment by Sejal30** [comment]
Hello Sir,
I would like to work on this issue

**Comment by sonali623** [comment]
I would like to work on this issue as a part of GSSoc 2020

**Comment by akhileshsantoshwar** [comment]
I want to work on this issue as a part of GSSoC'20. Can you please assign me to this issue

**Comment by pratu098** [comment]
I want to work on this issue as a part of GSSoC'20.  please assign me to this issue

**Comment by DawoodBhai420** [comment]
@raghav-dalmia  can you please assign me to this issue?

**Comment by JanaSabuj** [comment]
I want to work on the JavaScript version of this issue. (GSSoC' 20)
