### ISSUE TITLE
BFS and DFS in Graph

### ISSUE THREAD

**Issue by Mustafiz04** [jainaman224/Algo_Ds_Notes#1647]
**Implementation of BFS and DFS for a graph in Java.**
I would like to work on this issue under GSSoC20. @singh-shreya6 @asha15 @raghav-dalmia please assign me with this issue.

**Comment by raghav-dalmia** [comment]
@Mustafiz04 It's already implemented in JAVA. You can choose any other language and reopen it.

**Comment by Mustafiz04** [comment]
can I do it in python??
