### ISSUE TITLE
Longest Common Subsequence in C

### ISSUE THREAD

**Issue by NVS16** [jainaman224/Algo_Ds_Notes#1649]
As LCS is not available in C, I would like to work on it as part of GsSoc 2020. @singh-shreya6  @asha15 @raghav-dalmia kindly assign this to me

**Comment by asha15** [comment]
@NVS16 Go for it

**Comment by Aman-Codes** [comment]
As LCS is not available in JavaScript, I would like to work on it as part of GsSoc 2020. @singh-shreya6 @asha15 @raghav-dalmia kindly assign this to me
