### ISSUE TITLE
Reverse singly linked list

### ISSUE THREAD

**Issue by abhishekgupta368** [jainaman224/Algo_Ds_Notes#1652]
The reverse of a single linked list is missing, can you please assign me that

**Comment by asha15** [comment]
@abhishekgupta368 Can you specify the languages you want to work with?

**Comment by abhishekgupta368** [comment]
I will do in python

**Comment by j-shreya** [comment]
I can implement this in java. Pls assign this to me

**Comment by asha15** [comment]
@abhishekgupta368 Go for it.
@j-shreya Please create a new issue for it

**Comment by abhishekgupta368** [comment]
thank you

**Comment by abhishekgupta368** [comment]
I have to create a new issue by the same name?

**Comment by asha15** [comment]
@abhishekgupta368 no. @j-shreya like to implement this algo using java,that's why i asked her to create a new issue for it. you don't need to create a new one, start to work on this.
All the best

**Comment by abhishekgupta368** [comment]
thank you

**Comment by Jahnavi-Jonnalagadda** [comment]
Hi There! I would like to work on this issue in Python. Could you please assign this to me @asha15

**Comment by ritish099** [comment]
As a participant of GSSoC, I would like to work on this. Please assign this task to me. I can implement it in c,c++;

**Comment by asha15** [comment]
@Jahnavi-Jonnalagadda  please create a new issue for it
@ritish099  the issue is already taken

**Comment by Riyagoel2** [comment]
Hi I would like to work on it in Java. Please assign it to me @asha15

**Comment by thesrijande** [comment]
assign me
