### ISSUE TITLE
Rat in a maze problem-Recursion and backtracking in c++

### ISSUE THREAD

**Issue by mansikagrawal** [jainaman224/Algo_Ds_Notes#1654]
Given a M*N matrix with some cells as blocked you have to-
1) Find path from source to dest
2)count number of path from source to dest
3)Print all possible paths

Please assign me the task.

**Comment by j-shreya** [comment]
I can implement this in java. Pls assign this to me

**Comment by TheDangerD0802** [comment]
I can implement this problem based on backtracking in C++. Please assign this to me.
