### ISSUE TITLE
Aggressive cows problem- Divide and conquer 

### ISSUE THREAD

**Issue by mansikagrawal** [jainaman224/Algo_Ds_Notes#1656]
Farmer John has built a new long barn, with N (2 <= N <= 100,000) stalls. The stalls are located along a straight line at positions x1,...,xN (0 <= xi <= 1,000,000,000).

His C (2 <= C <= N) cows don't like this barn layout and become aggressive towards each other once put into a stall. To prevent the cows from hurting each other, FJ wants to assign the cows to the stalls, such that the minimum distance between any two of them is as large as possible. What is the largest minimum distance?
Input
t – the number of test cases, then t test cases follows.
* Line 1: Two space-separated integers: N and C
* Lines 2..N+1: Line i+1 contains an integer stall location, xi
Output
For each test case output one integer: the largest minimum distance.
Example
Input:

1
5 3
1
2
8
4
9
Output:

3
Output details:

FJ can put his 3 cows in the stalls at positions 1, 4 and 8,
resulting in a minimum distance of 3.

It is a SPOJ famous problem. Please assgin me the issue to work on it with c++ and java.

**Comment by Bhavyaa08** [comment]
I can implement this in java

**Comment by j-shreya** [comment]
I can implement this in java. Pls assign this to me

**Comment by TheDangerD0802** [comment]
This Problem is Based on Binary Search . I can implement this problem in C++ with complement Explanation of Approach .

**Comment by mansikagrawal** [comment]
Assign me this issue with java, please

**Comment by jainaman224** [comment]
@TheDangerD0802 I am sorry, it is not a generic problem. So, closing it.

**Comment by TheDangerD0802** [comment]
So my PR is not going to be accepted as the issue has been closed.
