### ISSUE TITLE
Jump Search

### ISSUE THREAD

**Issue by raghav-dalmia** [jainaman224/Algo_Ds_Notes#1676]
Implementation of jump search in any language.

**Comment by insane4u00** [comment]
I would like to implement in c++ and python.

**Comment by DawoodBhai420** [comment]
@raghav-dalmia  refer issue #1641  .
I have created this issue earlier, I don't know why people are creating issues which are already created earlier.
I am ready with the code file just waiting for 1st March.

**Comment by DawoodBhai420** [comment]
@raghav-dalmia  please refer issue #1641 
I have already created the issue earlier.
Please let me work on this issue as I am ready with the code just waiting for 1st march.
