### ISSUE TITLE
Add 1-D Array in Python/C++

### ISSUE THREAD

**Issue by aryasoni98** [jainaman224/Algo_Ds_Notes#1681]
I would like to work on 1-D Array of a number program in Python/C++, as part of GSSoC 20 . So Please assign this to me

**Comment by ritish099** [comment]
As a participant of GSSoC, I would like to work on this. Please assign this task to me. I can implement it in c++, python

**Comment by MastersAbh** [comment]
Can you please elaborate the problem statement ?
