### ISSUE TITLE
Python Implementation of Circular Queue 

### ISSUE THREAD

**Issue by Garimagupta85** [jainaman224/Algo_Ds_Notes#1690]
I would like to contribute this as a part of GSSoC 2020. Please assign me the same.

**Comment by asaw4** [comment]
i would like yo contribute in this . please assign me this

**Comment by Jahnavi-Jonnalagadda** [comment]
Hi There! I would like to work on this issue. Could you please assign this to me.

**Comment by diksha-dutt08** [comment]
I would like to work on this issue. I have good command on python.

**Comment by Garimagupta85** [comment]
@asha15 Thanks! Working on it
