### ISSUE TITLE
JavaScript implementation of Tree Postorder Traversal.

### ISSUE THREAD

**Issue by UddeshJain** [jainaman224/Algo_Ds_Notes#1693]
I would like to implement Postorder Tree Traversal algorithm in JavaScript. I'm a Participant in `GSSOC 2020`. Please assign me this one.

**Comment by UddeshJain** [comment]
@prakharcode ?

**Comment by Rukmini-Meda** [comment]
I would like to work on this issue. Please assign me as part of GSSoC '20
