### ISSUE TITLE
Last Digit of nth Fibonacci number by c++

### ISSUE THREAD

**Issue by RedEye00** [jainaman224/Algo_Ds_Notes#1694]
I will give optimised code for finding last digit of nth fibonacci number

**Comment by asaw4** [comment]
please assign me this problem. i can give a very optimized solution

**Comment by jainaman224** [comment]
@RedEye00 Go ahead.

**Comment by abhijeet010304** [comment]
I would like to work on this issue using C++. Kindly assign this to me.
