### ISSUE TITLE
Finding last digit of nth term in squares of fibonacci number by c++

### ISSUE THREAD

**Issue by RedEye00** [jainaman224/Algo_Ds_Notes#1696]
I will give optimised code for finding last digit square of nth fibonaaci number

**Comment by asaw4** [comment]
i can do this in a very optimized manner. please assign me this

**Comment by abhinashgiri** [comment]
Fibonacci series a unique pattern last digit repeats after every 60th term. I would use this logic to provide efficient code. Please, assign me this.

**Comment by simran2104** [comment]
I would like to resolve this issue for GSSoC'2020

**Comment by nitashadhingra** [comment]
i would like to contribute under GSSoC'20 @singh-shreya6 @MastersAbh @SakshiShreya
