### ISSUE TITLE
binary insertion sort

### ISSUE THREAD

**Issue by mruna7** [jainaman224/Algo_Ds_Notes#1700]
binary insertion sort is missing in java !! i want to work on it under GSSOC'20
please assign it to me  @Asha  @Sakshi Shreya  @Abhinav  @Shlok @Vaibhav  @Raghav Dalmia  @Shreya
@jainaman224 @somya-kapoor mam

**Comment by asaw4** [comment]
i would like to work on this problem under GSSoC'20. please assign me this problem

**Comment by ritish099** [comment]
As a participant of GSSoC, I would like to work on this. Please assign this task to me. I can implement it in java,c,c++,python,.
