### ISSUE TITLE
GCD using Euclidien  algorithm

### ISSUE THREAD

**Issue by mruna7** [jainaman224/Algo_Ds_Notes#1701]
i want to implement it in java . @Asha  @Sakshi Shreya  @Abhinav  @Shlok @Vaibhav  @Raghav Dalmia  @Shreya  .please assign it to me.
@jainaman224 @somya-kapoor

**Comment by asaw4** [comment]
i can implement it in c, c++ and python . please assign me this task.

**Comment by SohelRaja** [comment]
I would like to add GCD using Euclidean algorithm using c, c++, python. Please assign me for this @raghav-dalmia @SakshiShreya

**Comment by ritish099** [comment]
As a participant of GSSoC, I would like to work on this. Please assign this task to me. I can implement it in java,c,c++,python
