### ISSUE TITLE
code to check if a string is palindrome or not in C and C++ .

### ISSUE THREAD

**Issue by MdAkdas** [jainaman224/Algo_Ds_Notes#1706]
I can do this.
Assign me this issue. :)

**Comment by simran2104** [comment]
I would like to resolve this issue for GSSoC'2020

**Comment by ritish099** [comment]
As a participant of GSSoC, I would like to work on this. Please assign this task to me.

**Comment by Anushka-Rajvanshi** [comment]
I would like to work on this issue. Kindly assign me.

**Comment by suchi12j** [comment]
I want to work on it.

**Comment by jainaman224** [comment]
@suchi12j Please pick issue with label `up-for-grabs`

**Comment by meghanagottapu** [comment]
@MdAkdas I want to work on this issue. Can you please assign this issue to me
