### ISSUE TITLE
Add prims algorithm

### ISSUE THREAD

**Issue by utkarshanehe** [jainaman224/Algo_Ds_Notes#1710]
Add prims algorithm for minimal spanning tree using adjacency matrix in C++.

**Comment by Rukmini-Meda** [comment]
Please assign this to me as part of GSSoC '20

**Comment by eKta37** [comment]
As a participant of GSSoC, I would like to work on this in Java, @utkarshanehe please assign this task to me.

**Comment by simran2104** [comment]
I would like to resolve this issue for GSSoC'2020

**Comment by SakshiShreya** [comment]
@utkarshanehe is this not already present?
