### ISSUE TITLE
Pallindromes in Java/Python

### ISSUE THREAD

**Issue by raksha009** [jainaman224/Algo_Ds_Notes#1718]
Hi! I want to contribute by writing code for this program. It will:
1. Check if a number is palindrome or not
2.Check if a name/word is palindrome or not
Plz assign me this as a participant of GSSOC20.
@SakshiShreya @singh-shreya6 @asha15 @raghav-dalmia

**Comment by p-bucky** [comment]
Hey, I want to contribute on this issue by writing program.
It will Include: NAME and NUMBER check

Please assign this to me I've already messaged on slack @SakshiShreya @singh-shreya6 @asha15 @raghav-dalmia

**Comment by Jahnavi-Jonnalagadda** [comment]
Hi There! I would like to contribute on this issue.                                                                                        It will include Name and Number.                                                                                                                Kindly assign this to me @SakshiShreya @singh-shreya6 @asha15 @raghav-dalmia

**Comment by diksha-dutt08** [comment]
I have good command in python. So it would be great if you assign me this issue.

**Comment by hritikpapa** [comment]
I am a competitive coder in Python I have completed my gold badge on HACKER RANK, I would really appreciate if I am assigned to this issue.

**Comment by HardevKhandhar** [comment]
I would like to contribute to this issue for GSSoC' 2020. Kindly assign this issue to me

**Comment by simran2104** [comment]
I would like to resolve this issue for GSSoC'2020

**Comment by ritish099** [comment]
As a participant of GSSoC, I would like to work on this. Please assign this task to me.

**Comment by Anushka-Rajvanshi** [comment]
I would like to work on this issue using java. Kindly assign this issue to me.

**Comment by asha15** [comment]
palindrome for number is already implemented but not for checking issues.
@raksha009  Can i know how many open issues you have ?

**Comment by HariniJeyaraman** [comment]
I am a participant of GSSoC 2020 and would love to contribute to this issue. @asha15 @SakshiShreya @jainaman224 please assign me to this issue. I can implement : 
1. Finding if a given number/string is a palindrome
2. Minimum number of insertions to make a string/number a palindrome
in C/C++, Java and Python languages.

**Comment by raksha009** [comment]
@asha15  i have a single open issue for this project.
Also palindrome implemented is for an array. Also plz give it gssoc label. Thanks

**Comment by raksha009** [comment]
@asha15 I have only a single open issue. Also plz assign it gssoc label. Thanks

**Comment by raksha009** [comment]
@jainaman224 plz assign this issue gssoc20 label.

**Comment by 15aarushiGhadiya** [comment]
I want to work on above mentioned issues 2327, 2402, 2403, 2404. please assign me any 2 of these.

**Comment by 15aarushiGhadiya** [comment]
@raksha009 I want to work on above mentioned issues 2327, 2402, 2403, 2404. please assign me any 2 of these.

**Comment by 15aarushiGhadiya** [comment]
@raksha009 I want to work on above mentioned issues 2327, 2402, 2403, 2404. please assign me any 2 from these.

**Comment by jainaman224** [comment]
@15aarushiGhadiya Please pick different issue.

**Comment by meghanagottapu** [comment]
@raksha009 I want to work on 2491,2492 issues for GSSoC20

**Comment by raksha009** [comment]
@raghav-dalmia i have one un merged PR#2327 related to this issue pending since 17 days. Plz reopen the issue and plz review my PR.
