### ISSUE TITLE
Topological Sort in JS. 

### ISSUE THREAD

**Issue by JanaSabuj** [jainaman224/Algo_Ds_Notes#1732]
I want to implement this algorithm in JS . (GSSoC ' 20)
@raghav-dalmia @SakshiShreya @singh-shreya6 @asha15 @MastersAbh please review it.

**Comment by Angshuman032001** [comment]
I want to work on this issue.
Please assign me this @SakshiShreya @singh-shreya6 @jainaman224 @MastersAbh @somya-kapoor
