### ISSUE TITLE
Tree traversal algorithm

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#174]
Implement
- [ ] Pre-order Traversal
- [ ] Post-order Traversal
- [ ] In-order Traversal
- [ ] Level-order Traversal

**Comment by varunpurohit76** [comment]
can i claim it in java and python ?

**Comment by jainaman224** [comment]
@varunpurohit76 Already implemented in python. Can you please code in java ?

**Comment by varunpurohit76** [comment]
will do in java. thanks

**Comment by vaibhavchellani** [comment]
can i implement it in c++

**Comment by vaibhavchellani** [comment]
I just saw that it is done already

**Comment by PiyushGoyal443** [comment]
can i implement it in c?

**Comment by jainaman224** [comment]
@PiyushGoyal443 Already implemented please work on other issues.

**Comment by jay1499** [comment]
Can I implement the diagonal traversal of a tree? I can do it in cpp

**Comment by jainaman224** [comment]
@jay1499 Go ahead. Please mention me in the PR. I am excited to learn this.

**Comment by isha-gautam** [comment]
Is this issue still open? I'd like to take this issue up in Java

**Comment by jainaman224** [comment]
@isha-gautam Yes it is open. Go ahead.

**Comment by singh-shreya6** [comment]
@jainaman224 I want to take up Spiral order traversal of a Binary tree in C++

**Comment by jainaman224** [comment]
@singh-shreya6 Create a new issue and refer this issue and Go ahead.

**Comment by FinalGetsugaa** [comment]
Is this issue still open to implement it in c++

**Comment by HardevKhandhar** [comment]
Is the issue still open. I would like to take up for GSSoC'2020

**Comment by shreyasrivastava936** [comment]
Hi! I want to work on this issue in java. please assign this task to me for GSSoC'20.
