### ISSUE TITLE
 The Knight’s tour problem by Backtracking

### ISSUE THREAD

**Issue by sonali623** [jainaman224/Algo_Ds_Notes#1757]
A knight's tour is a sequence of moves of a knight on a chessboard such that the knight visits every square exactly once. If the knight ends on a square that is one knight's move from the beginning square (so that it could tour the board again immediately, following the same path), the tour is closed; otherwise, it is open.

The knight's tour problem is the mathematical problem of finding a knight's tour.

**Comment by sonali623** [comment]
I would like to work on it as a part of GSSoc 2020.
@singh-shreya6 @raghav-dalmia  @asha15  please assign this to me.

**Comment by BhanujaAggarwal** [comment]
I would like to work on this issue in C++,C

**Comment by asha15** [comment]
@sonali623 please specify the language the language you want to work with

**Comment by BhanujaAggarwal** [comment]
I would like to work on this issue in C++ @raghav-dalmia  @sonali623

**Comment by sonali623** [comment]
@asha15 @raghav-dalmia  I would like to work on this problem in C, Java and python
