### ISSUE TITLE
Gaussian Elimination Program

### ISSUE THREAD

**Issue by topcoder69** [jainaman224/Algo_Ds_Notes#1758]
Algorithm: Gaussian Elimination Program Algorithm

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

Gaussian Elimination is a method which reduces a system of given linear equations to upper triangular matrix and then uses backward substitution to find the roots. 
I would like to develop an algorithm for it in Cpp and Java.
I'm proficient in Data structures and algorithms. I would love to contribute it as a part of GSSoc '20. Please assign it to me!

**Comment by chandrikadeb7** [comment]
I would like to do the same in C under GSSoC'20
