### ISSUE TITLE
Array Rotation In C

### ISSUE THREAD

**Issue by sandhyabhan** [jainaman224/Algo_Ds_Notes#1766]
I want to work on this issue. Please assign this to me.

**Comment by HariniJeyaraman** [comment]
Interested to work on this issue as a participant of GSSoC 2020. Please assign this to me

**Comment by ritish099** [comment]
I Want to work on this issue please assign it to me

**Comment by BhanujaAggarwal** [comment]
I would like to work on this issue in C

**Comment by somya-kapoor** [comment]
@sandhyabhan You have created two similar PR, please delete one of them.

**Comment by 15aarushiGhadiya** [comment]
@sandhyabhan please assign this issue to me
