### ISSUE TITLE
Add "Bridge and torch problem" Implementation

### ISSUE THREAD

**Issue by HarshCasper** [jainaman224/Algo_Ds_Notes#1768]
Bridge and torch problem is a popular puzzle where four people need to cross a faulty bridge in minimum time with only two people able to cross at a time. They have one torch and every time a pair crosses the bridge, one needs to come back. Given the time taken by the four people to cross the bridge, we have to compute the minimum time taken to cross the bridge. I would like to be assigned this problem @singh-shreya6

**Comment by BhanujaAggarwal** [comment]
I would like to work on this issue in C++,python,java

**Comment by roshankcjha** [comment]
Hello @jainaman224  please assign this issue.I would like to work on finding its solution in different programming languages.

**Comment by jainaman224** [comment]
@roshankcjha Please another issue.
