### ISSUE TITLE
Queue using array

### ISSUE THREAD

**Issue by ayushin78** [jainaman224/Algo_Ds_Notes#177]
Functions to be included :
- Enqueue function
-  Dequeue function
-  Size function 
-  isEmpty function (checks whether queue is empty or not)

**Comment by pranayberry** [comment]
I'm on it.

**Comment by aaronraff** [comment]
Is it acceptable to just translate the C++ code into Java to keep the code consistent over the different languages?

**Comment by jainaman224** [comment]
It will be better if you use java style, java for loop, java collections etc but you can translate that if you want to. Thank you

**Comment by aaronraff** [comment]
Can I work on this in Javascript?

**Comment by instinxt** [comment]
Hey, i would like to contribute here , is this issue still open

**Comment by abhinashgiri** [comment]
I want to contribute to this as part of GSSOC 20. May I, please?
