### ISSUE TITLE
[Matrix_Operations] Add Matrix Addition in C

### ISSUE THREAD

**Issue by HardevKhandhar** [jainaman224/Algo_Ds_Notes#1773]
I would like to contribute to this issue for GSSoC'2020
By contributing a matrix addition program in C

**Comment by ritish099** [comment]
As a participant of GSSoC, I would like to work on this. Please assign this task to me.

**Comment by Anushka-Rajvanshi** [comment]
I would like to work on this issue for GSSoC2020. Kindly this to me. @singh-shreya6  @asha15 @raghav-dalmia

**Comment by BhanujaAggarwal** [comment]
I would like to work on this issue in C++

**Comment by Anushka-Rajvanshi** [comment]
Please review my PR #2000  @jainaman224 @singh-shreya6 @raghav-dalmia @asha15
