### ISSUE TITLE
Dynamic Programming - Adjacent Bit Count Problem [C++]

### ISSUE THREAD

**Issue by apoorvam25** [jainaman224/Algo_Ds_Notes#1779]
Problem Statement: 
For a string of n bits x1,x2,x3,...,Xn the adjacent bit count of the string (AdjBC(x)) is given by: 
X1*X2 + X2*X3 + X3*X4 + ... + Xn-1 * Xn
which counts the number of times a 1 bit is adjacent to another 1 bit. A program that takes as input integers n and k and returns the number of bit strings x of n bits (out of 2ⁿ) that satisfy AdjBC(x) = k.

**Comment by abhishekgupta368** [comment]
Can you please assign this problem to me?

**Comment by BhanujaAggarwal** [comment]
I would like to work on this issue in C++
