### ISSUE TITLE
Queue using Linked List

### ISSUE THREAD

**Issue by ayushin78** [jainaman224/Algo_Ds_Notes#178]
Functions to be included :
- Enqueue function
- Dequeue function
- Size function 
- isEmpty function (checks whether queue is empty or not)

**Comment by pranayberry** [comment]
I'm on it.

**Comment by jainaman224** [comment]
@pranayberry Please specify the language.

**Comment by avijeet95** [comment]
I could do this in C++ and Java, if necessary.

**Comment by jainaman224** [comment]
@avijeet95 please proceed.

**Comment by pranayberry** [comment]
Is the program needed in any other language?

**Comment by jainaman224** [comment]
Yes you can work on other languages.

**Comment by anusreesaji** [comment]
can I work on it using python?

**Comment by jainaman224** [comment]
Unfortunately, It is already implemented.
