### ISSUE TITLE
Matrix chain multiplication in Java

### ISSUE THREAD

**Issue by eKta37** [jainaman224/Algo_Ds_Notes#1784]
@adishjain @nj4710 @ayushin78 
As a GSSoC participant, I would like to work on this, please assign this task to me.

**Comment by AkanshaKamboj** [comment]
@singh-shreya6 I want to contribute it in C and Python. Please assign it to me

**Comment by eKta37** [comment]
@singh-shreya6 thank you for assigning this task to me. I'll start implementing it ASAP.
