### ISSUE TITLE
Implementation of Stack and Queue using Linked List in C language

### ISSUE THREAD

**Issue by SohelRaja** [jainaman224/Algo_Ds_Notes#1788]
I would like to add the implementation of **Stack and Queue** using **Linked List in C** language. Please Assign me for this @raghav-dalmia @asha15 @singh-shreya6. This can labelled as **GSSoC20**

**Comment by ritish099** [comment]
As a participant of GSSoC, I would like to work on this. Please assign this task to me.

**Comment by Anushka-Rajvanshi** [comment]
I want to work on this issue for GSSoC20. Kindly assign it to me. @MastersAbh @raghav-dalmia @asha15 @SakshiShreya @singh-shreya6

**Comment by BhanujaAggarwal** [comment]
I would like to work on this issue in C

**Comment by asha15** [comment]
@SohelRaja  This is already implemented
