### ISSUE TITLE
Shortest remaining time first cpu scheduler

### ISSUE THREAD

**Issue by vishakha2108** [jainaman224/Algo_Ds_Notes#1790]
Being a participant of gssoc 2020  I would like to work on this issue.I would like to implement srtf(preemptive) in java.

-Vishakha Narang

**Comment by BhanujaAggarwal** [comment]
I would like to work on this issue in C++ and python

**Comment by ravireddy07** [comment]
I would like to work on C, C++ and Java. Assign this sto me.

@jainaman224 @somya-kapoor @asha15 @singh-shreya6
