### ISSUE TITLE
Implementation of Magic Square Algorithm

### ISSUE THREAD

**Issue by SohelRaja** [jainaman224/Algo_Ds_Notes#1816]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

I would like to contribute for this in c, c++, python, java. Please assign me for this.

**Comment by ritish099** [comment]
I would like to contribute to this as a part of GSSoC 2k20. I can implement it in c,c++,java,python.

**Comment by BhanujaAggarwal** [comment]
I would like to work on this issue in C++,python,C#
