### ISSUE TITLE
Count Sort in "C"

### ISSUE THREAD

**Issue by Sejal30** [jainaman224/Algo_Ds_Notes#1817]
I would like to work on this issue as a part of GSSoC'20. Please assign me this issue.

**Comment by sheetalssr** [comment]
I am interested in this issue . Kindly assign me .

**Comment by ritish099** [comment]
I would like to contribute to this as a part of GSSoC 2k20. I can implement it in c,c++,java,python.

**Comment by Sejal30** [comment]
As I already started working on this. You can try this in any other language.

**Comment by SakshiShreya** [comment]
@Sejal30 please mention the languages you'll work on.
Others can create a new issue for other languages.

**Comment by singh-shreya6** [comment]
@Sejal30 Count Sort in C already exists
