### ISSUE TITLE
Finding factorial of numbers like 100! (C,C++,JAVA)

### ISSUE THREAD

**Issue by ritish099** [jainaman224/Algo_Ds_Notes#1819]
Factorial of 100 is too large for a variable to store. I can contribute for this problem. please assign the task to me @singh-shreya6

**Comment by goyalmuskan** [comment]
I want to work on this issue in Java. Please assign the same to me.

**Comment by p-bucky** [comment]
I want to work on this  issue in java. Please assign this to me @singh-shreya6

**Comment by internetlake98** [comment]
I want to work on this issue in C , C++. Pls assign this to me @singh-shreya6

**Comment by BhanujaAggarwal** [comment]
I want to work on this issue in C++. Please assign this to me.

**Comment by ritish099** [comment]
i am working on c,c++,java. U guys can try on python etc

**Comment by BhanujaAggarwal** [comment]
I want to work on this issue in Python. Please assign this to me.

**Comment by ritish099** [comment]
@singh-shreya6  mam I have created a pull request please review it.

**Comment by heisastark** [comment]
I can do it in JS @jainaman224
