### ISSUE TITLE
LCM of an given array of element in C,C++,Java

### ISSUE THREAD

**Issue by ritish099** [jainaman224/Algo_Ds_Notes#1821]
please give the issue to me @singh-shreya6 @raghav-dalmia @asha15

**Comment by p-bucky** [comment]
I want to work on java. Pleasse assign this issue to me @singh-shreya6 @raghav-dalmia @asha15

**Comment by Neelaksh-Singh** [comment]
I would like to work on it in python and c

**Comment by BishalKrChanda** [comment]
I want to work on this issue using Python, C, C++ and Java for GSSOC. Please assign me this issue @singh-shreya6 @raghav-dalmia @asha15

**Comment by ritish099** [comment]
@SakshiShreya i created a pull request for it..pls review it

**Comment by saloniankita23** [comment]
I want to work on this issue in C++. Kindly assign this issue to me @singh-shreya6 @raghav-dalmia @asha15

**Comment by jainaman224** [comment]
@saloniankita23 Please take another issue.

**Comment by Riyagoel2** [comment]
I would like to work on it in java.
Please assign it to. @asha15  @jainaman224

**Comment by shwetagurnani** [comment]
I would like to work on this issue in C, c++.Please assign it to me

**Comment by ananyakamboj** [comment]
I would like to work on this issue in C. Please assign

**Comment by Tawishi** [comment]
I would like to contribute the code in C++.
