### ISSUE TITLE
Implementing 1_D_Array in Ruby

### ISSUE THREAD

**Issue by nikipr1999** [jainaman224/Algo_Ds_Notes#1826]
Add basic functions of 1 dimensional array in Ruby
1. Finding frequency of an element in the array.
2. Finding the maximum and the second maximum number in the array.
3. Find the mean, variance and standard deviation of the elements of array.
4. Merge two sorted arrays.

**Comment by nikipr1999** [comment]
I would like to work on this for gssoc20 . Please assign this issue to me.

**Comment by nikipr1999** [comment]
I had made a pull request #1546 . Please check and merge it if no issues are there. Looking for your guidance.

**Comment by Vaibhavraj10** [comment]
@nikipr1999 Make sure you make a pull request for the referenced issue only once you have been assigned.
