### ISSUE TITLE
bitwise addition of two numbers in C and C++.(GSSoC'20)

### ISSUE THREAD

**Issue by DawoodBhai420** [jainaman224/Algo_Ds_Notes#1838]

**Comment by DawoodBhai420** [comment]
I want to work on this issue as a part of GSSoC'20.
@MastersAbh  @asha15  @raghav-dalmia 
can someone please assign me to this issue??

**Comment by Angshuman032001** [comment]
I can work on this issue on Java.
Please assign me this @SakshiShreya @asha15 @raghav-dalmia @MastersAbh @singh-shreya6

**Comment by Neelaksh-Singh** [comment]
I can work on this issue in C  for GSSoC 2020,please assign it to me @SakshiShreya @asha15 @raghav-dalmia @MastersAbh @singh-shreya6.

**Comment by mugdhajoshi** [comment]
I want to work on this issue in Python under GSSoC 2020. Please assign it to me for Python

**Comment by singh-shreya6** [comment]
@DawoodBhai420 Go ahead.

**Comment by singh-shreya6** [comment]
@Neelaksh-Singh Since this issue was raised by @DawoodBhai420, he has the right to work on it. Please don't code a problem till the problem has been assigned to you.
