### ISSUE TITLE
Detection of cycle in linked list

### ISSUE THREAD

**Issue by abhishekgupta368** [jainaman224/Algo_Ds_Notes#1840]
this program is missing and i would like to contribute in it.

**Comment by HariniJeyaraman** [comment]
I am a participant of GSSoC 2020 and want to contribute to this issue. @jainaman224 @Ash-D23 @asha15 @SakshiShreya please assign me this issue.
I can implement this program in C, C++, Java and Python.

**Comment by abhishekgupta368** [comment]
Harini, you can create your own issue then ask them

**Comment by abhishekgupta368** [comment]
can proceed ahead? I have completed my last issue.
