### ISSUE TITLE
Merge Sort in Java

### ISSUE THREAD

**Issue by p-bucky** [jainaman224/Algo_Ds_Notes#1862]
![Merge-Sort-Tutorial](https://user-images.githubusercontent.com/59308744/75643172-27a79300-5c64-11ea-9f5e-b914adf832fe.png)

**Comment by p-bucky** [comment]
Please assign this issue to me @SakshiShreya

**Comment by jainaman224** [comment]
I think it is already implemented. Do check.

**Comment by p-bucky** [comment]
> I think it is already implemented. Do check.

yeah.. Sorry I missed, From now onward I will take care
