### ISSUE TITLE
Implement Leap Year code in JavaScript

### ISSUE THREAD

**Issue by Angshuman032001** [jainaman224/Algo_Ds_Notes#1867]
Please assign me this issue @SakshiShreya @singh-shreya6 @jainaman224 @asha15 @somya-kapoor  @Vaibhavraj10 @raghav-dalmia

**Comment by shreyakapoor08** [comment]
Can I take up this issue ?

**Comment by Angshuman032001** [comment]
> Please assign me this issue @SakshiShreya @singh-shreya6 @jainaman224 @asha15 @somya-kapoor @Vaibhavraj10 @raghav-dalmia
