### ISSUE TITLE
Add code for Harmonic Progression in JavaScript

### ISSUE THREAD

**Issue by Angshuman032001** [jainaman224/Algo_Ds_Notes#1868]
Please assign me this issue @singh-shreya6 @asha15 @jainaman224 @SakshiShreya @somya-kapoor @Vaibhavraj10 @raghav-dalmia

**Comment by HariniJeyaraman** [comment]
Please assign me this issue @singh-shreya6 @asha15 @jainaman224  @SakshiShreya .
Would love to work on this and contribute
