### ISSUE TITLE
calculate the absolute difference between the sums of diagonals of a matrix in C++,Java

### ISSUE THREAD

**Issue by Angshuman032001** [jainaman224/Algo_Ds_Notes#1870]
Please assign me this issue for GSSoC  @SakshiShreya @singh-shreya6 @asha15 @raghav-dalmia @somya-kapoor @Vaibhavraj10

**Comment by Nikhil-Patro** [comment]
Please assign this issue to me @Angshuman032001 
I can implement a linear time complexity algorithm for this problem with constant amount of auxiliary space.
