### ISSUE TITLE
Add code for Round Robin CPU Scheduling

### ISSUE THREAD

**Issue by Xxoliaxx** [jainaman224/Algo_Ds_Notes#1873]
I would like to add the implementation of this in cpp. Please assign this.
@raghav-dalmia  @MastersAbh  @asha15  @singh-shreya6  @SakshiShreya @somya-kapoor

**Comment by hritik5102** [comment]
Please refer PR number #1639. This algorithm has been added.

**Comment by Vaibhavraj10** [comment]
@Xxoliaxx go ahead.

**Comment by Vaibhavraj10** [comment]
@hritik5102 Donot make a PR before you claim that issue.

**Comment by Xxoliaxx** [comment]
Please review the PR #1928 for this issue. @Vaibhavraj10

**Comment by hritik5102** [comment]
@Vaibhavraj10  @jainaman224  I'm really sorry for that, should I implement **Round Robin CPU scheduling** in C
