### ISSUE TITLE
Printing  a spiral matrix using C and C++.

### ISSUE THREAD

**Issue by harshlohia11** [jainaman224/Algo_Ds_Notes#1879]
It will take a input and it will print a square array accordingly.
I am working on this program.
![spiral](https://user-images.githubusercontent.com/59775144/75656259-99460800-5c89-11ea-8eaf-5d898e3e6c35.JPG)

I am attaching an sample output of the program.

**Comment by somya-kapoor** [comment]
It is already present in C but you can work it on C++.
@harshlohia11 Go ahead in C++.

**Comment by harshlohia11** [comment]
Yes but my program is a tad different from what is already present . I am
attaching a copy of what my output will look like.Please tell me if I can
do go ahead with this in C and C++.

**Comment by Akansha2202** [comment]
Can you please assign me this

**Comment by suchi12j** [comment]
I would like to take this issue

**Comment by bohemian98** [comment]
I can do this in both C and C++. Please assign this to me.

**Comment by pragyajaiswa05l** [comment]
would like to do it in c++ please assign it to me @jainaman224 @somya-kapoor @raghav-dalmia

**Comment by Ani1000** [comment]
would like to do it in python please assign it to me @jainaman224 @somya-kapoor @raghav-dalmia

**Comment by Ani1000** [comment]
Mam please assign me any work I already commented  on some the repo..
