### ISSUE TITLE
Dijkstra Algorithm in Python

### ISSUE THREAD

**Issue by ka1shi** [jainaman224/Algo_Ds_Notes#1883]
I want to add the code of Dijkstra Algorithm in Python. Please Assign it to me. @raghav-dalmia @MastersAbh @asha15 @singh-shreya6 @SakshiShreya

**Comment by Vaibhavraj10** [comment]
@ka1shi Dijkstra Algorithm implementation in Python is already there in our Repo. Please create another issue. I am closing this for now.
