### ISSUE TITLE
Implementing Collections in Java

### ISSUE THREAD

**Issue by simrankoul** [jainaman224/Algo_Ds_Notes#1889]
I would like to implement collections (List, Stack, Queue and all the implementations of these interfaces) in Java. Please assign me this issue.

**Comment by Vaibhavraj10** [comment]
@simrankoul Go ahead.

**Comment by simrankoul** [comment]
@Vaibhavraj10 Do I need to take dynamic values from the user in this case?

**Comment by 15aarushiGhadiya** [comment]
@Vaibhavraj10 @jainaman224 I want to impement hashmap and hashset for this issue, please assign this to me.

**Comment by 15aarushiGhadiya** [comment]
@Vaibhavraj10 @jainaman224 I want to implement hashmap and hashset for this issue, please assign this to me.

**Comment by 15aarushiGhadiya** [comment]
@Vaibhavraj10 @jainaman224 I want to implement hashmap and hashset for this issue, please assign this to me.

**Comment by simrankoul** [comment]
@15aarushiGhadiya  Hi Aarushi! I have already been assigned this issue, and am currently working on it.

**Comment by jainaman224** [comment]
@15aarushiGhadiya  Please pick an issue with label `up-for-grabs`
