### ISSUE TITLE
Binary Tree Pair Sum

### ISSUE THREAD

**Issue by mehmehul** [jainaman224/Algo_Ds_Notes#1905]
Finding pairs whose sum is equal to a certain given number in Binary Tree. Implementation for this code in the missing in the project repository. I would like to work on its implementation in C++ in this issue.

**Comment by chaithanyarlk** [comment]
i want to work on this

**Comment by chaithanyarlk** [comment]
i would like to work on this of finding pairs whose sum is equal to given number in a binary tree by using c language also i can implement using java. please assign this to me

**Comment by jainaman224** [comment]
@chaithanyarlk Please pickup another issue.
