### ISSUE TITLE
Optimize Linear Search in C

### ISSUE THREAD

**Issue by Aju100** [jainaman224/Algo_Ds_Notes#1911]

**Comment by shwhite17** [comment]
i wanna do this, can i?

**Comment by Shadman-Ahmed-Chowdhury** [comment]
I can to contribute in this issue. How can I be assigned to this issue?

**Comment by Aju100** [comment]
@jainaman224 can you please assigned to this issue please ?

**Comment by raghav-dalmia** [comment]
It's already implemented there.
