### ISSUE TITLE
challenges on competitive coding website(GSSoC'20)

### ISSUE THREAD

**Issue by DawoodBhai420** [jainaman224/Algo_Ds_Notes#1912]
I am thinking to add solutions to challenges on competitive coding websites such as Hackerank, Codechef, etc.
if it is okay to be added in repository, Mentors please let me know if I should start working on it.
and assign it to me.

**Comment by DawoodBhai420** [comment]
@jainaman224 @asha15 @singh-shreya6 @MastersAbh @raghav-dalmia 
should we add this in repo??
if yes, please assign this issue to me.

**Comment by jainaman224** [comment]
Not for now.
