### ISSUE TITLE
linear search in c

### ISSUE THREAD

**Issue by shwhite17** [jainaman224/Algo_Ds_Notes#1913]
#include <stdio.h>
int main()
{
  int array[100], search, c, n;
  printf("Enter number of elements in array\n");
  scanf("%d", &n);
  printf("Enter %d integer(s)\n", n);
  for (c = 0; c < n; c++)
    scanf("%d", &array[c]);
  printf("Enter a number to search\n");
  scanf("%d", &search); 
  for (c = 0; c < n; c++)
  {
    if (array[c] == search)    /* If required element is found */
    {
      printf("%d is present at location %d.\n", search, c+1);
      break;
    }
  }
  if (c == n)
    printf("%d isn't present in the array.\n", search);
  return 0;
}

**Comment by shwhite17** [comment]
is it correct?

**Comment by DawoodBhai420** [comment]
implementation is already there in repo.

**Comment by singh-shreya6** [comment]
@shwhite17 The implementation already exists in repo. Please select some other issue. Also you don't need to write the complete program in comment.
