### ISSUE TITLE
Pascal_Triangle - Java

### ISSUE THREAD

**Issue by JasleenRandhawa** [jainaman224/Algo_Ds_Notes#1925]
I would like to implement this problem in java.
Please assign this issue to me.
[Pascal_Triangle](Algo_Ds_Notes/Pascal_Triangle/)

**Comment by shreyakapoor08** [comment]
Hey! can I implement pascal triangle problem ?

**Comment by srimani-programmer** [comment]
I want to work on this issue. Please assign it to me @singh-shreya6 @raghav-dalmia @asha15

**Comment by somya-kapoor** [comment]
@JasleenRandhawa Before creating an issue, please see that someone else hasn't created the same issue before you. This issue has already been created #1818 .
