### ISSUE TITLE
To add hamiltonian cycle using backtracking code in c++

### ISSUE THREAD

**Issue by atrip10** [jainaman224/Algo_Ds_Notes#1934]

**Comment by goyalmuskan** [comment]
I want to work on this issue in Java, Please assign me. @jainaman224

**Comment by goyalmuskan** [comment]
Please assign me this issue. I want to work on it in Java. @singh-shreya6

**Comment by jainaman224** [comment]
@goyalmuskan Create a new issue and make sure it is not implemented yet.

**Comment by goyalmuskan** [comment]
@jainaman224 created issue #2096

**Comment by jainaman224** [comment]
@atrip10 We already have a issue for this. So, I have to close it.
