### ISSUE TITLE
 find next number divisible by any given number.

### ISSUE THREAD

**Issue by Anushka-Rajvanshi** [jainaman224/Algo_Ds_Notes#1935]
I want to add implementation of this program in c,c++and java. For eg.- to find next digit divisible by 7 after 187. Please assign me this issue. @singh-shreya6  @raghav-dalmia  @asha15 @MastersAb

**Comment by nikkkhil067** [comment]
I can easily implement this in C, C++, Python, Matlab.
Please assign this to me.

**Comment by Neelaksh-Singh** [comment]
i would also like to take it up
