### ISSUE TITLE
 priority scheduling (preemptive)  in scheduling algorithms C/C++.

### ISSUE THREAD

**Issue by MdAkdas** [jainaman224/Algo_Ds_Notes#1947]
I would like to work to on these algorithms in C/C++.
please assign me this issue. :)

**Comment by MdAkdas** [comment]
@SakshiShreya @asha15 @jainaman224

**Comment by Xxoliaxx** [comment]
Hello! Round Robin scheduling issue was already raised by me and I have been assigned to work on it.
So only ask for the other two please 😊

**Comment by MdAkdas** [comment]
Ohh. I've not noticed.🙄
 I can do the rest. 🙂

**Comment by pratu098** [comment]
I would like to work on this issue as a part of gssoc'20
