### ISSUE TITLE
struct node  discussion

### ISSUE THREAD

**Issue by jinz2014** [jainaman224/Algo_Ds_Notes#195]
How about the following c++ way to create define a Node class ?

class Node {
   public:
      int data;
      Node *left;
      Node *right;
      Node(int value) : data(value), left(NULL), right(NULL) {}
}

node *root = new Node(1);

**Comment by jainaman224** [comment]
There are many ways to do so. It looks better way though. Can you please provide link to show which program you are referring to.

**Comment by tusharsabhani** [comment]
I would like to do this task(in C++).
Also one query I have to give the full working program right or just the struct node definition?

**Comment by jainaman224** [comment]
Hey @tusharsabhani, Actually the question here is to use struct or class in c++. Like in linked list or tree programs. I am still not sure, whether to go for struct or class.

What are your thoughts. and to clarify this task needs to fix existing programs.
