### ISSUE TITLE
Armstrong Number using C#

### ISSUE THREAD

**Issue by BishalKrChanda** [jainaman224/Algo_Ds_Notes#1954]
I would like implement the program to check if a number is an Armstrong number or not using C# as a part of GSSoC ' 20. Please assign this to me.
@SakshiShreya @asha15 @jainaman224 @MastersAbh @Vaibhavraj10

**Comment by Neelaksh-Singh** [comment]
i would also like to work on this issue as a  part  of gssoc 20.
