### ISSUE TITLE
GCD in JS

### ISSUE THREAD

**Issue by heisastark** [jainaman224/Algo_Ds_Notes#1967]
Hey! There's no implementation of GCD on C++, can i go ahead with this?
https://github.com/jainaman224/Algo_Ds_Notes/tree/master/Gcd

**Comment by pratu098** [comment]
I would like to take this issue as a part of gssoc'20.

**Comment by Angshuman032001** [comment]
> Hey! There's no implementation of GCD on C++, can i go ahead with this?
> https://github.com/jainaman224/Algo_Ds_Notes/tree/master/Gcd

there is already a section on euclidean algorithm

**Comment by heisastark** [comment]
There's no JS implementation though.
I can work on that.
