### ISSUE TITLE
Power of 2 problem implementation in JS

### ISSUE THREAD

**Issue by heisastark** [jainaman224/Algo_Ds_Notes#1968]
There's no js implementation of this problem.
https://github.com/jainaman224/Algo_Ds_Notes/tree/master/Power_Of_Two
Please assign it to me?

**Comment by coderprasukj** [comment]
@jainaman224 I would like to work on this issue for GSSoC20. Please assign me with this issue.

**Comment by heisastark** [comment]
File for #1968 is ready, will send a PR as soon as PR #2219 gets approved.
