### ISSUE TITLE
Kruskal Algorithm in C

### ISSUE THREAD

**Issue by coderprasukj** [jainaman224/Algo_Ds_Notes#1991]
@jainaman224 I would like to work for kruskal algorithm in C. Please assign this issue to me for GSSoC.

**Comment by jainaman224** [comment]
I think it is present in repo or issue. So, do check.

**Comment by coderprasukj** [comment]
@jainaman224  Sir this issue is having a tag of 'easy' while other kruskal algo issues are labeled as 'medium'. Please see to it.

**Comment by urbashi123** [comment]
Can you assign me this issue #2255 ?

**Comment by AkanshaKamboj** [comment]
if this issue is open then please assign it to me @jainaman224
