### ISSUE TITLE
Implementation of 0/1 knapsack problem in C++

### ISSUE THREAD

**Issue by shweta0699** [jainaman224/Algo_Ds_Notes#1992]
I want to work on this as a part of GSSoC'20. Please assign it to me if it is not implemented yet.

**Comment by jainaman224** [comment]
I think it should be present. So do check.

**Comment by VIJAY07102** [comment]
Is anyone working on it? If not, can I start doing this?

**Comment by jainaman224** [comment]
@VIJAY07102 Please issue with label `up-for-grabs`

**Comment by VIJAY07102** [comment]
> @VIJAY07102 Please issue with label `up-for-grabs`

@jainaman224 Can you help me, how to label it with `up-for-grabs`

**Comment by jainaman224** [comment]
@VIJAY07102 Please pick issue which has this label already. Don't label this issue.

**Comment by VIJAY07102** [comment]
Can I solve the same problem  in another language(C or Python)?

**Comment by santushtisharma10** [comment]
I would like to contribute in C,please assign me this

**Comment by suchi12j** [comment]
I can do this.

**Comment by ishikabansal04** [comment]
i would like to do this issue in c++/java.

**Comment by meghanagottapu** [comment]
@shweta0699 @jainaman224 can you please verify my pull request

**Comment by HariniJeyaraman** [comment]
@jainaman224 I can implement in C,C++ and Python. Please assign me this issue
