### ISSUE TITLE
Python Implementation of Rabin Karp Algorithm

### ISSUE THREAD

**Issue by codermuskanj** [jainaman224/Algo_Ds_Notes#2019]
@jainaman224 
There is no Python implementation for the Rabin Karp algorithm. I would like to work on this issue for GSSoC. Please assign me with this issue.

**Comment by Neelaksh-Singh** [comment]
i would also to help @jainaman224  in its implementation

**Comment by Amitsharma45** [comment]
i would like to contribute i am from gssoc 2020

**Comment by Amitsharma45** [comment]
@codermuskanj i solve this problem

**Comment by codermuskanj** [comment]
@jainaman224 @somya-kapoor @raghav-dalmia This issue is assigned to me and i am working on it and have made a pull request  then why  @Amitsharma45 is working on it and his request has been reviewed?
