### ISSUE TITLE
Implementation of RSA algorithm using Chinese remainder theorem in C++ 

### ISSUE THREAD

**Issue by codermuskanj** [jainaman224/Algo_Ds_Notes#2021]
@jainaman224 @somya-kapoor @SakshiShreya @singh-shreya6 @asha15 @MastersAbh @raghav-dalmia  I would like to work on this task. Please assign me with this issue for GSSoC.

**Comment by Neelaksh-Singh** [comment]
i am more than wiiling to help with the same
