### ISSUE TITLE
Implement Count_Inversion in java

### ISSUE THREAD

**Issue by NikitaMasand** [jainaman224/Algo_Ds_Notes#2023]

**Comment by vinod2305** [comment]
I would like to work on this issue. Thank you.

**Comment by NikitaMasand** [comment]
Sorry but I had asked for this and It's already assigned. I am working on it.

**Comment by somya-kapoor** [comment]
@NikitaMasand Before creating an issue, please see that someone else hasn't created the same issue before you. This issue has already been created #1664.

**Comment by NikitaMasand** [comment]
@somya-kapoor, I am extremely sorry for this. I will make sure this won't happen again.
