### ISSUE TITLE
Substitution Cipher in java

### ISSUE THREAD

**Issue by hritik5102** [jainaman224/Algo_Ds_Notes#2050]
@raghav-dalmia @MastersAbh @asha15 @singh-shreya6 @SakshiShreya There is no Java implementation for the **Substitution Cipher (Affine cipher and Vigenere cipher )**. I would like to work on this issue. Please assign me with this issue.

**Comment by ravireddy07** [comment]
I would like to continue this issue with remaining cipher algorithms like vernam cipher, hill cipher, play fair, auto key cipher, monoceaser cipher and transposition ciphers in c++ and Java.
