### ISSUE TITLE
Insertion to & Deletion from a Singly Linked List Implementation in C, Java & Python

### ISSUE THREAD

**Issue by disha2sinha** [jainaman224/Algo_Ds_Notes#2063]
I want to contribute Insertion & Deletion codes of a linked list in three different Languages.Can i get assigned to this?

**Comment by BhavishayGulati** [comment]
Hey,I am Gssoc20 participant and  I would like to contribute in this issue

**Comment by Amitsharma45** [comment]
hey,i like  contribute in this issue

**Comment by jainaman224** [comment]
It is already implemented
