### ISSUE TITLE
C++ Program to check whether a singly linked List is a palindrome or not

### ISSUE THREAD

**Issue by disha2sinha** [jainaman224/Algo_Ds_Notes#2067]
Can I get assigned to writing the code of the problem mentioned in the title of this issue?

**Comment by BhavishayGulati** [comment]
hey I am a gssoc20 participant And i would like to solve this issue and i have successfully solved my first issue

**Comment by pooja-git11** [comment]
i am interested to write code for this problem ,assign this to me

**Comment by jainaman224** [comment]
@pooja-git11 Please pick issue with label `up-for-grabs`.
