### ISSUE TITLE
Tarjan's algorithm for finding Strongly Connected Components - C++

### ISSUE THREAD

**Issue by TVSSSRIPAD** [jainaman224/Algo_Ds_Notes#2073]
Hi, I would like to implement Tarjan's algorithm in C++ for finding Strongly Connected Components present in a graph.

**Comment by sngmanish** [comment]
@jainaman224 If no one is working on this issue could you please assign it to me..?

**Comment by TVSSSRIPAD** [comment]
I am working on this. Sorry for delay.
