### ISSUE TITLE
AKS primality test

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#2111]
- [x] C
- [x] C++
- [x] C# - @Yashank18
- [ ] CoffeeScript
- [ ] Dart - @Rukmini-Meda
- [ ] Go
- [x] Java
- [x] JS
- [ ] Kotlin
- [ ] Php
- [x] Python
- [x] Readme - @goyalmuskan
- [ ] Ruby
- [ ] Rust
- [ ] TypeScript - @Kuljeet-123

**Comment by Yashank18** [comment]
I want to work on this issue

**Comment by goyalmuskan** [comment]
I want to add the Readme for this issue @jainaman224

**Comment by nitin1kumar1** [comment]
I want to add the Cpp code for this.

**Comment by Kuljeet-123** [comment]
@jainaman224  I want to implement this in typescript.Please assign me this.

**Comment by Rukmini-Meda** [comment]
I would like to work on this issue in Dart. Please assign this to me as part of GSSOC'20.
