### ISSUE TITLE
AVL tree

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#2112]
- [x] C
- [x] C++ - @Manish-cloud
- [ ] C# - @KanakalathaVemuru
- [ ] CoffeeScript
- [x] Dart - @Rukmini-Meda
- [ ] Go
- [x] Java
- [ ] JS - @satvikchachra
- [ ] Kotlin
- [ ] Php - @chandrikadeb7
- [x] Python
- [x] Readme
- [ ] Ruby
- [ ] Rust
- [ ] TypeScript

**Comment by goyalmuskan** [comment]
I want to work on this issue in C#

**Comment by nitin1kumar1** [comment]
I can work o it in C. Assign.

**Comment by MdAkdas** [comment]
i can do this in C++. assign me this. :)

**Comment by chandrikadeb7** [comment]
I want to contribute in Ruby under GSSoC'20

**Comment by yuktirapartiwar** [comment]
I want to work on this issue in c++. Please assign me this issue.

**Comment by aryangulati** [comment]
Please allow me to add in C++

**Comment by abhijeet010304** [comment]
I would like to work on this issue using C++. Kindly assign this to me.

**Comment by BhanujaAggarwal** [comment]
@jainaman224 @raghav-dalmia Please assign this to me this to me for C#

**Comment by prashansag62** [comment]
Please assign this issue to me for C#

**Comment by Kuljeet-123** [comment]
@jainaman224 I want to work on this issue in PHP.Please assign me this issue.

**Comment by Ratna04priya** [comment]
I woud like to work in Go lang. @jainaman224 , can u assign this to me?

**Comment by Kuljeet-123** [comment]
@jainaman224  I have created the PR #2470 .Please review it and merge it.

**Comment by sandhyabhan** [comment]
i want to work on this using kotlin. plz assign this to me.

**Comment by jainaman224** [comment]
@sandhyabhan You already have 2 open issues
https://github.com/jainaman224/Algo_Ds_Notes/issues/assigned/sandhyabhan

Correct me if there is any mistake.

**Comment by sandhyabhan** [comment]
Yes...I am done with array rotation. I think there is some issue from your side..
pls check this link
https://github.com/jainaman224/Algo_Ds_Notes/pull/2320

**Comment by sandhyabhan** [comment]
please assign this to me in kotlin.

**Comment by Rukmini-Meda** [comment]
@jainaman224 I would like to work on this in Dart. Please assign this to me as part of GSSoC'20.

**Comment by chandrikadeb7** [comment]
@jainaman224 I want to work on PHP.
