### ISSUE TITLE
Binary Insertion Sort

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#2125]
- [x] C
- [x] C++
- [x] C# - @Yashank18
- [ ] CoffeeScript
- [ ] Dart - @raksha009
- [ ] Go - @KamalDGRT
- [ ] Java - @raktim00
- [ ] JS - @sheetalssr
- [ ] Kotlin
- [ ] Php - @goyalmuskan
- [x] Python
- [ ] Readme - @goyalmuskan
- [ ] Ruby
- [ ] Rust
- [ ] TypeScript

**Comment by goyalmuskan** [comment]
I want to work on this in Java. Please assign me this issue.

**Comment by jainaman224** [comment]
@goyalmuskan You already have 2 open issues.

**Comment by goyalmuskan** [comment]
Sir, I have already created PR for those. @jainaman224

**Comment by jainaman224** [comment]
Sorry but you have to wait for the review.

**Comment by raktim00** [comment]
I want to work on this issue on Java. Please assign me this. @jainaman224 @somya-kapoor

**Comment by Neelaksh-Singh** [comment]
would like to do it in php

**Comment by sheetalssr** [comment]
I can do this in js.kindly assign me .

**Comment by VIJAY07102** [comment]
Can I provide readme document for this issue?

**Comment by shortCircuit81** [comment]
please assign this to me in java or c++

**Comment by sheetalssr** [comment]
kindly review the PR.it has been 2 days.

**Comment by Jahnavi-Jonnalagadda** [comment]
@jainaman224 I would like to work on this issue in Dart. Could you please assign this to me.

**Comment by jainaman224** [comment]
@VIJAY07102 @Jahnavi-Jonnalagadda Are you working on it?

**Comment by rbjoshi1309** [comment]
@jainaman224 I would like to work on this issue in Php.

**Comment by Jahnavi-Jonnalagadda** [comment]
@jainaman224 I raised a PR already.

**Comment by jainaman224** [comment]
@Jahnavi-Jonnalagadda Please link this issue with PR.

**Comment by Jahnavi-Jonnalagadda** [comment]
@jainaman224 It shows that it is already linked with the issue.

**Comment by VIJAY07102** [comment]
@jainaman224 binary insertion sort has already been implemented in python, and also it has been merged, please verify it.

**Comment by VIJAY07102** [comment]
@jainaman224 For readme document, I already made a PR, but by mistake I had unassigned myself,  I didn't know that I unassigned myself. Please check the PR #2645

**Comment by goyalmuskan** [comment]
@jainaman224 May I add the readme for this? Or code in PHP?

**Comment by jainaman224** [comment]
@goyalmuskan Open different PR for both in order to get marks for both of them

**Comment by KamalDGRT** [comment]
@jainaman224 I would like to work on this issue in Go Language.

**Comment by raksha009** [comment]
Plz assign me binary insertion sort in dart @jainaman224
