### ISSUE TITLE
Length of a Linked List

### ISSUE THREAD

**Issue by ayushin78** [jainaman224/Algo_Ds_Notes#213]
Include the following two functions for determining the length of a linked list in these codes (https://github.com/jainaman224/Algo_Ds_Notes/tree/master/Linked_List)
- lengthIterative - This function should be implemented iteratively.
- lengthRecursive - This function should be implemented recursively.

Note : please specify the language in which you are interested before proceeding.

**Comment by vjon** [comment]
I'm interested in implementing this in C++, if it hasn't been already.

**Comment by itsdegan** [comment]
I could give it a try in Java

**Comment by jeremychen0127** [comment]
I have created a PR for Python in #218

**Comment by itsdegan** [comment]
I created a PR for Java #220

**Comment by sahilrider** [comment]
I am going to do it in C.

**Comment by sahilrider** [comment]
But there is no linked list in C. Should I make one?

**Comment by jainaman224** [comment]
@sahilrider please proceed

**Comment by LauraLaureus** [comment]
@jainaman224 does it already implemented in c++?

**Comment by jainaman224** [comment]
@LauraLaureus yes, please check out other issues or create new one.

**Comment by akhil117** [comment]
I like to work on this. Could I work on this by using java?

**Comment by jainaman224** [comment]
Go on

**Comment by Rita-Okonkwo** [comment]
Hi is it still possible to work on this using Java?

**Comment by jainaman224** [comment]
It is already implemented in Java.

**Comment by anusreesaji** [comment]
can I work on it in python?

**Comment by jainaman224** [comment]
@anusreesaji It is already implemented in python.

**Comment by Kevingeorge101** [comment]
Can I implement this in C?

**Comment by FinalGetsugaa** [comment]
can it be implemented in c++

**Comment by ravireddy07** [comment]
Hello @ayushin78  @jainaman224 , I would like work on this in C and Java. Please assign this to me.

**Comment by ravireddy07** [comment]
I made the PR. Completed the task in Java and C. #2004 
@jainaman224

**Comment by abhijeet010304** [comment]
I would like work on this in C++ and python.

**Comment by suchi12j** [comment]
Can I work on this?

**Comment by 15aarushiGhadiya** [comment]
Hi can I work on intersection point of 2 linkedlist in java @jainaman224
