### ISSUE TITLE
Quick Sort

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#2131]
- [x] C
- [x] C++
- [x] C# - @Yashank18
- [ ] CoffeeScript - @prashansag62
- [x] Dart
- [x] Go
- [x] Java
- [x] JS
- [x] Kotlin - @97shivank
- [x] Php - @goyalmuskan
- [x] Python
- [x] Readme
- [x] Ruby
- [ ] Rust - @m-code12
- [ ] TypeScript - @dj373

**Comment by atrip10** [comment]
I want to work on this issue in C++

**Comment by prashansag62** [comment]
I want to work on this in kotlin and coffeescript.Please assign this issue to me

**Comment by yuktta** [comment]
Please @jainaman224 assign this to me in Kotlin.

**Comment by Ratna04priya** [comment]
I would like to do it in Rust.

**Comment by Ratna04priya** [comment]
@jainaman224 , I think adding Quicksort in Assembly Language is also an great idea. I would like to work on it.

**Comment by jainaman224** [comment]
@prashansag62 Are you working on it?

**Comment by 97shivank** [comment]
@jainaman224 can i take this issue for kotlin?

**Comment by kmrakash** [comment]
let me work on using TypeScript . @jainaman224

**Comment by dj373** [comment]
Please let me implement in TypeScript @jainaman224

**Comment by m-code12** [comment]
I can do it in Rust.Assign it to me @jainaman224 .I can open a pr quickly.
