### ISSUE TITLE
Cocktail Sort

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#2144]
- [x] C
- [x] C++
- [ ] C# 
- [ ] CoffeeScript
- [ ] Dart - @Rukmini-Meda
- [ ] Go 
- [x] Java
- [x] JS
- [ ] Kotlin
- [ ] Php
- [x] Python
- [x] Readme
- [x] Ruby- @HardevKhandhar 
- [ ] Rust
- [ ] TypeScript

**Comment by urbashi123** [comment]
Hi! I would like to work on this issue. Please can you assign me?
@jainaman224

**Comment by jainaman224** [comment]
@urbashi123 Please specify the language that is not ticked or assigned yet.

**Comment by urbashi123** [comment]
I will do this using C#

**Comment by aakashdinkar** [comment]
I would like to work on this issue in go

**Comment by syedareehaquasar** [comment]
please assign me in c#

**Comment by rbjoshi1309** [comment]
@jainaman224 I would like to work on this issue in C#.

**Comment by Rukmini-Meda** [comment]
I would like to work on this issue in Dart. Please assign this to me as part of GSSOC'20.

**Comment by HardevKhandhar** [comment]
I would like to contribute to this issue in RUBY for GSSoC 2020
Please assign this issue to me in Ruby language.
