### ISSUE TITLE
Pancake Sort

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#2151]
- [x] C
- [x] C++
- [x] C# - @himanshusharma89
- [ ] CoffeeScript
- [ ] Dart - @Rukmini-Meda
- [x] Go - @KamalDGRT
- [ ] Java - @parjanyaacoder
- [x] JS - @sejalshri
- [ ] Kotlin - @sandhyabhan
- [ ] Php - @sakshikhachane
- [x] Python
- [ ] Readme - @Tawishi
- [x] Ruby
- [ ] Rust
- [ ] TypeScript

**Comment by yuktirapartiwar** [comment]
I want to work on this issue in java. Please assign me this issue.

**Comment by jainaman224** [comment]
It is already assigned for java.

**Comment by heisastark** [comment]
Please assign this to me for JS solution.

**Comment by p-soham11** [comment]
I want to do it in Python, Please assign me for that.

**Comment by malavikasmenon** [comment]
I would like to work on JS please.

**Comment by himanshusharma89** [comment]
Hey @jainaman224 , I would like to work on this issue in C#

**Comment by p-soham11** [comment]
Hello @jainaman224 can you review my pull request ?

**Comment by himanshusharma89** [comment]
@jainaman224 Can you check my PR #2309 and #2311

**Comment by malavikasmenon** [comment]
Could you check my PR #2310 ?

**Comment by syedareehaquasar** [comment]
please assign me in php

**Comment by rbjoshi1309** [comment]
@jainaman224 I would like to work on this issue in Php.

**Comment by Tawishi** [comment]
I would like to do the Readme for the issue @jainaman224.

**Comment by Tawishi** [comment]
@jainaman224 I have added the readme file. Please review and suggest changes, if needed.

**Comment by sakshikhachane** [comment]
I would like to work on this issue on php. Please assign me this.

**Comment by sandhyabhan** [comment]
I want to work on this in kotlin.pls assign

**Comment by KamalDGRT** [comment]
I would like to work on this in Go Language. Please assign me this issue @jainaman224 @asha15

**Comment by sejalshri** [comment]
For implementation in JS , kindly assign it to me. @jainaman224

**Comment by Rukmini-Meda** [comment]
I would like to work on this issue in Dart. Please assign this to me as part of GSSOC'20.
