### ISSUE TITLE
RSA algorithm

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#2162]
- [x] C
- [x] C++
- [ ] C#
- [ ] CoffeeScript
- [ ] Dart
- [ ] Go - @KamalDGRT
- [x] Java
- [ ] JS - @MOHITSAHAL
- [ ] Kotlin - @RaghavAwasthi
- [ ] Php
- [x] Python
- [ ] Readme - @mharshita
- [ ] Ruby
- [ ] Rust
- [ ] TypeScript

**Comment by arghac14** [comment]
Would like to work on this, can I get assigned to this issue?

**Comment by nitin1kumar1** [comment]
I can do readme for this.

**Comment by heisastark** [comment]
Can do this in JS. Please assign it to me.

**Comment by jainaman224** [comment]
@heisastark @arghac14 There is 2 open issue policy.

**Comment by heisastark** [comment]
@jainaman224 waiting for the last two to be merged sir

**Comment by heisastark** [comment]
@jainaman224 waiting for the last two to be merged

**Comment by MOHITSAHAL** [comment]
Sir i want to do this in JS. Please assign it to me.

**Comment by jainaman224** [comment]
@nitin1kumar1 @MOHITSAHAL Are you working on it?

**Comment by nitin1kumar1** [comment]
@jainaman224  you can check it and inform if anything's wrong. I will change it. I have PR for both my issues.

**Comment by RaghavAwasthi** [comment]
I would like to work on this in Kotlin

**Comment by KamalDGRT** [comment]
@jainaman224 Please assign me this issue for Go Language. I even completed the coding part.

**Comment by mharshita** [comment]
Please assign me the readme for this.
@jainaman224  @somya-kapoor

**Comment by Rukmini-Meda** [comment]
I would like to work on this issue in Dart. Please assign this to me as part of GSSOC'20.
