### ISSUE TITLE
Ternary Search

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#2176]
- [x] C
- [x] C++
- [x] C# - @p-soham11
- [x] CoffeeScript
- [ ] Dart - @heisastark
- [ ] Go - @Ratna04priya
- [x] Java
- [x] JS
- [ ] Kotlin - @saloniankita23
- [x] Php - @BhardwajShweta25
- [x] Python
- [x] Readme - @shwetagurnani
- [ ] Ruby - @atarax665
- [ ] Rust
- [ ] TypeScript

**Comment by HardevKhandhar** [comment]
I would like to do this issue in C#
Please assign me this issue for GSSoC 2020

**Comment by MOHITSAHAL** [comment]
Sir i would like to do this issue in python.Please assign this to me.

**Comment by jainaman224** [comment]
@MOHITSAHAL It is already implemented in Python.

**Comment by Ratna04priya** [comment]
I would like to implement that in GO lang.

**Comment by shwetagurnani** [comment]
I would like to work on readme .Please assign it to me.

**Comment by eKta37** [comment]
As a participant of GSSoC, I want to create a readme file for this issue. Please assign me this task.

**Comment by p-soham11** [comment]
Please assign me for C#

**Comment by BhardwajShweta25** [comment]
I would like to contribute in PHP.

**Comment by Ratna04priya** [comment]
Hello, I would like to contribute in PHP as well. I would like to add and modify the readme too.

**Comment by HariniJeyaraman** [comment]
@jainaman224 @SakshiShreya I can implement this is Kotlin and Ruby .
I can implement this in TypeScript also. Please assign me to this issue.

**Comment by saloniankita23** [comment]
Kindly assign this issue to me in Kotlin @jainaman224 @SakshiShreya .

**Comment by heisastark** [comment]
I can do this in Dart. Please assign it to me. @jainaman224

**Comment by jainaman224** [comment]
@saloniankita23 Are you working on it?

**Comment by saloniankita23** [comment]
@jainaman224 Yes, I am.

**Comment by atarax665** [comment]
I can do this in ruby. @jainaman224
