### ISSUE TITLE
Exponential Search

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#2177]
- [x] C
- [x] C++
- [x] C#
- [ ] CoffeeScript
- [ ] Dart - @disha2sinha
- [ ] Go
- [x] Java
- [x] JS
- [ ] Kotlin
- [x] Php - @thakran14
- [x] Python
- [ ] Readme - @AJAYSHARMA2012
- [ ] Ruby
- [ ] Rust
- [ ] TypeScript

**Comment by p-bucky** [comment]
Sir Assign this to me I will do in java

**Comment by nitashadhingra** [comment]
i would like to contribute in c++ under GSSOC @jainaman224 @asha15

**Comment by Aju100** [comment]
i would like to contribute in go lang. please assigned to me.

**Comment by MOHITSAHAL** [comment]
Sir i would like to contribute in python and JS. Please assign this to me.

**Comment by AJAYSHARMA2012** [comment]
Please assign this to me @jainaman224 . I can update the README

**Comment by HariniJeyaraman** [comment]
@jainaman224 I can implement this in Go and Kotlin and Ruby, Please assign me this issue. I do not have 2 open issues

**Comment by Ratna04priya** [comment]
I would like to do it in GO and PHP.

**Comment by rbjoshi1309** [comment]
@jainaman224 I would like to work on this issue in Php.

**Comment by saloniankita23** [comment]
@jainaman224 Kindly assign me this issue in Php.

**Comment by thakran14** [comment]
I wish to work on it in php kindly assign it to me

**Comment by AJAYSHARMA2012** [comment]
I have added all the requested changes. Please review my PR #2448 , it has been a month since then @asha15 @jainaman224.

**Comment by disha2sinha** [comment]
I would like to implement this in dart. Please assign me.

**Comment by AJAYSHARMA2012** [comment]
Please review my PR as well #2448 @jainaman224 @asha15
