### ISSUE TITLE
recursive approach for bitwise addition in C and C++

### ISSUE THREAD

**Issue by DawoodBhai420** [jainaman224/Algo_Ds_Notes#2186]
I am creating this issue as said by @raghav-dalmia ,
please assign this issue to me.

**Comment by DawoodBhai420** [comment]
@jainaman224  I had added both recursive and iterative approaches in single PR previously but the mentor @raghav-dalmia  suggested me to create separate issues for two approaches.
now, what am I supposed to do?
Please suggest.

**Comment by jainaman224** [comment]
Submit PR for iterative method only.
