### ISSUE TITLE
Introsort

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#2249]
- [ ] C - @Nik-09
- [ ] C++ - @Moddy2024
- [ ] C#
- [ ] CoffeeScript
- [ ] Dart - @vanya-24
- [ ] Go
- [ ] Java - @aaliyah03
- [ ] JS - @bohemian98
- [ ] Kotlin
- [ ] Php
- [x] Python 
- [ ] Readme - @raksha009
- [ ] Ruby
- [ ] Rust
- [ ] TypeScript

**Comment by Nik-09** [comment]
Willing to participate in gssoc 2020 by  contributing in this issue.

**Comment by chaithanyarlk** [comment]
i am willing to contribute to this in c++,c

**Comment by jainaman224** [comment]
@chaithanyarlk You can take only 2 issues at a time.

**Comment by chaithanyarlk** [comment]
I have solved one issue P S review it and I want to work on this in JAVA,PYTHON,C++,C
@jainaman224 please assign me

**Comment by IPSITA2000** [comment]
@jainaman224  I want to implement this program in JAVA , Python. Please assign this to me!

**Comment by nehasangeetajha** [comment]
@jainaman224 i want to implement in python. Please assign this to me

**Comment by malavikasmenon** [comment]
I want to work on it in C++

**Comment by AJAYSHARMA2012** [comment]
Please assign this to me @jainaman224 . I can update the README

**Comment by prat31** [comment]
I want to contribute to this in GO. Please assign it to me @jainaman224.

**Comment by SomyaGandhi** [comment]
I can work on this in javascript. Please assign this to me @jainaman224 .

**Comment by shwetagurnani** [comment]
I can work on readme.Please assign it to me

**Comment by HariniJeyaraman** [comment]
@jainaman224 I can update the Readme for this and implement in Kotlin, Java and Ruby. Please assign me this issue.

**Comment by urbashi123** [comment]
I want to work on readme. Can you assign me ?
@jainaman224

**Comment by Kuljeet-123** [comment]
@jainaman224  I want to work on this issue in PHP and Javascript

**Comment by suchi12j** [comment]
Pls assign me readme @jainaman224

**Comment by p-soham11** [comment]
@jainaman224 Can you please assign me for C# ?

**Comment by jainaman224** [comment]
@Nik-09 @chaithanyarlk @prat31 Are you working on it?

**Comment by prat31** [comment]
Please assign to someone else for GO.

**Comment by chaithanyarlk** [comment]
I will submit my work by tommorow @jainaman224

**Comment by Nik-09** [comment]
Currently I am learning that topic, i will try to complete this within
April.

**Comment by shreyakapoor08** [comment]
can I do this in c#

**Comment by adi44** [comment]
I would like to work in python and c

**Comment by bohemian98** [comment]
@somya-kapoor  @jainaman224 I would like to do this in JS. please assign this to me.

**Comment by 264pranjal** [comment]
I want to work on the readme. @jainaman224 sir please assign it to me.

**Comment by aaliyah03** [comment]
Since @chaithanyarlk has removed the assignment, can I take it up and implement it in Java? And if not, I'd like to work on it in Kotlin

**Comment by JyotiJauhari** [comment]
@somya-kapoor  ma'am 
Willing to participate in gssoc 2020 by contributing in this issue.
through
Python language.
Please assign me this issue.

**Comment by JyotiJauhari** [comment]
@jainaman224 please assign me this issue I will work on it in python, if not available in python then #c or php.

**Comment by JyotiJauhari** [comment]
@somya-kapoor I had read the reason why previous pull request for intro.py is closed. 
I will work on it and don't repeat the mistake which was done by nehasangeetajha. Please assign this issue to me. I will do it in python.

**Comment by shubha028** [comment]
@jainaman224 pls assign this issue to me .I can do it in java and  python.

**Comment by vanya-24** [comment]
Please assign me this issue. I can do it in python and dart. @jainaman224

**Comment by raksha009** [comment]
@jainaman224 plz assign me readme of introsort

**Comment by Moddy2024** [comment]
i am from gssoc 2020 and will like to work on this on C++

**Comment by Moddy2024** [comment]
PLEASE REVIEW MINE PR ON TIME FOR THIS #3036 SO I CAN GET THE POINTS ON GSSOC'20
