### ISSUE TITLE
Tug of War Algorithm in Python - Backtracking

### ISSUE THREAD

**Issue by Harikrishnan6336** [jainaman224/Algo_Ds_Notes#2258]
PROBLEM : Given a set of n numbers , divide the set in two subsets of n/2 sizes each such that the difference of the sum of two subsets is as minimum as possible

A solution to the above problem is the TUG OF WAR algorithm based on Backtracking . The solution tries every possible subset of half size. We initialize current set as empty and then build it considering that there are two possibilities for each element, either be a part of current set, or be a part of the other subset. We consider both possibilities for every element and when a subset of half size is obtained we check whether this solutions is better than the best solution so far and update as needed

**Comment by Harikrishnan6336** [comment]
@jainaman224    I would like to work on this algorithm

**Comment by jainaman224** [comment]
We are not accepting issues created by GSSoC participants. Please pick another issue.
