### ISSUE TITLE
Simpson1/3 rule in PHP, Java, Python

### ISSUE THREAD

**Issue by manildayma** [jainaman224/Algo_Ds_Notes#2288]

**Comment by IPSITA2000** [comment]
I would like to implement this program in Java. Please assign this to me!

**Comment by IPSITA2000** [comment]
Can I get assigned for implementing its algorithm in JAVA?

**Comment by Swa4nali** [comment]
Please assign this issue to me

**Comment by Swa4nali** [comment]
Thanks for assigning this to me.

**Comment by Swa4nali** [comment]
[Simpson.txt](https://github.com/jainaman224/Algo_Ds_Notes/files/4302979/Simpson.txt)

**Comment by Swa4nali** [comment]
[Simpson.txt](https://github.com/jainaman224/Algo_Ds_Notes/files/4302980/Simpson.txt)
Code in java

**Comment by Swa4nali** [comment]
Is it okay if I post my code in text format here??  I don't know how to upload my code or where to upload my code. So, I am uploading my code in this format.

**Comment by Swa4nali** [comment]
I am not able to upload my java code here.. How can I upload a java, PHP or any other source code here?

**Comment by jainaman224** [comment]
@Swa4nali Please ask on slack channel named `git_github`, if you are GSSoC aspirant.
