### ISSUE TITLE
Queue implementation using Array in Java

### ISSUE THREAD

**Issue by eKta37** [jainaman224/Algo_Ds_Notes#2299]
As a participant of GSSoC, I want to work on this. Please assign this task to me.

**Comment by Amitsharma45** [comment]
i want to work on this issue and i am from Gssoc2020

**Comment by Amitsharma45** [comment]
https://github.com/jainaman224/Algo_Ds_Notes/pull/2302
please check it and accept pull request

**Comment by Amitsharma45** [comment]
https://github.com/jainaman224/Algo_Ds_Notes/pull/2302
please check it and accept pull reqest.

**Comment by Amitsharma45** [comment]
please pull request and accept it.
