### ISSUE TITLE
Bitmasking functions 

### ISSUE THREAD

**Issue by Akansha2202** [jainaman224/Algo_Ds_Notes#2319]
1)get bit at some position
2)set the bit at some position
3)clear and update bits
4)replace a sequence of the bit at some positions with other bit

**Comment by abhishekgupta368** [comment]
Can you please assign me, please?
I am waiting for some issue for a long time.
thank you

**Comment by Ratna04priya** [comment]
I would like to work on the issue, in Python, Go, Js, Java and PHP

**Comment by abhishekgupta368** [comment]
I can do it in all language which is allowed in this repository.
