### ISSUE TITLE
Wave Print 2D Array

### ISSUE THREAD

**Issue by shruthi019** [jainaman224/Algo_Ds_Notes#2371]
This will print all the elements of the 2D array traversing it like a wave - top to bottom in the first column, then bottom to top in the second column and so on. I would like to work on this implementation in C++ as part of GSSoC. Please assign this issue to me.

**Comment by Adyasha8105** [comment]
please assign this task to me.
@shruthi019

**Comment by BhanujaAggarwal** [comment]
@jainaman224 @raghav-dalmia @somya-kapoor Please assign this to me

**Comment by AdityaGupta150** [comment]
@jainaman224 I will solve it, please assign it to me :-)

**Comment by Riyagoel2** [comment]
I would like to work on it in Java @jainaman224
