### ISSUE TITLE
Maximum and minimum elements by divide and conquer 

### ISSUE THREAD

**Issue by prince-09** [jainaman224/Algo_Ds_Notes#2440]
I want to implement finding maximum and minimum element of an array by divide and conquer.

**Comment by JyotiJauhari** [comment]
@Vaibhavraj10  @MastersAbh @raghav-dalmia 
Hello Sir!!
I want to implement finding maximum and minimum element of an array by divide and conquer using C programming language.

**Comment by hitha2000** [comment]
@prince-09  please assign me this issue
