### ISSUE TITLE
Implementation of Klee’s Algorithm

### ISSUE THREAD

**Issue by abhishekgupta368** [jainaman224/Algo_Ds_Notes#2450]
This algorithm is used to create a union of overlapping coordinates and find the longest Line.
This one is missing.
Can you please assign me this. @jainaman224 
Thank you

**Comment by hitha2000** [comment]
@abhishekgupta368  please assign me this issue

**Comment by abhishekgupta368** [comment]
I am not a mentor

**Comment by hitha2000** [comment]
Oh sorry

**Comment by hitha2000** [comment]
@jainaman224  please assign this issue to me
