### ISSUE TITLE
Rotate_linked_list_by_k_nodes

### ISSUE THREAD

**Issue by poorva2145** [jainaman224/Algo_Ds_Notes#2452]
This algorithm is not included in Algo_Ds_Notes repository.
This algorithm rotates linked list by k nodes counterclockwise. This algorithm also works when k is greater than length of linked list.

**Comment by poorva2145** [comment]
Please assign this issue to me

**Comment by poorva2145** [comment]
I had created pull request for the same but it got rejected as I was not assigned.

**Comment by mahakmandlecha** [comment]
please assign me this isssue

**Comment by Kuljeet-123** [comment]
I Would love to do this in python....please assign this to me
