### ISSUE TITLE
Program to Create magic square in C,C++,JAVA.

### ISSUE THREAD

**Issue by ritish099** [jainaman224/Algo_Ds_Notes#2454]
@asha15 @SakshiShreya assign this issue to me kindly

**Comment by LovepreetSingh12** [comment]
I would like to work on this in Java as a part of GSSoC 2020.

**Comment by mahakmandlecha** [comment]
please assign me this issue in Java language

**Comment by Kuljeet-123** [comment]
@asha15 I'm a GSSOC'20 participant...  I would love to do this in c++.
