### ISSUE TITLE
Remove Duplicate Characters

### ISSUE THREAD

**Issue by aftex261** [jainaman224/Algo_Ds_Notes#2508]
Please assign me this issue

**Comment by aftex261** [comment]
This algo is about to remove duplicate characters from an array in C language

**Comment by bohemian98** [comment]
I can do this in cpp. Please assign this to me.

**Comment by aftex261** [comment]
I have already created the algo and working on it from earlier.Please assign it to me.

**Comment by MananKaur** [comment]
I would like to work on this one for java. Kindly assign this issue to me!
