### ISSUE TITLE
I would like to implement LCM operation in C++ and python

### ISSUE THREAD

**Issue by ShebinJoseph** [jainaman224/Algo_Ds_Notes#2510]

**Comment by ShebinJoseph** [comment]
Can I start working on this ?

**Comment by shortCircuit81** [comment]
please assign this to me

**Comment by ShebinJoseph** [comment]
@shortCircuit81 Sorry,I already started working on this.I am waiting for the mentors to get a response.You go for some other issues.

**Comment by LovepreetSingh12** [comment]
Can I work on this in Java?
