### ISSUE TITLE
Shift zeroes to end of array in O(n)

### ISSUE THREAD

**Issue by manali-biswas** [jainaman224/Algo_Ds_Notes#2512]
I would like to implement shifting zeroes to end of array in time complexity O(N) and space complexity O(1) in c++. Please assign me this issue.

**Comment by suchi12j** [comment]
I want to work on this

**Comment by manali-biswas** [comment]
@jainaman224 please assign me this issue for c and c++

**Comment by MananKaur** [comment]
I would like to implement this for java, kindly assign this issue to me!

**Comment by bohemian98** [comment]
I can work on this problem in python. Please assign this to me.
