### ISSUE TITLE
Recursion in C and C++

### ISSUE THREAD

**Issue by shubhigupta991** [jainaman224/Algo_Ds_Notes#2520]
1. Factorial of a number.
2. HCF of two numbers.
3. Fibonacci series
4. Count the number of digits.
5. Sum of all digits of a number.
6. Palindrome.
7. Length of string.

**Comment by syedareehaquasar** [comment]
assign me this issue

**Comment by Adyasha8105** [comment]
please assign this issue to me as I m a beginner

**Comment by shortCircuit81** [comment]
please assign this to me ..

**Comment by LovepreetSingh12** [comment]
I would like to work on this as a part of GSSoC 2020.

**Comment by bohemian98** [comment]
Please assign this to me. I can work on both C and C++ and can make the readme file too.
