### ISSUE TITLE
Recursion in C and C++ 

### ISSUE THREAD

**Issue by shubhigupta991** [jainaman224/Algo_Ds_Notes#2566]
1. Factorial of a number.
2. HCF of two numbers.
3. Fibonacci series
4. Count the number of digits.
5. Sum of all digits of a number.
6. Palindrome.
7. Length of string.

**Comment by nehasangeetajha** [comment]
@jainaman224 can u assign me Factorial of a number in CPP ?

**Comment by bohemian98** [comment]
I can work on all of the problems in CLP and C. I am GSSoC participant, please assign this issue to me.

**Comment by bohemian98** [comment]
@jainaman224 I can work on this issue in CPP and C both. Please asign me this issue
