### ISSUE TITLE
Graph Algorithms 

### ISSUE THREAD

**Issue by anjalisoni3655** [jainaman224/Algo_Ds_Notes#2655]
I want to add the Krushkals , Prims and dijkstra algorithms in C++. With proper comments .
Please assign this to me

**Comment by anjalisoni3655** [comment]
Should I give a pull request directly or wait for the mentors to approve ?

**Comment by arp99** [comment]
which graph algorithms should be implemented? or can I give any number of algorithms and give a pull request

**Comment by anjalisoni3655** [comment]
@jainaman224 can you please assign this to me   , so that i can proceed further
