### ISSUE TITLE
Linked_List_Reversal

### ISSUE THREAD

**Issue by rhythm10** [jainaman224/Algo_Ds_Notes#2662]
Sir, I would like to make a program for Reverse Single Linked List it in C, C++, and JAVA.

**Comment by pratu098** [comment]
I would like to prog.ram for reverse linked list in Python and java as a part og Gssoc

**Comment by scortier** [comment]
Hello Sir, I would like to build a program for Linked_List_Reversal in CPP and Python.

**Comment by iamankitkumar08062001** [comment]
Hello Sir, I would like to build a program for Linked List Reversal in C language.
