### ISSUE TITLE
Mean_Median_Mode

### ISSUE THREAD

**Issue by rhythm10** [jainaman224/Algo_Ds_Notes#2667]
Sir, I would like to implement Mean, Median and Mode of unsorted Array in Language C, C++ and JAVA.
Please assign me this task.

**Comment by RiaJha02** [comment]
Hello, I would like to try this and can implement the solution in C/C++/JAVA/JS/Python.
Thank you!

**Comment by RaghavAwasthi** [comment]
I would like to work on this in Kotlin

**Comment by raghav-dalmia** [comment]
@rhythm10 - c,c++,java
@RiaJha02  - js,python
@RaghavAwasthi - kotlin

**Comment by jainaman224** [comment]
Sorry but creation of issue is not allowed.
