### ISSUE TITLE
Maximum Product subarray 

### ISSUE THREAD

**Issue by anjalisoni3655** [jainaman224/Algo_Ds_Notes#2668]
I want to add the code for maximum product subarray in C , C++ , java , python . PLease assign me this issue 
@jainaman224

**Comment by anjalisoni3655** [comment]
THis will be extension to the maximum sum subarray that we do using Kadene's algorithm

**Comment by payal-98** [comment]
In this ,we have to write code for max. product sub array in all these languages?
