### ISSUE TITLE
No implemenation of Binary Search in C

### ISSUE THREAD

**Issue by saksham0037** [jainaman224/Algo_Ds_Notes#268]

**Comment by jainaman224** [comment]
Do you want to work, then please proceed.

**Comment by sahilkhurana19** [comment]
I am willing to take a go at it

**Comment by saksham0037** [comment]
I am up

**Comment by jainaman224** [comment]
@sahilkhurana19 Please work on other issues.

**Comment by ashivliving** [comment]
I have added bubble_sort.c

**Comment by faraaz98** [comment]
I have a PULL REQUEST for [binary_Search.c](https://github.com/jainaman224/Algo_Ds_Notes/pull/303)

**Comment by faraaz98** [comment]
I have added [binary_search.c](https://github.com/jainaman224/Algo_Ds_Notes/pull/303)

**Comment by sourabhjagtap95** [comment]
Made a pull request #307
