### ISSUE TITLE
Target Sum

### ISSUE THREAD

**Issue by shivanidalmia1203** [jainaman224/Algo_Ds_Notes#2692]
Problem Statement 
Given an array and a target Sum . Assign positive and negative i,e. '+' or '-' to each element of an array such that after assigning the total sum of the array equals the target Sum. Return count of such possible assignment combinations.

I/P    :- An array and a target sum.
O/P  :- Count of possible assignments.
Language Used :- C++

**Comment by shivanidalmia1203** [comment]
Please assign me this issue.

**Comment by raghav-dalmia** [comment]
Go ahead.

**Comment by jainaman224** [comment]
Sorry
But creation of issue is not allowed.

**Comment by shivanidalmia1203** [comment]
Please assign me issue 1770
