### ISSUE TITLE
Finding nth fibonacci number using Binet's formula

### ISSUE THREAD

**Issue by Manish-cloud** [jainaman224/Algo_Ds_Notes#2694]
Binet's formula : It is efficient method for finding nth fibonacci number 
Time Complexity : O(1)                                         //  Constant Time complexity

So, I would like to provide it's implementation in following languages
1 ] C
2 ] C++
3 ] Python
4 ] Java

**Comment by nancysingh24** [comment]
> Binet's formula : It is efficient method for finding nth fibonacci number
> Time Complexity : O(1) // Constant Time complexity
> 
> So, I would like to provide it's implementation in following languages
> 1 ] C
> 2 ] C++
> 3 ] Python
> 4 ] Java

I would like to work on this using C++.
