### ISSUE TITLE
huffman tree code in c

### ISSUE THREAD

**Issue by GarimaMahajan20** [jainaman224/Algo_Ds_Notes#2727]
i want to provide huffman tree  construction code in c language given the frequencies

**Comment by Amitsharma45** [comment]
i want to work on this issues and i am from girlscript summer of code 2020 please reply

**Comment by nikkkhil067** [comment]
I want to write code for this in C, C++, Python and Java.
Please assign this to me.

**Comment by YaminiShrestha31** [comment]
I want to take this issue please assign this to me

**Comment by m-code12** [comment]
I am interested for this issue. Please assign it to me.
