### ISSUE TITLE
Palindromic_String in Java and Python

### ISSUE THREAD

**Issue by Mustafiz04** [jainaman224/Algo_Ds_Notes#2736]
I would like to work on Palindromic String implementation in Java and Python as the GSSoC'20 participant.
Please @jainaman224 assign to me

**Comment by Amitsharma45** [comment]
@jainaman224  i want work on issue in C and python and i am from girl script summer of code 2020,please assigm this issue to me

**Comment by Shr03mink** [comment]
i would like to work on this in java and C++. Could you please assign this issue to me @jainaman224
