### ISSUE TITLE
Queue using Stack

### ISSUE THREAD

**Issue by rhythm10** [jainaman224/Algo_Ds_Notes#2762]
Sir, Can I start implementing my code in JAVA for Queue using Stack.

**Comment by spacemonkey1101** [comment]
I can write it in C ,C++, python and java

**Comment by pratyushraj7** [comment]
I can do this in C++ and Python.

**Comment by thakran14** [comment]
i can do this in c++ and java pls assign

**Comment by anurajbhandari5** [comment]
I can do in java

**Comment by shwhite17** [comment]
can you please assign this issue to me @rhythm10 I will give my level best
