### ISSUE TITLE
Implementation of Kadane’s Algorithm to find the Largest Sum Contiguous Subarray

### ISSUE THREAD

**Issue by anshukcse** [jainaman224/Algo_Ds_Notes#2771]
**@jainaman224 @somya-kapoor @SakshiShreya @singh-shreya6 @asha15 @MastersAbh @raghav-dalmia** I would like to work on this task. Please assign me with this issue for GSSoC.

**Comment by nikkkhil067** [comment]
Please assign this to me. I would like to work on it.

**Comment by pragyajaiswa05l** [comment]
@jainaman224  @raghav-dalmia  @asha15 @somya-kapoor  please assign me this issue .would like to do it in c++ as a part of GSSoC 2020.
