### ISSUE TITLE
Minimum spanning tree problem

### ISSUE THREAD

**Issue by arpit1997** [jainaman224/Algo_Ds_Notes#278]
Given an undirected and connected graph G = (V, E)
G=(V,E), a spanning tree of the graph G is a tree that spans G, it includes every vertex of 
and is a subgraph of every edge in the tree belongs to G The cost of the spanning tree is the sum of the weights of all the edges in the tree. There can be many spanning trees. Minimum spanning tree is the spanning tree where the cost is minimum among all the spanning trees. There also can be many minimum spanning trees.

**Comment by jainaman224** [comment]
I think issue for this already exist. Hence closing this issue for now.
