### ISSUE TITLE
Principal Component Analysis

### ISSUE THREAD

**Issue by AparnaJuhi** [jainaman224/Algo_Ds_Notes#2784]
Dimensionality Reduction Technique-
The sheer size of data in the modern age is not only a challenge for computer hardware but also a main bottleneck for the performance of many machine learning algorithms. The main goal of a PCA analysis is to identify patterns in data; PCA aims to detect the correlation between variables. If a strong correlation between variables exists, the attempt to reduce the dimensionality only makes sense. In a nutshell, this is what PCA is all about: Finding the directions of maximum variance in high-dimensional data and project it onto a smaller dimensional subspace while retaining most of the information.

**Comment by AparnaJuhi** [comment]
Please assign this issue to me @jainaman224

**Comment by AparnaJuhi** [comment]
Please assign this issue to me @jainaman224  @asha15

**Comment by BALaka-18** [comment]
I would like to work on this issue too.  @jainaman224
