### ISSUE TITLE
Balanced tree problem Red Black Tree

### ISSUE THREAD

**Issue by arpit1997** [jainaman224/Algo_Ds_Notes#280]
**How to balance a given tree**
A red-black tree is a binary search tree with one extra bit of storage per node: its
color, which can be either RED or BLACK. By constraining the node colors on any
simple path from the root to a leaf, red-black trees ensure that no such path is more
than twice as long as any other, so that the tree is approximately balanced.

**Comment by AyushRai09** [comment]
I would like to work on the problem of creating a red black tree in c. Can you assign this work to me?

**Comment by arpit1997** [comment]
@AyushRai09 Well Thank you for you for your interest and go for it if you can do it. There is no need to assign the issue #280  You may refer these links to boost your work
[eeks for geeks](www.geeksforgeeks.org/red-black-tree-set-1-introduction-2/)
[wikipedia](https://en.wikipedia.org/wiki/Red–black_tree)
Hope this helps
:smile_cat: :smiley_cat:

**Comment by jainaman224** [comment]
Thank you @arpit1997 .

**Comment by anusreesaji** [comment]
can I work on it in python

**Comment by jainaman224** [comment]
@anusreesaji Go ahead.

**Comment by prasty** [comment]
Can I work on it sir.

**Comment by jainaman224** [comment]
Yes @prasty go ahead. But make sure either it is not implemented or not claimed for any language by anyone.

**Comment by shreyasrivastava936** [comment]
Hi! I want to work on this issue in java. please assign this task to me for GSSoC'20.
