### ISSUE TITLE
Algorithm for generating magic square

### ISSUE THREAD

**Issue by anirudh-kac** [jainaman224/Algo_Ds_Notes#2837]
An algorithm to generate magic square (a n x n matrix) for any given value of n

**Comment by 264pranjal** [comment]
@anirudh-kac @jainaman224  can I work on this issue in python language. Will it be considered a valid contribution under Gssoc20

**Comment by anirudh-kac** [comment]
@264pranjal , I myself raised this issue so that it would be assigned to me and I can work on it. This is how we're supposed to contribute under GSSOC. But since I was planning to implement it in C++ , you can also work on implementing the same in python if @jainaman224  assigns us both . Let's see if that can work

**Comment by anirudh-kac** [comment]
Why is this issue closed ? @jainaman224
