### ISSUE TITLE
Travelling Salesman Problem

### ISSUE THREAD

**Issue by coderprasukj** [jainaman224/Algo_Ds_Notes#2849]
@jainaman224 @asha15 @somya-kapoor I would like to work on this issue problem in C, Javascript and PHP. Kindly have a look at it and assign me with this issue.

**Comment by JyotiJauhari** [comment]
@jainaman224 @asha15 @somya-kapoor Please Assign me this issue. I can write algorithm for it and  code in C++.

**Comment by JyotiJauhari** [comment]
@jainaman224 @asha15 @somya-kapoor
Please assign me this issue . I had studied this algorithm which is use to find the shortest path to cover all the nodes of a graph.
I can write brief intro about the Algo  and can  implement it in C++.
