### ISSUE TITLE
Bubble_Sort.cpp not working due to small error

### ISSUE THREAD

**Issue by samyak06** [jainaman224/Algo_Ds_Notes#2851]

**Comment by samyak06** [comment]
Please assign me to remove the error. I have already pulled down the request for the same.
Thank You

**Comment by nikkkhil067** [comment]
Please assign this to me. I can resolve the error in the code.

**Comment by akshaysingh5** [comment]
I want to work on this issue.

**Comment by Tanmayi03** [comment]
Please assign me this issue
