### ISSUE TITLE
GCD problem in C

### ISSUE THREAD

**Issue by anshuman1510** [jainaman224/Algo_Ds_Notes#2868]
I want to add GCD algorithm using recursion in C language.

**Comment by anshuman1510** [comment]
Please assign me this if not implemented yet.

**Comment by vanya-24** [comment]
Please assign me this issue!

**Comment by vanya-24** [comment]
Please assign me this issue! I can do it using euler's theorem and in many more ways!

**Comment by shubha028** [comment]
@jainaman224 pls assign this issue to me .I can do it different ways and recursion too in c .
