### ISSUE TITLE
Huffman coding problem

### ISSUE THREAD

**Issue by arpit1997** [jainaman224/Algo_Ds_Notes#290]
Huffman coding is a lossless data compression algorithm. The idea is to assign variable-legth codes to input characters, lengths of the assigned codes are based on the frequencies of corresponding characters. The most frequent character gets the smallest code and the least frequent character gets the largest code

It is somehow a bit complex to understand as it requires many other concepts to implement it. 
:smile: :smile: :smile:

**Comment by prabhjyot28** [comment]
Hello @jainaman224 , I would like to build this algorithm in Python.

**Comment by jainaman224** [comment]
Go ahead.

**Comment by sez98** [comment]
i have added a pull request for the .java for this algorithm

**Comment by jainaman224** [comment]
@sez98 Go ahead. From next time wait for the issue to be assigned before working on it.

**Comment by sez98** [comment]
@jainaman224 sure i ll keep that in mind.

**Comment by shreyasrivastava936** [comment]
Hi! I want to work on this issue. please assign this task to me for GSSoC'20.
