### ISSUE TITLE
Euclidean Algorithm

### ISSUE THREAD

**Issue by jainaman224** [jainaman224/Algo_Ds_Notes#2905]
- [x] C - @simrann20
- [x] C++
- [x] C#
- [x] CoffeeScript
- [x] Clojure
- [ ] Dart - @disha2sinha
- [ ] Go
- [x] Java
- [x] JS - @Satyam3976
- [x] Kotlin
- [x] Php
- [x] Python
- [x] Readme
- [x] Ruby - @Tahanima
- [ ] Rust - @mightomi
- [x] Scala 
- [ ] TypeScript - @shivamgupta57121

**Comment by simrann20** [comment]
@jainaman224  @somya-kapoor  can you assign me this in C ?

**Comment by shwetagurnani** [comment]
Please assign it t me in C?

**Comment by Satyam3976** [comment]
Please assign it to me in JS

**Comment by simrann20** [comment]
@jainaman224 @asha15 @singh-shreya6  Completed my assigned task. Please review my PR

**Comment by vyom153069** [comment]
i would like to work on this issue in C language , please ,please assign to me

**Comment by Tahanima** [comment]
Hello @jainaman224 @singh-shreya6
I am a GSSoC'20 participant and I want to implement the Euclidean Algorithm algorithm in Ruby language. So, please assign me this issue for Ruby language

**Comment by disha2sinha** [comment]
I want to work on this in dart and JS both . please assign me.

**Comment by shivamgupta57121** [comment]
Hello  @jainaman224 
Please assign it to me in Typescript.

**Comment by shivamgupta57121** [comment]
Hello @jainaman224 @raghav-dalmia  @singh-shreya6 
Please assign it to me in TypeScript.

**Comment by mightomi** [comment]
I like to work with Rust, can I be assigned @jainaman224
