### ISSUE TITLE
Implementation of doubly Linked list

### ISSUE THREAD

**Issue by AmitKarnam** [jainaman224/Algo_Ds_Notes#2908]
Hey,Would like to add code for implementation of doubly linked list in C.

**Comment by AmitKarnam** [comment]
@jainaman224  Would like to add implementation of doubly linked list in C programming language.

**Comment by vyom153069** [comment]
@jainaman224 i would like to work on this issue in java

**Comment by naresh2002** [comment]
Hello, if you would like the code to be in **C** or **C++** then please assign me this.
I am new to Github so if you think this is where I can begin to learn more about github then you can assign it to me or if you think this is the task  for some pros then you can assign it to anyone else.
But if you assign it to me, I would be so grateful to you.

**Comment by AmitKarnam** [comment]
Hey @jainaman224  can u please provide the reason for closing the issue
