### ISSUE TITLE
Print the prime factors of a number in cpp

### ISSUE THREAD

**Issue by vedangi163** [jainaman224/Algo_Ds_Notes#2922]
The program will print the prime factors of a number in cpp.

**Comment by shwhite17** [comment]
@vedangi163  assign it to me?

**Comment by vedangi163** [comment]
I am done with this program. It would be really great to contribute it. So
please assign this issue to me.

**Comment by shwhite17** [comment]
@vedangi163 are u not admin ?  But issue is opened by you.🤔
