### ISSUE TITLE
Travelling Salesman Problem NP complete

### ISSUE THREAD

**Issue by arpit1997** [jainaman224/Algo_Ds_Notes#341]
Travelling salesman problem TSP is considered as NP-hard problem.It is a classical problem of [optimisation](https://simple.wikipedia.org/wiki/Optimization_%28computer_science%29). Most easy and trivial solution is to go for all permutation and find the best solution but factorial n is a very large complexity for a problem. This problem comes in the domain of [Graph Theory](https://en.wikipedia.org/wiki/Graph_theory)
:smile:

**Comment by prasty** [comment]
Can I work on it.

**Comment by jainaman224** [comment]
@prasty go ahead.

**Comment by shreyasrivastava936** [comment]
Hi! I want to work on this issue. please assign this task to me for GSSoC'20.
