### ISSUE TITLE
Longest Increasing Subsequence

### ISSUE THREAD

**Issue by arpit1997** [jainaman224/Algo_Ds_Notes#371]
LIS is a dynamic programming problem and here is a description
>The longest Increasing Subsequence (LIS) problem is to find the length of the longest subsequence of a given sequence such that all elements of the subsequence are sorted in increasing order. For example, length of LIS for { 10, 22, 9, 33, 21, 50, 41, 60, 80 } is 6 and LIS is {10, 22, 33, 50, 60, 80}.

:cheese: :smile_cat: :smiley_cat:

**Comment by DylanGuedes** [comment]
Hi. The PR #375 adds the code to solve the size of the LIS.

**Comment by RashiG27** [comment]
hey, I would like to work on this one.

**Comment by jainaman224** [comment]
@RashiG27 Go on but keep in mind it is already implemented for C++ and ruby.

**Comment by Ask149** [comment]
@jainaman224  I would like to implement the Longest Increasing Subsequence in python.

**Comment by jainaman224** [comment]
@RashiG27 In which language are you working?

**Comment by isha-gautam** [comment]
@jainaman224 Can I work on this issue in Java?

**Comment by jainaman224** [comment]
@isha-gautam Go ahead.

**Comment by jainaman224** [comment]
@Ask149 Go ahead.

**Comment by Ask149** [comment]
> @Ask149 Go ahead.

Thanks, @jainaman224, I'll make a PR and notify you soon.

**Comment by shreyasrivastava936** [comment]
Hi! I want to work on this issue in Java. please assign this task to me for GSSoC'20.

**Comment by ravireddy07** [comment]
Hello @arpit1997 , I would like to work on this issue in Java and C++, C. Please assign this to me. Change the Badge too.
