### ISSUE TITLE
Index not being updated

### ISSUE THREAD

**Issue by igormp** [jainaman224/Algo_Ds_Notes#391]
Although I made a PR to update it in #390, I fear it won't take too long for it to be outdated again, so it would be nice if for every new commit we ask for an update to the index for every new algorithm or a new implementation to an existing one. 
Maybe we could make it a requirement for future PRs and make it clear in the README.

**Comment by jainaman224** [comment]
Actually, I have asked them to do so, but due to inability of many to resolve conflicts, I have chosen this approach.
It would be better if you recommend any better idea than mine. It will be a great help.
Thank you.

**Comment by igormp** [comment]
What if we update the README so it makes clear the need to update the index? We could put it somewhere along with [part 6](https://github.com/jainaman224/Algo_Ds_Notes#6-create-a-new-branch-bangbang)

**Comment by jainaman224** [comment]
Actually how to tell them how to resolve conflicts. Otherwise it will be great.

**Comment by igormp** [comment]
Hmm, I'm not that good with git to solve conflicts (had some myself and spent more time trying to solve then than doing the actual commit). Would be nice if someone more experienced could hand us some help.

**Comment by jainaman224** [comment]
We need to merge changes in a file where 2 or more person are working together. This is easy thing but for beginners, it is tough and I have also started contributing from this repository only. Hence I understand their state of mind.
