### ISSUE TITLE
Two redundant folders for Queues using linked list

### ISSUE THREAD

**Issue by nandukalidindi** [jainaman224/Algo_Ds_Notes#393]
Both `Queue_Linked_List.c` and `Queue_using_linked_list.c` seem to be implementing the same Queue logic.

Reason I am pointing this is I wanted to push a C++ template implementation for Queue which supports int, double, float, short etc. (all number datatypes) with header(**.h**) and implementation(**.cpp**) in different files.

**Comment by jainaman224** [comment]
I will consult my team and get back to you. Thank you for pointing out.

**Comment by jainaman224** [comment]
Done
