### ISSUE TITLE
Could we add unit test?

### ISSUE THREAD

**Issue by fnaith** [jainaman224/Algo_Ds_Notes#399]
I found this project is far more useful than just notes, it contains so many data structure that some language's standard library do not even have. If it provides some test case to guarantee the stability, then more real application will consider to use this project. In that case, test should not be contained as main function in source. But now, the structure of this project seems only consider code files. Maybe the maintainer should tell us how to contribute test file.

**Comment by jainaman224** [comment]
I always promote creation of separate function instead of writing inside main function. For that specific purpose we can have commented main function.
If you have any better solution, please suggest.
Thanks

**Comment by fnaith** [comment]
Using simple strategy for managing multiple language library maybe a solution. I just want to check how test works on this project.
