### ISSUE TITLE
Easy Accessibility 

### ISSUE THREAD

**Issue by Ifyokoh** [jainaman224/Algo_Ds_Notes#448]
I think since these algorithms are written in different languages, I suggest the repo be arranged in folders, each folder containing algorithms of a particular language. This will help for easy accessibility

**Comment by jainaman224** [comment]
Hi @Ifyokoh, what about making the platform for searching them?

**Comment by infiniteoverflow** [comment]
I would like to help in this task.

**Comment by Karna98** [comment]
What's the status of this issue? I would like to work on it.

**Comment by jainaman224** [comment]
@Karna98 Take another issue. I will setup a basic project after GSSoC then we can discuss about web portal.
