### ISSUE TITLE
Adding matrix folder

### ISSUE THREAD

**Issue by NirmalKumarJoshi** [jainaman224/Algo_Ds_Notes#450]
This folder will contain all the programs related to matrix in different languages.
The few programs that can be added are-
- [x] Matrix Addition
- [x] Matrix Subtraction
- [x] Matrix Multiplication
- [ ] Matrix Multiplication | Recursive
- [x] Sort a given matrix
- [x] Program for scalar multiplication of a matrix
- [ ] Sum of middle row and column in Matrix
- [x] Mirror of matrix across diagonal
- [ ] Search in a row wise and column wise sorted matrix
- [x] Program to Compute Determinant of a Matrix
- [ ] And more to be added...

**Comment by NirmalKumarJoshi** [comment]
@jainaman224 I want to work on this issue. Please assign me.

**Comment by jainaman224** [comment]
@NirmalKumarJoshi Please go ahead.

**Comment by quicksilver28** [comment]
Hello! I am a gssoc participant and interested in contributing to this issue. I'll work on providing, C, C++ and Java solutions!

**Comment by jainaman224** [comment]
@quicksilver28 Go ahead. Just look at the repo, as there are algorithms already implemented in c++.

**Comment by Karna98** [comment]
I would like to implement all the above Matrix Operation in Python

**Comment by jainaman224** [comment]
@Karna98 Go ahead.
Add 5 files at most in a commit. If you are GSSoC participant.

**Comment by ayanujju** [comment]
Can I implement this in C language ?

**Comment by jainaman224** [comment]
@ayanujju Go ahead.

**Comment by somya-kapoor** [comment]
I would like to implement the following matrix operation in C++.
Matrix operation: Matrix Multiplication | Recursive, Sum of middle row and column in Matrix, print Lower triangular, print  Upper triangular and check idempotent matrix.

**Comment by ayanujju** [comment]
I think you have assigned it to Nirmal by mistake @jainaman224 .Please assign it to me.

**Comment by jainaman224** [comment]
@somya-kapoor Go ahead.

**Comment by jainaman224** [comment]
@ayanujju There are multiple people working on this.
You can work on it. Don't worry about assigning issues.

**Comment by ayanujju** [comment]
okay, sorry for my wrong assumption

**Comment by somya-kapoor** [comment]
I would like to implement the following matrix operation in C.
Matrix operation: Matrix Multiplication | Recursive, Sum of middle row and column in Matrix, print Lower triangular, print Upper triangular and check idempotent matrix.

**Comment by jainaman224** [comment]
@somya-kapoor It is already assigned.
