### ISSUE TITLE
Python Implementations for AVL_Tree, Treap, Red_Black_Tree, Huffman-Encoding , Doubly_Linked_List  and Circular_Linked_List

### ISSUE THREAD

**Issue by vidyabhandary** [jainaman224/Algo_Ds_Notes#452]
Hi jainaman224,
I would like to work on the python implementations of the following items
1. AVL_Tree at https://github.com/jainaman224/Algo_Ds_Notes/tree/master/AVL_Tree
2. Treap at https://github.com/jainaman224/Algo_Ds_Notes/tree/master/Treap
3. Red_Black_Tree at https://github.com/jainaman224/Algo_Ds_Notes/tree/master/Red_Black_Tree
4. Huffman-Encoding at https://github.com/jainaman224/Algo_Ds_Notes/tree/master/Huffman-Encoding
5. Doubly_Linked_List at https://github.com/jainaman224/Algo_Ds_Notes/tree/master/Doubly_Linked_List
6. Circular_Linked_List at https://github.com/jainaman224/Algo_Ds_Notes/tree/master/Circular_Linked_List

**Comment by jainaman224** [comment]
@vidyabhandary Go ahead.

**Comment by GayathriVenkatesh** [comment]
Can I implement Huffman Encoding in Python?

**Comment by jainaman224** [comment]
@GayathriVenkatesh Go ahead.
