### ISSUE TITLE
Add readme.md for linkedlist.

### ISSUE THREAD

**Issue by InfiniteVerma** [jainaman224/Algo_Ds_Notes#457]
Hi. I would like to work on README.md for linkedlist. I am a GSSOC participant.

**Comment by Saranya-jena** [comment]
I am a GSSoC participant and I would like to add a readme.md for linkedlist.

**Comment by jainaman224** [comment]
@InfiniteVerma Go ahead.

**Comment by InfiniteVerma** [comment]
I sent a pull request. Number #465
