### ISSUE TITLE
Working on README.md for Binary Search Trees

### ISSUE THREAD

**Issue by Soumya0803** [jainaman224/Algo_Ds_Notes#458]
I would like to add a readme.md for Binary Search Trees.
I am a Gssoc participant.

**Comment by Saranya-jena** [comment]
I am interested in adding a readme.md for Binary Search Trees.
I am a GSSoC particpant.

**Comment by jainaman224** [comment]
@Soumya0803 Please go ahead.

**Comment by jainaman224** [comment]
@Saranya-jena What about documenting Trie ?
If you are interested please create an issue.

**Comment by Saranya-jena** [comment]
Okay sir , I will do that.

**Comment by jainaman224** [comment]
@Saranya-jena Are you working on it?
