### ISSUE TITLE
Insertion Sort, Quick Sort, Selection Sort, Radix Sort in js

### ISSUE THREAD

**Issue by Ash-D23** [jainaman224/Algo_Ds_Notes#460]
I am a GSSOC Participant
I would like to work on these sorting algorithms in js

**Comment by jainaman224** [comment]
Go ahead.

**Comment by KanchanThareja** [comment]
@jainaman224 I want to work on the above algorithms in C, C++ and Java

**Comment by jainaman224** [comment]
@KanchanThareja Sorry but it is already implemented.
