### ISSUE TITLE
Josephus Problem

### ISSUE THREAD

**Issue by tusharsabhani** [jainaman224/Algo_Ds_Notes#461]
In this problem n people are standing in a circle and n-1 are executed. In each step a certain number of people  are skipped and the next person in the circle is executed. This certain number is denoted by k, so after every execution k-1 people are skipped and the next person is executed. By Josephus method we need to find the place where the person will not be executed.

**Comment by DeepankarAcharyya** [comment]
@tusharsabhani   I am a GsSoc participant and would like to work on it.

**Comment by tusharsabhani** [comment]
I already did for C & C++

**Comment by DeepankarAcharyya** [comment]
I have done the program for python3

**Comment by jainaman224** [comment]
Great.
@DeepankarAcharyya Please claim issue first from next time.
