### ISSUE TITLE
Working on README.md for Stacks using Linked Lists

### ISSUE THREAD

**Issue by gauravburjwal** [jainaman224/Algo_Ds_Notes#466]
Hello,
I am a GSSoC participant.
I would like to add a README.md for Stacks using Linked Lists.

**Comment by khushal87** [comment]
could i add stack using linked list implementation is javascript??

**Comment by jainaman224** [comment]
Go ahead.

**Comment by jainaman224** [comment]
@gauravburjwal Go ahead.
