### ISSUE TITLE
Add readme.md for binary heap

### ISSUE THREAD

**Issue by InfiniteVerma** [jainaman224/Algo_Ds_Notes#469]
@jainaman224 Hi. I would like to work on README.md for Binary Heap. I am a GSSOC participant.

**Comment by jainaman224** [comment]
@InfiniteVerma Go ahead.

**Comment by jainaman224** [comment]
@InfiniteVerma Are you working on it?

**Comment by InfiniteVerma** [comment]
Yeah. Need time till 4th. Sorry for the delay.

**Comment by jainaman224** [comment]
@InfiniteVerma No issues.
