### ISSUE TITLE
Add readme.md for depth-fitst-search

### ISSUE THREAD

**Issue by Jayashree-panda** [jainaman224/Algo_Ds_Notes#473]

**Comment by harsha-iiiv** [comment]
@Jayashree-panda  please assign to me.

**Comment by Jayashree-panda** [comment]
@harsha-iiv actually I have solved it and I am about to make the PR. You can view other topic and create an issue. I believe you will get better.

**Comment by Jayashree-panda** [comment]
@jainaman224 Can you please help me saying for adding the compile online option. I don't get that.

**Comment by jainaman224** [comment]
@Jayashree-panda Go ahead.
