### ISSUE TITLE
Adding strings folder

### ISSUE THREAD

**Issue by NirmalKumarJoshi** [jainaman224/Algo_Ds_Notes#474]
This folder will contain all programs related to strings in different languages
The few programs that can be added are:

- [ ] String length
- [ ] Anagram Strings
- [ ] Vowels and consonants in a string
- [ ] String Pattern
- [ ] Substring within a string

**Comment by NirmalKumarJoshi** [comment]
@jainaman224 Please assign me this issue

**Comment by jainaman224** [comment]
Be specific about substring within a string.
Go ahead with anagram strings, others are not relevant.

**Comment by divya7shahi** [comment]
hello @jainaman224 I am a newbie at opensource and I want to work on this issue as well,I please assign me this issue ,if there is anyscope

**Comment by jainaman224** [comment]
@divya7shahi Go ahead for anagram of strings.

**Comment by Ash-D23** [comment]
hello @jainaman224 can i work in js or python for this issue anagrams ? if there is any scope

**Comment by jainaman224** [comment]
@Ash-D23 Go ahead.
