### ISSUE TITLE
MoreTraversal On Tree

### ISSUE THREAD

**Issue by helios1101** [jainaman224/Algo_Ds_Notes#475]
I'm submitting a feature request :
 
Description :
The few programs that can be added are-
- [x] Mirror Image Of Tree
- [x] Top View Of Tree
- [x] Left View Of Tree

Current behaviour:
      Currently there is no solutions in any language.

Expected behaviour:
      There should be codes in each language.

Would you like to work on the issue?
      Yes

@jainaman224 I want to work on this issue. Please assign me.

**Comment by jainaman224** [comment]
Go ahead.

**Comment by helios1101** [comment]
Do I need to update the index page also? Do I need to change something or everything is fine?
Please review the PR #509 

@jainaman224
