### ISSUE TITLE
Topological Sort using Java

### ISSUE THREAD

**Issue by Chaitanyasuma** [jainaman224/Algo_Ds_Notes#480]

**Comment by Chaitanyasuma** [comment]
Can I implement this using Java?

**Comment by jainaman224** [comment]
If there is no solution in java and no one is working. Go ahead.

**Comment by joel-razor1** [comment]
@jainaman224 , can I implement this sorting algorithm in **C**? I can complete this in less time.

**Comment by jainaman224** [comment]
@joel-razor1 It is not about time. Go ahead
