### ISSUE TITLE
Disjoint Sets in Python

### ISSUE THREAD

**Issue by kaustubh-pandey** [jainaman224/Algo_Ds_Notes#481]
I would like to add an implementation of Disjoint Sets in Python. Can I work on this?

**Comment by Jaseemck** [comment]
i would like to contribute some programs to this session. Please assign me on this @jainaman224 .

**Comment by jainaman224** [comment]
@kaustubh-pandey Go ahead.

**Comment by jainaman224** [comment]
@Jaseemck Find or create an issue and claim it.
