### ISSUE TITLE
Adding code for hybrid inheritence(c++)

### ISSUE THREAD

**Issue by Jayashree-panda** [jainaman224/Algo_Ds_Notes#482]

**Comment by jainaman224** [comment]
I don't think this is relevant enough.

**Comment by divya7shahi** [comment]
hello @jainaman224  I can add  code for hybrid inheritance like the cases where it is used and it's properties 
if it's still in the issue list,please may I get this issue

**Comment by jainaman224** [comment]
@divya7shahi Hybrid Inheritance is correct to implement. It is not anything specific.
