### ISSUE TITLE
0-1 Knapsack Problem in python (GSSoC Participant)

### ISSUE THREAD

**Issue by joel-razor1** [jainaman224/Algo_Ds_Notes#486]
I've noticed that 0-1 Knapsack Program is available in c++ and java only. I would like to work on this problem.

**Comment by souka1** [comment]
I would like to work on this problem

**Comment by diptinayan** [comment]
I am highly interested to work on this problem.

**Comment by Jaseemck** [comment]
I can code the program in python and c. I have done it in c++ and quite strong in its concept. I can close this issue within the deadline. So please assign me on this @jainaman224 .

**Comment by shadow989** [comment]
I'm interested in this issue and can do this within the time provided .I have worked on this algorithm in c language and can do it in python for sure..

**Comment by jainaman224** [comment]
@Jaseemck Go ahead if it is not implemented in any of those language.

**Comment by jainaman224** [comment]
@shadow989 Please have a look at other issues.

**Comment by Karna98** [comment]
is this issue open? I want to work on it.

**Comment by jainaman224** [comment]
@Karna98 Please specify the language.

**Comment by Karna98** [comment]
@jainaman224 Renaming of the issue is required as it has been already implemented.
or Close the issue.

**Comment by jainaman224** [comment]
Ok
