### ISSUE TITLE
Machine Learning Algorithms using python

### ISSUE THREAD

**Issue by mani1soni** [jainaman224/Algo_Ds_Notes#487]
Hey, @jainaman224 I want to add some Machine Learning algorithms like Decision Tree, Linear Regression, K-means clustering etc. using python.

**Comment by mani1soni** [comment]
I would like to work on it.

**Comment by diptinayan** [comment]
I would like to contribute some algorithms in this.

**Comment by jainaman224** [comment]
@mani1soni Go ahead, tell me what algorithms are you going to be working on.
@diptinayan you can choose any other algorithm than him.

**Comment by shadow989** [comment]
I'd like to contribute some Algorithm in this...

**Comment by mani1soni** [comment]
@jainaman224 i'll work on  Decision Tree, Linear Regression, K-means clustering and Cnn.

**Comment by jainaman224** [comment]
Ok

**Comment by jainaman224** [comment]
@mani1soni Are you still working on it?

**Comment by mani1soni** [comment]
@jainaman224 yes, i am working...but i'm able to contribute in this by 3rd april because of college's internals.

**Comment by jainaman224** [comment]
No issues.

**Comment by mugdhajoshi** [comment]
I want to work on this issue as part of GSSoC 2020. Please assign it to me.
Only linear regression is implemented till now in the code.
I can implement other machine learning algorithms like multiple linear regression, Support vector regression, Support vector machine, k-nearest neighbour, K means clustering, decision tree, random forest, Naive bayes etc and also deep learning in python like convolutional neural network.

**Comment by jainaman224** [comment]
@mugdhajoshi  Create separate issue for each of them.
