### ISSUE TITLE
Adding Algorithms in Dart & Kotlin & Rust

### ISSUE THREAD

**Issue by piedcipher** [jainaman224/Algo_Ds_Notes#490]
I would like to propose 2 new languages in which Algorithms can added.
- Dart
- Kotlin
- Rust
 
I'm GSSoC 19 Participant, since there was no issue for it, I created this one. Let me know your thoughts.

**Comment by jainaman224** [comment]
Yes, you can code in any of the language. Go ahead. But make sure to specify algorithms you are going to work on.

**Comment by shubhammantri1** [comment]
I am a participant of ggsoc and I want to write Bubble sort algorithm in Kotlin can I do That.

**Comment by jainaman224** [comment]
Create a new issue and go ahead.
