### ISSUE TITLE
programs in JavaScript of different ds and algorithms.

### ISSUE THREAD

**Issue by khushal87** [jainaman224/Algo_Ds_Notes#502]
Can i start working on it? #502

**Comment by khushal87** [comment]
- [ ] stack using linked list in js 

- [ ] stack using array in js 

- [ ] binary tree and its operations in js 

- [ ] array operations in js 

- [ ] queue using stack in js 
this are some preliminary programs i want to work on can I ?

**Comment by jainaman224** [comment]
Go ahead.
