### ISSUE TITLE
Adding Modular Exponentiation Algorithm in C++,Python, Java

### ISSUE THREAD

**Issue by MastersAbh** [jainaman224/Algo_Ds_Notes#506]

**Comment by GayathriVenkatesh** [comment]
Can I work on this in Python?

**Comment by divya7shahi** [comment]
hello @jainaman224 may I work on this in c++,please assign me this issue I would like to work on it

**Comment by jainaman224** [comment]
@MastersAbh Please tell me what is modular exponentation.

**Comment by jainaman224** [comment]
@GayathriVenkatesh Please have a look at other issue.

**Comment by jainaman224** [comment]
@divya7shahi Can you work in c?

**Comment by MastersAbh** [comment]
For computing (x^y)%p for large numbers, we use modular exponentiation, where p is generally a prime number. It can be implemented both, recursively and iteratively.

**Comment by jainaman224** [comment]
@MastersAbh Go ahead.
