### ISSUE TITLE
Linked list implementation Javascript

### ISSUE THREAD

**Issue by khushal87** [jainaman224/Algo_Ds_Notes#508]
### Objective 

Linked list implementation Javascript

#### Assigned to (if any)
I am working on it.

**Comment by khushal87** [comment]
Refer to #492 

Ping @jainaman224

**Comment by jainaman224** [comment]
You have assigned to many issues.
Please take up to 2 issues at a time.

**Comment by khushal87** [comment]
Sorry I thought it is okay to add it.It wont happen again

**Comment by jainaman224** [comment]
@khushal87 Now you can work on it.
