### ISSUE TITLE
Adding Coin Change Problem in C++, Python, Java

### ISSUE THREAD

**Issue by singh-shreya6** [jainaman224/Algo_Ds_Notes#512]

**Comment by Rashmirana** [comment]
I like to implement this problem in java. 
I'm a GSSoC participant.

**Comment by raghav-dalmia** [comment]
I want to implement this in C++. I am also a GSSoC-19 participant.

**Comment by jainaman224** [comment]
@singh-shreya6 Go ahead.

**Comment by jainaman224** [comment]
@Rashmirana and @raghav-dalmia Let's wait for @singh-shreya6 or you can choose any other language.
