### ISSUE TITLE
Adding Algorithms for constructing Tree from given Inorder and Preorder traversals

### ISSUE THREAD

**Issue by somya-kapoor** [jainaman224/Algo_Ds_Notes#513]
I would like to work on constructing a tree from given inorder and preorder traversals in c++.
I am a GSSoC participant.

**Comment by jainaman224** [comment]
@somya-kapoor Go ahead.

**Comment by rashmi3105** [comment]
I would like to work on it. Can I take this up? I am a GSSoC participant.

**Comment by isha-gautam** [comment]
@jainaman224 can I work on it in Java?

**Comment by somya-kapoor** [comment]
I would like to work on constructing a tree from given inorder and postorder traversals in c++.

**Comment by jainaman224** [comment]
@rashmi3105 Go ahead for other language than c++ or java.

**Comment by jainaman224** [comment]
@isha-gautam Go ahead for java.

**Comment by jainaman224** [comment]
@pankajpoply45 Go ahead for python.

**Comment by jainaman224** [comment]
@somya-kapoor It is assigned to you for c++.

**Comment by pankajpoply45** [comment]
#602
