### ISSUE TITLE
Manacher’s Algorithm in c++

### ISSUE THREAD

**Issue by somya-kapoor** [jainaman224/Algo_Ds_Notes#514]
Hi, I would like to add Manacher’s Algorithm( for finding longest palindromic substring) using c++.

**Comment by jainaman224** [comment]
@somya-kapoor Go ahead.

**Comment by shahkv95** [comment]
Heyy @somya-kapoor  are you actively working on it?

**Comment by somya-kapoor** [comment]
Yes, I have submitted PR.
