### ISSUE TITLE
Linked List Trickiest Questions in C++

### ISSUE THREAD

**Issue by saumyashrm2802** [jainaman224/Algo_Ds_Notes#520]
Hey...I want to add trickiest and mind boggling questions on linked list in C++.
For example - Converting singly linked list into circular linked list.
                       Removing loop from a linked list
                       Partitioning linked list around a given value
and lots more.

**Comment by jainaman224** [comment]
@saumyashrm2802 Go ahead. Just suggest the folder name you are going to use.

**Comment by jainaman224** [comment]
@saumyashrm2802 Are you still working on it?
