### ISSUE TITLE
3 Way Merge Sort

### ISSUE THREAD

**Issue by KavithaVarughese** [jainaman224/Algo_Ds_Notes#521]
3 Way merge sort designed in c language

**Comment by KavithaVarughese** [comment]
Can I take this up ?

**Comment by rashmi3105** [comment]
I would like to implement this. Can I take this up? I am a GSSoC participant.

**Comment by jainaman224** [comment]
@KavithaVarughese Please mention the language.
@rashmi3105 You can take other language. Ones Kavitha decides.

**Comment by KavithaVarughese** [comment]
I will do it in c language

**Comment by rashmi3105** [comment]
I will do it in Java

**Comment by shahkv95** [comment]
Is it similar to merge 3 sorted array ? @rashmi3105 @KavithaVarughese 
If so, I will take it for python.

**Comment by jainaman224** [comment]
@KavithaVarughese Are you still working on it?

**Comment by jainaman224** [comment]
@shahkv95 Are you still working on it?

**Comment by aadhar54** [comment]
I would like to work on this issue. Please assign it to me for Java .

**Comment by shreyasrivastava936** [comment]
Hi! I want to work on this issue in Java. please assign this task to me for GSSoC'20.

**Comment by abhinashgiri** [comment]
I would like to work on this in c++ as a part of GSSoC 20 , may I, please.

**Comment by jainaman224** [comment]
@aadhar54 Go ahead for java
@abhinashgiri Go ahead with C++
