### ISSUE TITLE
Adding README.md with updated python code in Dynamic Programming Rod Cutting 

### ISSUE THREAD

**Issue by dshahid380** [jainaman224/Algo_Ds_Notes#523]
### This issue is related to Dynamic Programming Rod Cutting Algorithm
**Issues**
 - No README.md are there in the respective folder.
 - Steps are not written very well in the respective code.

Need to improve this.

**Comment by jainaman224** [comment]
@dshahid380 Go ahead.

**Comment by dshahid380** [comment]
@jainaman224  sir, i have already created a pull request for the same.
Here is the link
https://github.com/jainaman224/Algo_Ds_Notes/pull/532
