### ISSUE TITLE
Program for Tower of Hanoi in C++

### ISSUE THREAD

**Issue by somya-kapoor** [jainaman224/Algo_Ds_Notes#537]
I would like to work on it

**Comment by AkshitAggarwal** [comment]
If this issue hasn't been assigned to anyone yet, I would like to work on it. I am yet to make my first contribution in this project.

**Comment by jainaman224** [comment]
@somya-kapoor Go ahead. But don't take too many issues.

**Comment by jainaman224** [comment]
@AkshitAggarwal Implement in other language than c++ but mention it here first.

**Comment by AkshitAggarwal** [comment]
@jainaman224 I'm sorry but as of now, I can only program in C and C++

**Comment by jainaman224** [comment]
@AkshitAggarwal Go ahead with c.

**Comment by AkshitAggarwal** [comment]
Alright!

**Comment by shahkv95** [comment]
@jainaman224 Heyy, I would like to take up this task. Can I take up the task in python, as contributors are already working in C and C++?

**Comment by jainaman224** [comment]
@shahkv95 Go ahead.

**Comment by AvinashDhillor** [comment]
can i implement in java

**Comment by Ash-D23** [comment]
@jainaman224 can i implement this in js

**Comment by jainaman224** [comment]
@Ash-D23 Go ahead.

**Comment by kunal-kushwaha** [comment]
@jainaman224 I would like to implement this in Java

**Comment by jainaman224** [comment]
@kunal-kushwaha Go ahead.
