### ISSUE TITLE
Cocktail sort  in c++

### ISSUE THREAD

**Issue by somya-kapoor** [jainaman224/Algo_Ds_Notes#538]
I would like to on with it. (it is a variation of Bubble sort)

**Comment by jainaman224** [comment]
@somya-kapoor Go ahead.

**Comment by shahkv95** [comment]
Heyy @jainaman224, I would like to take up this task.
May I proceed?

**Comment by shahkv95** [comment]
If @somya-kapoor is working in C++, I can take up python.

**Comment by jainaman224** [comment]
@shahkv95 Go ahead with python.

**Comment by shahkv95** [comment]
I have sent the PR for python code for Cocktail Sort. Do check it out @jainaman224 .

**Comment by somya-kapoor** [comment]
@jainaman224  can I implement it in c?

**Comment by jainaman224** [comment]
Please don't take up too many issues.
If this issue remains unassigned. I will assign you but first complete assigned issues.

**Comment by somya-kapoor** [comment]
@jainaman224 Please assign me this issue in c.

**Comment by jainaman224** [comment]
@somya-kapoor Go ahead.

**Comment by jainaman224** [comment]
@somya-kapoor Are you working on it?
