### ISSUE TITLE
circle sort in c,c++,java and python

### ISSUE THREAD

**Issue by raghav-dalmia** [jainaman224/Algo_Ds_Notes#551]

**Comment by jainaman224** [comment]
@raghav-dalmia Please throw some light on circle sort.

**Comment by shahkv95** [comment]
@raghav-dalmia Heyy, I would like to code circle sort. I can work in C, C++ and python. May I proceed for the same? If yes, which language should I pick up ?

**Comment by jainaman224** [comment]
What is circle sort?

**Comment by raghav-dalmia** [comment]
Hey aman, i don't know the exact logic/math behind circle sort, but know
the algorithm. In this sort we will compare 1st and last, 2nd and second
last and so on elements of array, and swap the elements if first is greater
than rearer one ,then split the array in two half and repeat the same
procedure for those two half array. If there is any swaping in the above
procedure then repeat the whole procedure again. If not swaping is done,
then we get sorted array. You can refere [this](
https://www.google.com/amp/s/www.geeksforgeeks.org/circle-sort/amp/).

**Comment by raghav-dalmia** [comment]
Hey shahkv95, I am writing this algo in all four mention language, you can choose any other.
