### ISSUE TITLE
Adding Job Sequencing algorithm in C++, Python

### ISSUE THREAD

**Issue by MastersAbh** [jainaman224/Algo_Ds_Notes#558]
I want to add Job sequencing algo in C++ & Python. Please assign this to me.

**Comment by rishabhgarg25699** [comment]
@MastersAbh Yes you can go ahead but please tell me one thing Job Sequencing Problem can be achieved by greedy algorithm as well as disjoint set. Please specify which algorithm you use. And also in your code please first tell the what is the Job Sequencing Problem and after then tell the solution with input and output.

**Comment by MastersAbh** [comment]
Sure. I will take care of that. Thanks. I'll use greedy approach.

**Comment by rishabhgarg25699** [comment]
@jainaman224 why you assigned this issue to me . I am the mentor not the participant .

**Comment by jainaman224** [comment]
Sorry, I thought it was PR.
