### ISSUE TITLE
Adding Max-Array sum solution using dynamic programming in cpp,python,c and php

### ISSUE THREAD

**Issue by Jaseemck** [jainaman224/Algo_Ds_Notes#559]
Can i work on this? @jainaman224

**Comment by jainaman224** [comment]
Go ahead.
Please try to find name of algorithm if exists.

**Comment by Jaseemck** [comment]
Looks like Kadane's Algorithm is already implemented

**Comment by jainaman224** [comment]
@Jaseemck Yes. You can either add comments, documentation or improve variable names. If required.
