### ISSUE TITLE
Adding Comb Sort in C++, Java, Python and Go

### ISSUE THREAD

**Issue by singh-shreya6** [jainaman224/Algo_Ds_Notes#560]
Comb Sort is an improvement over Bubble Sort which solves the problem of small values at the end of the list which decreases performance in Bubble Sort. Its best case time complexity is O(n log n) and worst case O(n^2)

**Comment by rishabhgarg25699** [comment]
@singh-shreya6 Yes Go ahead . And I have a suggestion also Please write the code in the good manner with good commenting in all 4 language.
