### ISSUE TITLE
Adding Z algorithm in Java 

### ISSUE THREAD

**Issue by Vaibhavraj10** [jainaman224/Algo_Ds_Notes#569]
Z algorithm is a linear time string matching algorithm which runs in O(N) complexity. It is used to find all occurrence of a pattern P in a string S, which is common string searching problem.

**Comment by Vaibhavraj10** [comment]
I want to work on this issue.

**Comment by Jaseemck** [comment]
Can i implement it in other programming languages python, cpp, c and php? @jainaman224

**Comment by rishabhgarg25699** [comment]
I appreciate your work and your PR but it is good if you first open the issue and not submit PR until we pass your issue . It is the good practise in open source .

**Comment by somya-kapoor** [comment]
can I work on it in c++?

**Comment by rishabhgarg25699** [comment]
@somya-kapoor  In cpp @Jaseemck  is doing . You can take another issue

**Comment by uemarica** [comment]
Hey, i've added a java implementation without asking, will take care from next time.

**Comment by jainaman224** [comment]
@Jaseemck Are you working on Php?
