### ISSUE TITLE
bucket-sort in c++

### ISSUE THREAD

**Issue by somya-kapoor** [jainaman224/Algo_Ds_Notes#575]

**Comment by shahkv95** [comment]
Should I I take up this task?

**Comment by rishabhgarg25699** [comment]
If @somya-kapoor not want to work to in this issue then @shahkv95 you can take this issue . Now it is assigned to @somya-kapoor .

**Comment by shahkv95** [comment]
Heyy @somya-kapoor are you working on this issue. If not please pass it to me. 
Please reply asap.
Thank you.

**Comment by somya-kapoor** [comment]
I am working on it.

**Comment by somya-kapoor** [comment]
My Branch #623

**Comment by somya-kapoor** [comment]
> I am working on it.

#623
