### ISSUE TITLE
AVL Trees in Java

### ISSUE THREAD

**Issue by Vaibhavraj10** [jainaman224/Algo_Ds_Notes#581]
AVL Tree can be defined as height balanced binary search tree in which each node is associated with a balance factor which is calculated by subtracting the height of its right sub-tree from that of its left sub-tree.

**Comment by Vaibhavraj10** [comment]
I want to work on this issue!

**Comment by rishabhgarg25699** [comment]
@Vaibhavraj10 Please go ahead .  But please comment your code and write input and output of the code.
