### ISSUE TITLE
Adding nCr%p using Dynamic Programming in C++,Java & Python

### ISSUE THREAD

**Issue by MastersAbh** [jainaman224/Algo_Ds_Notes#586]
I want to work on this issue. please assign it to me.

**Comment by rishabhgarg25699** [comment]
Assigned. But please comment your code and write input and output of the code.

**Comment by pankajpoply45** [comment]
I want to work in it in java @rishabhgarg25699

**Comment by jainaman224** [comment]
@pankajpoply45 It is already done in java.
