### ISSUE TITLE
Largest Sum Contiguous Subarray

### ISSUE THREAD

**Issue by shahkv95** [jainaman224/Algo_Ds_Notes#591]
The program code is to find the largest sum of continuous sub array.
Languages : C++ , Python

**Comment by shahkv95** [comment]
Heyy @jainaman224 may I proceed for the same?

**Comment by divs30** [comment]
may I work on it in c @rishabhgarg25699

**Comment by shahkv95** [comment]
Heyy @rishabhgarg25699 , we received a message in slack from one of our GS from GSSoC to submit PRs for those issues which are labelled as 'gssoc19' . Other labels includes 'beginner' , 'easy' , 'medium' , 'hard' as you are aware about it. 
I request you @rishabhgarg25699 to please label the issue with the required label so that I can send you the PR immediately.
Thank you so much.

**Comment by jainaman224** [comment]
@shahkv95 Is kadane algorithm different?
@divs30 Go ahead for C.

**Comment by shahkv95** [comment]
> @shahkv95 Is kadane algorithm different?
> @divs30 Go ahead for C.

@jainaman224 No both are same. Kadane algorithm itself is Largest Sum Contiguous Subarray.

**Comment by shahkv95** [comment]
I think after I opened this issue,mistakenly @KanchanThareja opened it with synonymous name, i.e. Kadane's Algorithm. I think still there's no problem as she is working in C and Javascript and I am working in C++ and Python. If you want then I can change the name to Kadane as well.
@jainaman224  is it possible for you to merge both the PR in one folder?

**Comment by pankajpoply45** [comment]
@jainaman224 can I work on it in java?

**Comment by jainaman224** [comment]
@shahkv95 Change name to Kadane algorithm.

**Comment by jainaman224** [comment]
@pankajpoply45 It is already implemented in java.
@shahkv95 It is already implemented in cpp and python.
