### ISSUE TITLE
pancake sort in c++

### ISSUE THREAD

**Issue by divs30** [jainaman224/Algo_Ds_Notes#596]
Pancake sort is a way of sorting an unsorted array  by performing as many few reversals as it is possible unlike traditional sorting algorithm which work on comparisons.

**Comment by divs30** [comment]
may I work on it.

**Comment by ananya-deka** [comment]
Can I work on it in C?

**Comment by jainaman224** [comment]
@divs30 Go ahead.
@ananya-deka Go ahead.

**Comment by vaishali614** [comment]
can i work on it in c++?

**Comment by divs30** [comment]
hello mentors I have added code of pancake sort in c++ please look into it @jainaman224, @rishabhgarg25699

**Comment by divs30** [comment]
I would like to work on it in python as well may I

**Comment by gupta2140** [comment]
> can i work on it in c++?

Hi @vaishali614 someone is already assigned this issue. You are welcome to look at other open tasks :)

**Comment by vaishali614** [comment]
Okayy @gupta2140

**Comment by sez98** [comment]
@ananya-deka if ur not doing it in c.. may I work on it? @jainaman224 please let me know

**Comment by sez98** [comment]
@jainaman224 can i work on pancake sort in java? no one has taken that

**Comment by jainaman224** [comment]
@sez98 Go ahead.

**Comment by jainaman224** [comment]
@sez98 Are you working on it?

**Comment by jainaman224** [comment]
@vaishali614 Would you like to work in Java?

**Comment by sez98** [comment]
yes .. i am... i ll complete it in a few days.

**Comment by vaishali614** [comment]
@jainaman224 no aman, i code in c++!
