### ISSUE TITLE
Optimal Binary Search Tree 

### ISSUE THREAD

**Issue by GOVINDDIXIT** [jainaman224/Algo_Ds_Notes#604]
Make separate PR for each language

**Comment by uemarica** [comment]
I can implement it in java and python

**Comment by GOVINDDIXIT** [comment]
@uemarica Pls go ahead 👍

**Comment by somya-kapoor** [comment]
Can I implement it in C++?

**Comment by agarwalprashasti** [comment]
I want to work on this, Kindly assign me this issue

**Comment by jainaman224** [comment]
@somya-kapoor Go ahead.

**Comment by jainaman224** [comment]
@agarwalprashasti Choose language that is not already assigned.

**Comment by somya-kapoor** [comment]
Can I implement it in C?

**Comment by jainaman224** [comment]
@somya-kapoor Go ahead.

**Comment by jainaman224** [comment]
@uemarica Are you still working on it?
