### ISSUE TITLE
Adding Longest Common Subsequence problem in C++, Java, Python, Go

### ISSUE THREAD

**Issue by singh-shreya6** [jainaman224/Algo_Ds_Notes#610]
I want to implement it using Dynamic Programming Approach.

**Comment by rishabhgarg25699** [comment]
@singh-shreya6  Please go ahead

**Comment by rashmi3105** [comment]
I want to implement this in c++.

**Comment by jainaman224** [comment]
@rashmi3105 Please have a look at other issue. It is already assigned.
