### ISSUE TITLE
Aho-Corasick Algorithm in C++

### ISSUE THREAD

**Issue by Vaibhavraj10** [jainaman224/Algo_Ds_Notes#624]
It is a kind of dictionary-matching algorithm that locates elements of a finite set of strings (the "dictionary") within an input text.

**Comment by Vaibhavraj10** [comment]
Can I work on this?

**Comment by jainaman224** [comment]
@Vaibhavraj10 Go ahead.

**Comment by jainaman224** [comment]
@Vaibhavraj10 Are you working on it?

**Comment by Vaibhavraj10** [comment]
@jainaman224 yes, I was actually busy with the college work. I will soon submit the PR within a day or two.

**Comment by archi14** [comment]
@jainaman224 Can I work on this?

**Comment by jainaman224** [comment]
@archi14 Go ahead.
