### ISSUE TITLE
Graph coloring algorithm

### ISSUE THREAD

**Issue by shahkv95** [jainaman224/Algo_Ds_Notes#633]
It is an algorithm used for coloring certain elements in a graph based on the constraints provided.
Languages to be included : **C++ , Java**
I request @jainaman224 or other mentors to label it under the label '**difficult**'(if you feel so) along with '**gssoc19**'.
Thank you so much.

**Comment by KanchanThareja** [comment]
I want to work on this one in Python and JavaScript.

**Comment by jainaman224** [comment]
@KanchanThareja Go ahead.

**Comment by jainaman224** [comment]
@KanchanThareja Are you working on this?

**Comment by KanchanThareja** [comment]
@jainaman224 Yes I am.

**Comment by jainaman224** [comment]
@shahkv95 Are you working on it?

**Comment by shahkv95** [comment]
I already completed it and sent the PR. I don't know where have I stucked. Please guide me.
