### ISSUE TITLE
Reverse Delete Algorithm

### ISSUE THREAD

**Issue by shahkv95** [jainaman224/Algo_Ds_Notes#634]
The main feature of the Reverse Delete ALgorithm is to delete an edge if on doing so, it doesn't leads to disconnection of graph.
I request @jainaman224 to label it as 'difficult'(if you feel so) along with 'gssoc'.
Thank you so much.

**Comment by shahkv95** [comment]
The language I will work on will be C++. @jainaman224

**Comment by jainaman224** [comment]
@shahkv95 We are unable to label the issue before hand. As we see the code and learn the algorithm ourselves as well. On that basis we mark that PR.

I would suggest you to code in C as well. As it is similar to C++ for all issues you take up. If you looking to gain more points.

**Comment by shahkv95** [comment]
Ohk @jainaman224 .

**Comment by jainaman224** [comment]
@shahkv95 Are you working in it?

**Comment by shahkv95** [comment]
I have already sent the PR for the same.

**Comment by jainaman224** [comment]
I am unable to find the PR. Can you please refer this issue in PR.
