### ISSUE TITLE
Implement Lazy propogation segmentation tree in C++

### ISSUE THREAD

**Issue by gupta2140** [jainaman224/Algo_Ds_Notes#635]
Implement Lazy propogation segmentation tree to support range update and queries on sum, maximum and minimum in a single code.

**Comment by dshahid380** [comment]
Are you still working on this?

**Comment by somya-kapoor** [comment]
@jainaman224 I would like to work on it . Please assign this to me.

**Comment by jainaman224** [comment]
@somya-kapoor Go ahead.
