### ISSUE TITLE
Add Kosaraju's algorithm for finding number of SCC in a directed graph

### ISSUE THREAD

**Issue by gupta2140** [jainaman224/Algo_Ds_Notes#638]

**Comment by shahkv95** [comment]
I wish to take up this issue @gupta2140 @jainaman224

**Comment by jainaman224** [comment]
@shahkv95 Please complete assigned issues first.

**Comment by gupta2140** [comment]
@shahkv95 any progress on the task?

**Comment by shreyasrivastava936** [comment]
Hi! I want to work on this issue. please assign this task to me for GSSoC'20.
