### ISSUE TITLE
Add Digit DP

### ISSUE THREAD

**Issue by gupta2140** [jainaman224/Algo_Ds_Notes#640]
Input 2 numbers L and R (where 0 <= L <= R <= 10^10) and find the number of integers in this range which have at max 7 non-zero digits in it.

**Comment by kritigoyal** [comment]
I would like to work on it if this issue hasn't  been resolved yet. And can we code this in any programming language? And are there any more constraints or just the problem stated : (Input 2 numbers L and R (where 0 <= L <= R <= 10^10) and find the number of integers in this range which have at max 7 non-zero digits in it.)

**Comment by gupta2140** [comment]
1. Sure, you can work on this, it hasn't been resolved yet.
2. You can code in any language, but preferably C++ first (most commonly understood by everyone), then you can implement it in other languages as well.
3. There are no more constraints other than the mentioned one. However, if you need more information/help, feel free to ask.

**Comment by Naba7** [comment]
Can I be assigned this issue? @jainaman224

**Comment by gupta2140** [comment]
@kritigoyal are you still working on it?

**Comment by Naba7** [comment]
So, can I take it up? @gupta2140

**Comment by kritigoyal** [comment]
@gupta2140 sir I wrote the code and committed the file. Can you please let
me know the issue with it.

**Comment by jainaman224** [comment]
@gupta2140 Please have a look.

**Comment by shreyasrivastava936** [comment]
Hi! I want to work on this issue in Java. please assign this task to me for GSSoC'20.

**Comment by mugdhajoshi** [comment]
I want to work on this issue in Python as part of GSSoC 2020. Please assign it to me
