### ISSUE TITLE
Implement multiplicative inverse using Fermat's little theorem in C++

### ISSUE THREAD

**Issue by gupta2140** [jainaman224/Algo_Ds_Notes#642]
Given two numbers 'a' and 'p', where 'a' is any positive non-zero integer and 'p' is a prime number, find the multiplicative inverse of 'a' (mod p) using Fermat's little theorem.

**Comment by MastersAbh** [comment]
Isn't it already done #606 ?

**Comment by gupta2140** [comment]
Oops, yeah I didn't see that. Thanks.
