### ISSUE TITLE
Pigeonhole Sort in c and c++

### ISSUE THREAD

**Issue by somya-kapoor** [jainaman224/Algo_Ds_Notes#649]

**Comment by p-rit** [comment]
I want to work on this

**Comment by jainaman224** [comment]
@somya-kapoor You can't claim too many issues at the same time.

**Comment by jainaman224** [comment]
@p-rit Please choose languages other than c and c++.

**Comment by p-rit** [comment]
Python would work?

**Comment by jainaman224** [comment]
@p-rit Go ahead.

**Comment by somya-kapoor** [comment]
@jainaman224  Please assign me this issue as I have completed all the other assigned issue.

**Comment by jainaman224** [comment]
@somya-kapoor Go ahead.
