### ISSUE TITLE
Mo's Algorithm in C

### ISSUE THREAD

**Issue by tusharsabhani** [jainaman224/Algo_Ds_Notes#653]

**Comment by tusharsabhani** [comment]
I would like to take this task

**Comment by jainaman224** [comment]
Go ahead.

**Comment by tusharsabhani** [comment]
I am having some problem in implementing it so you can assign this issue to someone else or close it.

**Comment by jainaman224** [comment]
Ok

**Comment by ayanujju** [comment]
Can I work on this?

**Comment by jainaman224** [comment]
@ayanujju Go ahead.

**Comment by jainaman224** [comment]
@ayanujju Are you working on it?

**Comment by ayanujju** [comment]
Yes Sir. Please give me two more days.

**Comment by AkshitAggarwal** [comment]
If this issue is still open, or if the C++ code is required I can implement it.

**Comment by jainaman224** [comment]
@AkshitAggarwal It is already implemented.

**Comment by somya-kapoor** [comment]
@jainaman224 I would like to work on it. Please assign this to me.

**Comment by jainaman224** [comment]
@somya-kapoor Go ahead.
