### ISSUE TITLE
Longest common Substring in C++, Java and Python.

### ISSUE THREAD

**Issue by prashant-mahanta** [jainaman224/Algo_Ds_Notes#667]
I want to add the Longest common substring algorithm which is commonly known as LCS in C++, Java, and Python.
The Time complexity of the algorithm `O(n*m)`  and Space complexity `O(n)` using DP
Link: [Longest Common Substring_Wikipedia](https://en.wikipedia.org/wiki/Longest_common_substring_problem)
Can I go ahead with this?

**Comment by jainaman224** [comment]
It is already assigned.
https://github.com/jainaman224/Algo_Ds_Notes/issues/610

**Comment by prashant-mahanta** [comment]
@jainaman224 my approach is for strings not array and with a space complexity of O(n). The PR which is merged for **longest common subsequence** is for integer array with a space complexity of O(m*n).

**Comment by jainaman224** [comment]
@prashant-mahanta Is there any specific name to the algorithm?

**Comment by prashant-mahanta** [comment]
@jainaman224 No, the **Longest Common Substring** is usually the problem called. It's the implementation difference, instead of a m*n matrix we can keep a 2*n matrix to reduce the space complexity(as we only need the adjacent rows only) from O(m*n) to O(n). 
Should I go ahead?
