### ISSUE TITLE
Burrows-Wheeler Data Transform Algorithm

### ISSUE THREAD

**Issue by Priyankasaggu11929** [jainaman224/Algo_Ds_Notes#690]
@jainaman224 can I implement this?

**Comment by jainaman224** [comment]
@Priyankasaggu11929 Go ahead. Please mention languages you are handling.

**Comment by Priyankasaggu11929** [comment]
@jainaman224 I will implement this in javascript.

**Comment by jainaman224** [comment]
Ok

**Comment by pankajpoply45** [comment]
I want to work in java. @jainaman224

**Comment by jainaman224** [comment]
@pankajpoply45 Go ahead.

**Comment by pankajpoply45** [comment]
@jainaman224  created pull request #770
