### ISSUE TITLE
Adding Strassen's matrix multiplication Algorithm in c,python and java

### ISSUE THREAD

**Issue by Jaseemck** [jainaman224/Algo_Ds_Notes#695]
Strassen's algorithm is used to find product of two matrix with more efficiency than the conventional one.

**Comment by Jaseemck** [comment]
Can i work on this to implement in java,c and python

**Comment by jainaman224** [comment]
@Jaseemck Go ahead.

**Comment by jainaman224** [comment]
@Jaseemck Are you working in python?
