### ISSUE TITLE
Program for Jump_Search in JS,cpp,Java,python

### ISSUE THREAD

**Issue by khushal87** [jainaman224/Algo_Ds_Notes#697]
can i start working on it ??

**Comment by jainaman224** [comment]
@khushal87 Go ahead.

**Comment by Bhairavi-shah** [comment]
Can I start working on the Python code for this ??

**Comment by jainaman224** [comment]
@Bhairavi-shah It is already assigned to Khushal.

**Comment by khushal87** [comment]
@Bhairavi-shah I have already done it
