### ISSUE TITLE
Knuth_Morris_Pratt_Algorithm in java is not available

### ISSUE THREAD

**Issue by sez98** [jainaman224/Algo_Ds_Notes#706]
I would like to complete code for this in java

**Comment by jainaman224** [comment]
Don't rush find complete all other issues. We have a policy of assigning max 2 unfinished issues.

**Comment by jainaman224** [comment]
Once you are done with other issues. Comment here and we will assign it you.

**Comment by sez98** [comment]
I have completed all the other issues that I referenced. All the three issues have been done with the pull requests pending.

**Comment by jainaman224** [comment]
@sez98 Go ahead.

**Comment by jainaman224** [comment]
@sez98 Are you still working on it?

**Comment by sez98** [comment]
yes... i am... i ll complete it in a few days.

**Comment by archi14** [comment]
@jainaman224 can I work on this?

**Comment by jainaman224** [comment]
@archi14 Go ahead.

**Comment by archi14** [comment]
@jainaman224 there is already a java one in KMP folder
https://github.com/jainaman224/Algo_Ds_Notes/blob/master/Knuth_Morris_Pratt_Algorithm/KMP.java

**Comment by jainaman224** [comment]
Ohh sorry.
Thanks for having a look.
