### ISSUE TITLE
Doubly Linked List in C

### ISSUE THREAD

**Issue by gauravburjwal** [jainaman224/Algo_Ds_Notes#718]
I'm am GSSoC participant.
I would like to work on Doubly Linked List in C

**Comment by jainaman224** [comment]
Go ahead. If there is no implementation.

**Comment by Maxz2136** [comment]
I am a Gssoc participant. I would like to work on this issue.

**Comment by jainaman224** [comment]
@Maxz2136 Please specify the language.

**Comment by Maxz2136** [comment]
> @Maxz2136 Please specify the language.

Language:C++ or C

**Comment by jainaman224** [comment]
Sorry it is already implemented for C++ and claimed for C.
