### ISSUE TITLE
Comb Sort in c 

### ISSUE THREAD

**Issue by somya-kapoor** [jainaman224/Algo_Ds_Notes#732]

**Comment by jainaman224** [comment]
Once you are done with other issues. I will assign you this.
There is a 2 issue policy.

**Comment by shadow989** [comment]
can i work on this issue ?

**Comment by Karna98** [comment]
Is this issue available? I want to work on it.

**Comment by jainaman224** [comment]
@shadow989 @Karna98 You can work on this issue instead of c.
First priority is given to @shadow989 among you.

**Comment by Karna98** [comment]
I am implementing Comb Sort in php.
