### ISSUE TITLE
Miller–Rabin Primality Test

### ISSUE THREAD

**Issue by Priyankasaggu11929** [jainaman224/Algo_Ds_Notes#751]
@jainaman224 Can I implement this in Python?

**Comment by jainaman224** [comment]
@Priyankasaggu11929 Go ahead.

**Comment by pankajpoply45** [comment]
Can I implement it in java @jainaman224

**Comment by jainaman224** [comment]
@pankajpoply45 Go ahead.

**Comment by jainaman224** [comment]
@pankajpoply45 Are you still working on it?
