### ISSUE TITLE
README for Bucket Sort

### ISSUE THREAD

**Issue by marwahmanbir** [jainaman224/Algo_Ds_Notes#753]
I would like to prepare an explanation/readme for Bucket Sort.
Also, there are two directories for this algorithm. One has implementation in C only & the other one has implementation in other languages. I'll merge the content of both into a single directory.

**Comment by jainaman224** [comment]
@marwahmanbir Go ahead.

**Comment by marwahmanbir** [comment]
Fixed.

**Comment by jainaman224** [comment]
Please close issue after PR getting merged.
