### ISSUE TITLE
Breadth First Search in C

### ISSUE THREAD

**Issue by gauravburjwal** [jainaman224/Algo_Ds_Notes#755]
I'm GSSoC participant.
I would like to work on Breadth First Search in C

**Comment by jainaman224** [comment]
@gauravburjwal Go ahead.

**Comment by divs30** [comment]
May I work on it in cpp and python

**Comment by jainaman224** [comment]
@divs30 It is already implemented.

**Comment by susiejojo** [comment]
I have written the code but when I try to push the file it shows this error:
![Error](https://user-images.githubusercontent.com/42820001/55107311-099dee00-50f7-11e9-9c63-20eb7948a69b.png)

**Comment by susiejojo** [comment]
I'm an RGSoC participant. Here's my profile link: https://teams.railsgirlssummerofcode.org/users/4080
I have created a pull request with the required code uploaded in C.
Eagerly waiting for your response!

**Comment by jainaman224** [comment]
@gauravburjwal Are you working on it?

**Comment by jainaman224** [comment]
@susiejojo It is already assigned to Gaurav. If he is not working on it then I will look into your PR.

**Comment by susiejojo** [comment]
Oh sorry I didn't notice... But I created a pull request with the code I wrote in C already... So what do I do next?

**Comment by gauravburjwal** [comment]
@jainaman224  Yes I'm working on it and I will send PR as soon as possible. Currently busy with my sessional test.

**Comment by jainaman224** [comment]
@susiejojo Please close that PR.

**Comment by jainaman224** [comment]
@susiejojo You can reopen your PR.
