### ISSUE TITLE
DDA line drawing algo

### ISSUE THREAD

**Issue by tusharsabhani** [jainaman224/Algo_Ds_Notes#756]
This algo is used to draw straight lines

**Comment by tusharsabhani** [comment]
I would like to implement in C,C++ and Java

**Comment by jainaman224** [comment]
@tusharsabhani Go ahead.

**Comment by tusharsabhani** [comment]
Having problem in java implementation.
You may assign to someone else

**Comment by kunal-kushwaha** [comment]
@jainaman224 I would like to implement this in Java.

**Comment by jainaman224** [comment]
@kunal-kushwaha Go ahead.

**Comment by jainaman224** [comment]
@tusharsabhani Are you working on it?

**Comment by tusharsabhani** [comment]
Yes
