### ISSUE TITLE
N-Queens Problem

### ISSUE THREAD

**Issue by marwahmanbir** [jainaman224/Algo_Ds_Notes#757]
I would like to add N-Queens Problem that uses backtracking technique, in the following languages:
- C/C++
- Java
- Python

**Comment by jainaman224** [comment]
@marwahmanbir Go ahead.

**Comment by devRD** [comment]
can I work on this?

**Comment by jainaman224** [comment]
@devRD Please specify the language.

**Comment by devRD** [comment]
@jainaman224 I would like to work on it with JavaScript.

**Comment by marwahmanbir** [comment]
@devRD You can go for it in JavaScript.

**Comment by kritigoyal** [comment]
@jainaman224  I would like to work on it with Python

**Comment by jainaman224** [comment]
@kritigoyal Manbir is already working on it. Please have a look at other issues.

**Comment by kritigoyal** [comment]
Okay

**Comment by gupta2140** [comment]
Is it the N-Queen problem? If yes, kindly rename the issue to include full name of the problem.

**Comment by kunal-kushwaha** [comment]
@jainaman224 I would like to implement this in Java.

**Comment by m-code12** [comment]
@jainaman224 , @asha15 , I can implement this in Rust and it hasn't been implemented yet. Please assign it to me .
