### ISSUE TITLE
Red_Black_Tree in java

### ISSUE THREAD

**Issue by aneesh98** [jainaman224/Algo_Ds_Notes#768]
Would like to write java implementation of Red Black Trees

**Comment by jainaman224** [comment]
@aneesh98 Go ahead.

**Comment by divs30** [comment]
May I work on it in C and cpp

**Comment by divs30** [comment]
and python as well

**Comment by jainaman224** [comment]
@divs30 It is already implemented in C, cpp and python.

**Comment by jainaman224** [comment]
@aneesh98 Are you working on it?

**Comment by aneesh98** [comment]
Yes I am.
