### ISSUE TITLE
Assembly Line Scheduling

### ISSUE THREAD

**Issue by Karna98** [jainaman224/Algo_Ds_Notes#774]
Language Implementation: 
- [x] C
- [x] C++
- [x] Python
- [x] Java
- [x] Php
- [x] C#

**Comment by Karna98** [comment]
I would like to work on it.

**Comment by jainaman224** [comment]
@Karna98 Go ahead.

**Comment by jainaman224** [comment]
@Karna98 Are you working on it?

**Comment by Karna98** [comment]
I'm going to take some time but will try to implement it ASAP.

**Comment by singh-shreya6** [comment]
I would like to work on it in C++, Java and Python

**Comment by Karna98** [comment]
> @jainaman224 I would like to work on it in C++, Java and Python

I'm currently working on it.

**Comment by jainaman224** [comment]
@singh-shreya6 It would be great if you can another issue. I leave this decision upto you.
@Karna98 It was unassigned due to inactivity. I hope Shreya will let you work. Please show some activity from next time.

**Comment by singh-shreya6** [comment]
Yes sure, continue if you are working on it.
I thought of taking it up due to inactivity.

**Comment by jainaman224** [comment]
Thanks @singh-shreya6.
