### ISSUE TITLE
shaker sort algorithm in ruby

### ISSUE THREAD

**Issue by AnshitaVishwa** [jainaman224/Algo_Ds_Notes#782]
sir i would like to implement shaker_sort algorithm in ruby language.

**Comment by divs30** [comment]
Sir may I implement in c,cpp and python.

**Comment by jainaman224** [comment]
@divs30 It is already implemented in c, cpp and python.
@AnshitaVishwa Go ahead.

**Comment by jainaman224** [comment]
@AnshitaVishwa Are you working on it?
