### ISSUE TITLE
Rabin_karp Algorithm in java 

### ISSUE THREAD

**Issue by Anshuvats** [jainaman224/Algo_Ds_Notes#789]
the Rabin–Karp algorithm or Karp–Rabin algorithm is a string-searching algorithm that uses hashing to find any one of a set of pattern strings in a text. For text of length n and p patterns of combined length m, its average and best case running time is O(n+m) in space O(p), but its worst-case time is O(nm).

**Comment by gupta2140** [comment]
Please correct the issue title "Rabin_carp" --> "Rabin_karp"

**Comment by Anshuvats** [comment]
okay,sir

**Comment by jainaman224** [comment]
@Anshuvats Are you working on it?

**Comment by Anshuvats** [comment]
yes, sir

**Comment by archi14** [comment]
@jainaman224 please assign this to me.

**Comment by jainaman224** [comment]
@archi14 Go ahead.
