### ISSUE TITLE
Chocolate distribution problem in C,C++,python ,java issue 

### ISSUE THREAD

**Issue by divs30** [jainaman224/Algo_Ds_Notes#790]
The problem statement states that
Given an array of k integers where each value represents number of chocolates in a packet. Each packet can have variable number of chocolates. There are p students, the task is to distribute chocolate packets such that:

Each student gets one packet.
The difference between the number of chocolates in packet with maximum chocolates and packet with minimum chocolates given to the students is minimum.

**Comment by divs30** [comment]
I would like to work on it C,C++,java ,python

**Comment by jainaman224** [comment]
@divs30 Go ahead.

**Comment by jainaman224** [comment]
@divs30 Are you working on it?

**Comment by divs30** [comment]
yes
