### ISSUE TITLE
EggDrop problem in Java

### ISSUE THREAD

**Issue by kunal-kushwaha** [jainaman224/Algo_Ds_Notes#794]
@jainaman224 I would like to work on this.

**Comment by jainaman224** [comment]
Wait for issue to be assigned before working on it.
Please give some information about this problem.

**Comment by kunal-kushwaha** [comment]
@jainaman224 Alright.
The problem is that there is an N-Storey building and you are given e eggs. When you drop an egg from any floor of the building, the egg will either break or survive the fall. If the egg survives, then it would have survived any lesser fall. If the egg breaks, then any greater fall would have broken it as well. The eggs are all identical and interchangeable. You’d like to find the minimum height that will break an egg. What is the fewest number of drops in which you are guaranteed to find the right floor?
