### ISSUE TITLE
Trapping rain water between tower problem in c,cpp,java,python

### ISSUE THREAD

**Issue by divs30** [jainaman224/Algo_Ds_Notes#808]
this problems states to find out maximum water trapped in between buildings of different height s

i.e.We have an array where each element represents height of a tower. If it starts raining, what is the amount of water that can be collected between the towers

**Comment by divs30** [comment]
I would like to work on it in c,cpp,java,python

**Comment by jainaman224** [comment]
@divs30 Go ahead.

**Comment by jainaman224** [comment]
@divs30 Are you working on it?

**Comment by divs30** [comment]
yes

**Comment by bvishal8510** [comment]
@jainaman224 may I work on this issue?

**Comment by jainaman224** [comment]
@bvishal8510 Go ahead.
