### ISSUE TITLE
Sparse Table Implementation in Python and Java

### ISSUE THREAD

**Issue by prashant-mahanta** [jainaman224/Algo_Ds_Notes#810]
I want to implement Sparse Table in Python and Java. It is available only in C and C++.

**Comment by jainaman224** [comment]
@prashant-mahanta Go ahead.

**Comment by jainaman224** [comment]
@prashant-mahanta Are you working on it?

**Comment by prashant-mahanta** [comment]
@jainaman224  Yes I am.
