### ISSUE TITLE
Number of Islands Problem in C/C++, Java, Python, C#, PHP and JavaScript

### ISSUE THREAD

**Issue by ayanujju** [jainaman224/Algo_Ds_Notes#815]
In the problem, a matrix is given in which only O's and 1's. We have to find total number of clusters formed by elements with value 1.  For example, in the below shown matrix there are total four such clusters. 

matrix[M][N] =  {{'**1**', 'O', 'O', 'O', 'O', 'O'},
                           {'**1**', 'O', '**1**', '**1**', '**1**', '**1**'},
                           {'O', 'O', 'O', 'O', 'O', 'O'},
                           {'**1**', '**1**', '**1**', 'O', '**1**', '**1**'},
                           {'**1**', '**1**', '**1**', 'O', '**1**', '**1**'},
                           {'O', 'O', 'O', 'O', '**1**', '**1**'},
                          };
Output: Number of islands is 4

This problem is also known as '**Number of Islands**' problem.

**Comment by ayanujju** [comment]
I would like to work on this in C/C++ and Python

**Comment by jainaman224** [comment]
@ayanujju Are you working on it?

**Comment by ayanujju** [comment]
Yes Sir.

**Comment by singh-shreya6** [comment]
@jainaman224 I would like to do his in C++, Java and Python

**Comment by jainaman224** [comment]
Go ahead.
