### ISSUE TITLE
Length of Longest Bitonic Subsequence for a given array in C/C++, Java, Python, PHP and JavaScript

### ISSUE THREAD

**Issue by ayanujju** [jainaman224/Algo_Ds_Notes#816]
Problem Statement:
Given an array arr[0 … n-1] containing n positive integers, a subsequence of arr[ ] is called Bitonic if it is first increasing first and then decreasing. 
For example:
  Input arr[ ] = {1, 11, 2, 10, 4, 5, 2, 1}
  Output: 6 
A Longest Bitonic Subsequence of length 6 is {1, 2, 10, 4, 2, 1}.

**Comment by ayanujju** [comment]
I want to work on this issue in C/C++ and Python. Please assign it to me.

**Comment by jainaman224** [comment]
@ayanujju Are you working on it?

**Comment by ayanujju** [comment]
Yes Sir.

**Comment by ayanujju** [comment]
Sir, please assign this issue to me.

**Comment by aadhar54** [comment]
I would like to work on this issue. Please assign it to me for Java .

**Comment by shreyasrivastava936** [comment]
Hi! I want to work on this issue . please assign this task to me for GSSoC'20.
