### ISSUE TITLE
Count Inversions in an array using Merge Sort method

### ISSUE THREAD

**Issue by kaustubh-pandey** [jainaman224/Algo_Ds_Notes#817]
I wanted to add an implementation of counting inversions in an array using Merge sort method in C++. Can I work on this?

**Comment by jainaman224** [comment]
@kaustubh-pandey Are you working on it?

**Comment by kaustubh-pandey** [comment]
Yes , I am working on it

**Comment by mark-nakachon** [comment]
if u assign this issue to me i can fix it in less than an hour

**Comment by jainaman224** [comment]
@mark-nakachon Please have a look at other issue.
