### ISSUE TITLE
Hamiltonian Cycle

### ISSUE THREAD

**Issue by marwahmanbir** [jainaman224/Algo_Ds_Notes#820]
Add an algorithm to find Hamiltonian Cycle, in the following languages:
- C/C++
- Python
- Java

**Comment by KanchanThareja** [comment]
@jainaman224 I want to work on it.

**Comment by jainaman224** [comment]
Go ahead.

**Comment by shahkv95** [comment]
I would like to work on this issue - I will be able to do in C++, python and C

**Comment by jainaman224** [comment]
@shahkv95 Go ahead.

**Comment by HarshitaSahai** [comment]
Is this issue still open ? Can I work on it?

**Comment by marwahmanbir** [comment]
@shahkv95 are you working on it?

**Comment by marwahmanbir** [comment]
@HarshitaSahai meanwhile you can do this in Java and JavaScript.
Make sure that you do not copy the code from anywhere. We do check for plagiarism. @shahkv95 @HarshitaSahai

**Comment by HarshitaSahai** [comment]
Sorry I'm not familiar with Java or JavaScript.

**Comment by marwahmanbir** [comment]
You can take other issues then, or open a new one.

**Comment by aadhar54** [comment]
I would like to work on this issue. Please assign it to me for Java .

**Comment by shreyasrivastava936** [comment]
Hi! I want to work on this issue. please assign this task to me for GSSoC'20.
