### ISSUE TITLE
Longest Palindromic Subsequence in C++, Java, Python

### ISSUE THREAD

**Issue by MastersAbh** [jainaman224/Algo_Ds_Notes#831]
Please assign this issue to me.

**Comment by jainaman224** [comment]
@MastersAbh Are you working on it?

**Comment by MastersAbh** [comment]
Yes. I am working on it.

**Comment by mark-nakachon** [comment]
@jainaman224 if you assign this issue to me I will fix this in less than an hour

**Comment by jainaman224** [comment]
@mark-nakachon Hey, It is not about being quick. It is about learning. Please have a look at other issue.
