### ISSUE TITLE
Longest Repeating Subsequence in C++, Java and Python

### ISSUE THREAD

**Issue by prashant-mahanta** [jainaman224/Algo_Ds_Notes#844]
To find the longest repeating subsequence in C++, Java, and Python

Can I work on this?

**Comment by jainaman224** [comment]
@prashant-mahanta Go ahead.
And throw some light on it.

**Comment by prekshajagetiya123** [comment]
As no one is assigned to this issue, can I also contribute to the same?

**Comment by jainaman224** [comment]
@prekshajagetiya123 It is already assigned to Prashant. Please have a look at other issues.

**Comment by jainaman224** [comment]
@prashant-mahanta Are you working on it?

**Comment by prashant-mahanta** [comment]
@jainaman224 Yes I am. I had some medical issues so it got delayed soon be sending the PR.
