### ISSUE TITLE
Prefix_sum in C

### ISSUE THREAD

**Issue by susiejojo** [jainaman224/Algo_Ds_Notes#849]
Hey this is Dipanwita. I am an RGSoC participant this year. I'd like to implement prefix sum in C.

**Comment by jainaman224** [comment]
@susiejojo Go ahead.

**Comment by susiejojo** [comment]
Sir I've created a pull request with the required code in C. Looking forward to your review on it.

**Comment by susiejojo** [comment]
Commit id 2ee4f43

**Comment by susiejojo** [comment]
Commit 66a73c8

**Comment by susiejojo** [comment]
Commit fa06829
