### ISSUE TITLE
Fix bug in Activity Selection quoted example in all languages

### ISSUE THREAD

**Issue by singh-shreya6** [jainaman224/Algo_Ds_Notes#853]
start[] = {1, 3, 1, 5, 8, 6}
finish[] = {2, 6, 6, 7, 10, 8}
In all the 6 languages implemented, the example quoted is wrong, as the array should be sorted by its finish time to implement activity selection.

**Comment by jainaman224** [comment]
Please fix it. I have made blunder.

**Comment by MastersAbh** [comment]
Correct. Must be fixed.

**Comment by singh-shreya6** [comment]
@rishabhgarg25699 I was asked to split the PR into two PRs. Why did you close this issue after merging only C, C++ and Go implementations. The implementations in Java, Javascript and Python are not yet merged. Please look into it.
