### ISSUE TITLE
Cohen Sutherland Line Clipping Algorithm

### ISSUE THREAD

**Issue by marwahmanbir** [jainaman224/Algo_Ds_Notes#858]
I would like to add the Cohen Sutherland algorithm in C/C++

**Comment by prekshajagetiya123** [comment]
Could you please assign this to me? I would like to work on this issue.

**Comment by marwahmanbir** [comment]
Hey @prekshajagetiya123 I will be working on C/C++ and Java implementations. You can work on other languages like JavaScript, if @jainaman224 allows.

**Comment by prekshajagetiya123** [comment]
Hi! Actually I am comfortable wth C++, so if you say can I please work on that!

**Comment by prekshajagetiya123** [comment]
ok, I would also like to implement it in Python. Should I proceed?

**Comment by jainaman224** [comment]
@marwahmanbir @prekshajagetiya123 Go ahead.
