### ISSUE TITLE
N-Queen Problem in cpp,java,go,python and js

### ISSUE THREAD

**Issue by khushal87** [jainaman224/Algo_Ds_Notes#864]
Can i start working on it? I know someone is already doing but he may be working on JS implementation so please confirm and say whether i can work on the other one ?

**Comment by jainaman224** [comment]
It is already implemented in some languages. Have a look at https://github.com/jainaman224/Algo_Ds_Notes/tree/master/Queens_Problem.

**Comment by khushal87** [comment]
can i go with go lang and if possible JS??

**Comment by jainaman224** [comment]
Go ahead with go, js and cpp.
