### ISSUE TITLE
Number Convertions in different languages

### ISSUE THREAD

**Issue by khushal87** [jainaman224/Algo_Ds_Notes#865]
Can i work on it ??

**Comment by jainaman224** [comment]
Please specify the language.

**Comment by khushal87** [comment]
c,c++,java,python,js

**Comment by mruna7** [comment]
can we work on it?

**Comment by shreyasrivastava936** [comment]
Hi! I want to work on this issue in Java. please assign this task to me for GSSoC'20.

**Comment by jainaman224** [comment]
@mruna7 Go ahead.
Please select a language/

**Comment by mruna7** [comment]
Thankyou sir !I will implement it in java

**Comment by abhijeet010304** [comment]
Sir I would like to work on it in C++

**Comment by mruna7** [comment]
[Binary_To_Octal.txt](https://github.com/jainaman224/Algo_Ds_Notes/files/4469113/Binary_To_Octal.txt)

**Comment by mruna7** [comment]
#2432 #2291
