### ISSUE TITLE
Scheduling Algorithm in c++

### ISSUE THREAD

**Issue by somya-kapoor** [jainaman224/Algo_Ds_Notes#876]
I want to implement following algorithm in c++ :
1. first come, first served (FCFS)
2.Shortest Remaining Time First (SRTF);Non-Preemptive
3.Shortest Remaining Time First (SRTF);Preemptive
4.Priority Scheduling

**Comment by somya-kapoor** [comment]
Can I implement it in C also?

**Comment by jainaman224** [comment]
@somya-kapoor Go ahead. If it is not implemented yet.
