### ISSUE TITLE
Next Smallest Palindrome

### ISSUE THREAD

**Issue by KanchanThareja** [jainaman224/Algo_Ds_Notes#886]
Eg: Next smallest palindrome of 123 is 131

I want to implement this in c++, java, python and C#.

**Comment by jainaman224** [comment]
Go ahead

**Comment by prekshajagetiya123** [comment]
can I implement the same in C?

**Comment by jainaman224** [comment]
@prekshajagetiya123 Go ahead.

**Comment by KanchanThareja** [comment]
@jainaman224 i am working on this issue

**Comment by jainaman224** [comment]
@KanchanThareja Try to show some activity within a week.

**Comment by KanchanThareja** [comment]
@jainaman okay.
