### ISSUE TITLE
Ugly number in c and c++

### ISSUE THREAD

**Issue by somya-kapoor** [jainaman224/Algo_Ds_Notes#896]

**Comment by AkshitAggarwal** [comment]
I'd like to work on this issue, using C++

**Comment by jainaman224** [comment]
@AkshitAggarwal Please take another issue or language. It is already assigned.

**Comment by AkshitAggarwal** [comment]
If someone is doing it in C++, maybe I can do it in C?

**Comment by jainaman224** [comment]
It is assigned in both languages to somya.
