### ISSUE TITLE
0 1 BFS in cpp

### ISSUE THREAD

**Issue by susiejojo** [jainaman224/Algo_Ds_Notes#906]
Given a graph where every edge has weight as either 0 or 1. A source vertex is also given in the graph. Find the shortest path from source vertex to every other vertex.

**Comment by jainaman224** [comment]
Please first have a look at issues already assigned to you.

**Comment by susiejojo** [comment]
The issue assigned to me was solved and the PR was merged #861

**Comment by susiejojo** [comment]
Also, I'm an RGSoC participant sir, but the tag says gssoc19

**Comment by jainaman224** [comment]
@susiejojo I apologise for misunderstanding. Go ahead.

**Comment by susiejojo** [comment]
Commit : 77eb663

**Comment by susiejojo** [comment]
Commit 7eb6633
