### ISSUE TITLE
2 pass algorithm for macro

### ISSUE THREAD

**Issue by kritigoyal** [jainaman224/Algo_Ds_Notes#918]
I would like to add a two pass algorithm for macro in C language. Please assign me this task.

**Comment by jainaman224** [comment]
It would be great if you can let us a bit about this.

**Comment by kritigoyal** [comment]
This algorithm is used for identifying macro name and performing expansion.
Pass 1 of the 2 pass algorithm is used to recognize macro definition and
save it while Pass 2 of 2 pass algorithm is used to recognize macro call
and perform macro expansion.

**Comment by jainaman224** [comment]
@kritigoyal Are you still working on it?

**Comment by kritigoyal** [comment]
I have created the file but unfortunately i did'nt use git branching. I
wrote the code but was facing slight issue regarding committing. Due to
some prior work i was'nt able to figure out that issue and solve it.

**Comment by jainaman224** [comment]
Will you be working on it?

**Comment by kritigoyal** [comment]
Yes I have written the full code it's only about committing the file that's
an issue. Currently I am a bit busy that's why I am unable to fix it
