### ISSUE TITLE
Making Search easier

### ISSUE THREAD

**Issue by riya-17** [jainaman224/Algo_Ds_Notes#929]
@jainaman224 I think it is quite difficult to search throughout the repository which algorithm is implemented and which is not. We can arrange them in sub folders like. we can create a Sorting folder and plane all sorting algorithms inside this folder.

**Comment by jainaman224** [comment]
I am thinking around it. We can definitely do this.

**Comment by riya-17** [comment]
@jainaman224 I am working on Travis I am halfway through it, Should I start working on this as well?

**Comment by riya-17** [comment]
Hey @jainaman224

**Comment by jainaman224** [comment]
Go ahead.

**Comment by jainaman224** [comment]
Please fix naming as well.

**Comment by riya-17** [comment]
@jainaman224 sure. Thanks :)

**Comment by jainaman224** [comment]
@riya-17 Let's discuss on gitter. I have something else in mind.

**Comment by riya-17** [comment]
@jainaman224 I have proposed a pull request. Sorry, I haven't seen this comment earlier. I will connect with you on gitter
