### ISSUE TITLE
Lowest Common Ancestor of a Binary Search Tree

### ISSUE THREAD

**Issue by sakshichahal53** [jainaman224/Algo_Ds_Notes#946]
According to the definition of LCA on Wikipedia: “The lowest common ancestor is defined between two nodes p and q as the lowest node in T that has both p and q as descendants (where we allow a node to be a descendant of itself)."

![lca](https://user-images.githubusercontent.com/25123590/55701212-effe7f80-59ef-11e9-821f-ad031f2903a5.png)

I'd like to contribute to this issue in C++, Java and Python
-RGSoC participants

**Comment by ahegde3** [comment]
Can i take this issue?

**Comment by sakshichahal53** [comment]
I'd work on it.
