### ISSUE TITLE
Connect nodes at same level in a Binary Tree

### ISSUE THREAD

**Issue by sakshichahal53** [jainaman224/Algo_Ds_Notes#947]
Hi @jainaman224, I'd like to make a feature request for the problem: 
Connect all the adjacent nodes at the same level in a binary tree. 

I'd like to contribute to this issue for C++ .

**Comment by sakshichahal53** [comment]
May I work on it?

**Comment by shreyasrivastava936** [comment]
Hi! I would like to work on this issue. please assign this task to me for GSSoC'20.
