### ISSUE TITLE
Implementation of Quick Hull in python,cpp,javascript

### ISSUE THREAD

**Issue by mark-nakachon** [jainaman224/Algo_Ds_Notes#959]
I am assigning this issue to myself, please add the Gssoc label and i will soon add the PR

**Comment by marwahmanbir** [comment]
Hey @mark-nakachon, you can take only two issues at a time. Close the other ones and keep open only the two that you'll work on. Once you resolve the two you can go for the other two. Also, issues are approved by @jainaman224 first and then only you can start working on it.
