### ISSUE TITLE
Number Conversion (Decimal To Binary)

### ISSUE THREAD

**Issue by khushal87** [jainaman224/Algo_Ds_Notes#964]
can i start working on it ?

**Comment by nitink4472** [comment]
Is this issue still open?

**Comment by LovepreetSingh12** [comment]
I would like to contribute in this issue in JAVA as a part of GSSoC 2020..

**Comment by abhinashgiri** [comment]
I want to code in Python 3 as a part of GSSoC 20.

**Comment by Manas2520** [comment]
Can I try to resolve this issue in C++?

**Comment by jainaman224** [comment]
@LovepreetSingh12 Go ahead with Java.
@Manas2520 Go ahead with C++.

**Comment by Manas2520** [comment]
Since my examinations are going on,please allow me a time gap of one week so that I can focus on my exams.I will start contributing as soon as my exams are over.

**Comment by Manas2520** [comment]
Please assign me to this issue once again.I accidentally click the "unassign me" button while I was exploring GitHub.My sincere apologies.
