### ISSUE TITLE
Sudoku solver in javascript

### ISSUE THREAD

**Issue by mark-nakachon** [jainaman224/Algo_Ds_Notes#984]
implementation of sudoku solver in javascript
please add the Gssoc label and assign this issue to me

**Comment by ranjal007** [comment]
I would like to work on this issue 
please assign it to me for Gssoc20

**Comment by jainaman224** [comment]
@ranjal007 Go ahead

**Comment by priyanka2109** [comment]
I would like to contribute in c++

**Comment by ranjal007** [comment]
@jainaman224  Sir I have Implemented the code. I just need to know I have to upload all the files of Javascript, CSS, and HTML or I just have to upload the Javascript code.

**Comment by jainaman224** [comment]
@ranjal007 Please ask on `git_github` channel on slack.
