### ISSUE TITLE
README for Cocktail Sort

### ISSUE THREAD

**Issue by marwahmanbir** [jainaman224/Algo_Ds_Notes#997]
Add a README.md file to explain Cocktail Sort Algorithm. The file should contain the following:
- Explanation
- Algorithm
- Pseudocode
- Example
- Time Complexity

Also add images/GIFs to explain if possible.

**Comment by archi14** [comment]
@marwahmanbir I would like to work on this.

**Comment by marwahmanbir** [comment]
@archi14 Go for it :+1:
