### ISSUE TITLE
README for Comb Sort Algorithm

### ISSUE THREAD

**Issue by marwahmanbir** [jainaman224/Algo_Ds_Notes#998]
Add a README.md file to explain Comb Sort Algorithm. The file should contain the following:
- Explanation
- Algorithm
- Pseudocode
- Example
- Time Complexity

Also add images/GIFs to explain if possible.

**Comment by asha15** [comment]
@marwahmanbir shall work on this issue ?

**Comment by marwahmanbir** [comment]
@asha15 go for it.

**Comment by marwahmanbir** [comment]
@asha15 are you working on it?

**Comment by asha15** [comment]
@marwahmanbir yes ,i'll send a PR very soon
