### ISSUE TITLE
README for Shell Sort Algorithm

### ISSUE THREAD

**Issue by marwahmanbir** [jainaman224/Algo_Ds_Notes#999]
Add a README.md file to explain Shell Sort Algorithm. The file should contain the following:
- Explanation
- Algorithm
- Pseudocode
- Example
- Time Complexity

Also add images/GIFs to explain if possible.

**Comment by raibove** [comment]
Can I work on this issue 
Slack Username - Shweta

**Comment by marwahmanbir** [comment]
@raibove go for it.

**Comment by marwahmanbir** [comment]
@raibove are you working on it?

**Comment by raibove** [comment]
Yes Will try to submit it by tomorrow .

**Comment by asha15** [comment]
@marwahmanbir can i know is anyone working on this issue ?

**Comment by jainaman224** [comment]
@asha15 Go for it.

**Comment by asha15** [comment]
@jainaman224 Thank you.could you assign it for me,so i can send  a PR

**Comment by asha15** [comment]
@rishabhgarg25699 Please assign this to me.

**Comment by jainaman224** [comment]
@asha15 It is assigned to you.
